// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignment.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAssignmentAsset = `-- name: AddAssignmentAsset :exec
INSERT INTO assignment_assets (assignment_id,media_asset_id) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type AddAssignmentAssetParams struct {
	AssignmentID uuid.UUID `json:"assignment_id"`
	MediaAssetID uuid.UUID `json:"media_asset_id"`
}

func (q *Queries) AddAssignmentAsset(ctx context.Context, arg AddAssignmentAssetParams) error {
	_, err := q.db.Exec(ctx, addAssignmentAsset, arg.AssignmentID, arg.MediaAssetID)
	return err
}

const addSubmissionAsset = `-- name: AddSubmissionAsset :exec
INSERT INTO assignment_submission_assets (submission_id,media_asset_id) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type AddSubmissionAssetParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	MediaAssetID uuid.UUID `json:"media_asset_id"`
}

func (q *Queries) AddSubmissionAsset(ctx context.Context, arg AddSubmissionAssetParams) error {
	_, err := q.db.Exec(ctx, addSubmissionAsset, arg.SubmissionID, arg.MediaAssetID)
	return err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (id,organization_id,course_id,lesson_id,title,instructions,due_at,maximum_score,passing_score,allowed_file_types,maximum_submissions,is_required)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id, organization_id, course_id, lesson_id, title, instructions, due_at, maximum_score, passing_score, allowed_file_types, maximum_submissions, is_required, status, created_at, updated_at
`

type CreateAssignmentParams struct {
	ID                 uuid.UUID          `json:"id"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	CourseID           uuid.UUID          `json:"course_id"`
	LessonID           uuid.NullUUID      `json:"lesson_id"`
	Title              string             `json:"title"`
	Instructions       string             `json:"instructions"`
	DueAt              pgtype.Timestamptz `json:"due_at"`
	MaximumScore       pgtype.Numeric     `json:"maximum_score"`
	PassingScore       pgtype.Numeric     `json:"passing_score"`
	AllowedFileTypes   []string           `json:"allowed_file_types"`
	MaximumSubmissions int32              `json:"maximum_submissions"`
	IsRequired         bool               `json:"is_required"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.ID,
		arg.OrganizationID,
		arg.CourseID,
		arg.LessonID,
		arg.Title,
		arg.Instructions,
		arg.DueAt,
		arg.MaximumScore,
		arg.PassingScore,
		arg.AllowedFileTypes,
		arg.MaximumSubmissions,
		arg.IsRequired,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.DueAt,
		&i.MaximumScore,
		&i.PassingScore,
		&i.AllowedFileTypes,
		&i.MaximumSubmissions,
		&i.IsRequired,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssignmentSubmission = `-- name: CreateAssignmentSubmission :one
INSERT INTO assignment_submissions (id,assignment_id,enrollment_id,student_id,submission_number,text_content)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, assignment_id, enrollment_id, student_id, submission_number, status, text_content, submitted_at, created_at, updated_at
`

type CreateAssignmentSubmissionParams struct {
	ID               uuid.UUID `json:"id"`
	AssignmentID     uuid.UUID `json:"assignment_id"`
	EnrollmentID     uuid.UUID `json:"enrollment_id"`
	StudentID        uuid.UUID `json:"student_id"`
	SubmissionNumber int32     `json:"submission_number"`
	TextContent      string    `json:"text_content"`
}

func (q *Queries) CreateAssignmentSubmission(ctx context.Context, arg CreateAssignmentSubmissionParams) (AssignmentSubmission, error) {
	row := q.db.QueryRow(ctx, createAssignmentSubmission,
		arg.ID,
		arg.AssignmentID,
		arg.EnrollmentID,
		arg.StudentID,
		arg.SubmissionNumber,
		arg.TextContent,
	)
	var i AssignmentSubmission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.SubmissionNumber,
		&i.Status,
		&i.TextContent,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :execrows
DELETE FROM assignments WHERE id=$1 AND status='draft'
`

func (q *Queries) DeleteAssignment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssignment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAssignmentAssets = `-- name: DeleteAssignmentAssets :exec
DELETE FROM assignment_assets WHERE assignment_id=$1
`

func (q *Queries) DeleteAssignmentAssets(ctx context.Context, assignmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssignmentAssets, assignmentID)
	return err
}

const deleteSubmissionAssets = `-- name: DeleteSubmissionAssets :exec
DELETE FROM assignment_submission_assets WHERE submission_id=$1
`

func (q *Queries) DeleteSubmissionAssets(ctx context.Context, submissionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubmissionAssets, submissionID)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, organization_id, course_id, lesson_id, title, instructions, due_at, maximum_score, passing_score, allowed_file_types, maximum_submissions, is_required, status, created_at, updated_at FROM assignments WHERE id=$1
`

func (q *Queries) GetAssignment(ctx context.Context, id uuid.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.DueAt,
		&i.MaximumScore,
		&i.PassingScore,
		&i.AllowedFileTypes,
		&i.MaximumSubmissions,
		&i.IsRequired,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentSubmission = `-- name: GetAssignmentSubmission :one
SELECT id, assignment_id, enrollment_id, student_id, submission_number, status, text_content, submitted_at, created_at, updated_at FROM assignment_submissions WHERE id=$1
`

func (q *Queries) GetAssignmentSubmission(ctx context.Context, id uuid.UUID) (AssignmentSubmission, error) {
	row := q.db.QueryRow(ctx, getAssignmentSubmission, id)
	var i AssignmentSubmission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.SubmissionNumber,
		&i.Status,
		&i.TextContent,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentSubmissionForUpdate = `-- name: GetAssignmentSubmissionForUpdate :one
SELECT id, assignment_id, enrollment_id, student_id, submission_number, status, text_content, submitted_at, created_at, updated_at FROM assignment_submissions WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetAssignmentSubmissionForUpdate(ctx context.Context, id uuid.UUID) (AssignmentSubmission, error) {
	row := q.db.QueryRow(ctx, getAssignmentSubmissionForUpdate, id)
	var i AssignmentSubmission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.SubmissionNumber,
		&i.Status,
		&i.TextContent,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignmentAssetIDs = `-- name: ListAssignmentAssetIDs :many
SELECT media_asset_id FROM assignment_assets WHERE assignment_id=$1 ORDER BY media_asset_id
`

func (q *Queries) ListAssignmentAssetIDs(ctx context.Context, assignmentID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAssignmentAssetIDs, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var media_asset_id uuid.UUID
		if err := rows.Scan(&media_asset_id); err != nil {
			return nil, err
		}
		items = append(items, media_asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentSubmissions = `-- name: ListAssignmentSubmissions :many
SELECT id, assignment_id, enrollment_id, student_id, submission_number, status, text_content, submitted_at, created_at, updated_at FROM assignment_submissions
WHERE assignment_id=$1 AND ($2::uuid IS NULL OR student_id=$2)
 AND ($3::timestamptz IS NULL OR (created_at,id)<($3,$4::uuid))
ORDER BY created_at DESC,id DESC LIMIT $5
`

type ListAssignmentSubmissionsParams struct {
	AssignmentID    uuid.UUID          `json:"assignment_id"`
	StudentID       uuid.NullUUID      `json:"student_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListAssignmentSubmissions(ctx context.Context, arg ListAssignmentSubmissionsParams) ([]AssignmentSubmission, error) {
	rows, err := q.db.Query(ctx, listAssignmentSubmissions,
		arg.AssignmentID,
		arg.StudentID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentSubmission{}
	for rows.Next() {
		var i AssignmentSubmission
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.EnrollmentID,
			&i.StudentID,
			&i.SubmissionNumber,
			&i.Status,
			&i.TextContent,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseAssignments = `-- name: ListCourseAssignments :many
SELECT id, organization_id, course_id, lesson_id, title, instructions, due_at, maximum_score, passing_score, allowed_file_types, maximum_submissions, is_required, status, created_at, updated_at FROM assignments WHERE course_id=$1
 AND ($2::boolean OR status='published')
 AND ($3::timestamptz IS NULL OR (created_at,id)<($3,$4::uuid))
ORDER BY created_at DESC,id DESC LIMIT $5
`

type ListCourseAssignmentsParams struct {
	CourseID           uuid.UUID          `json:"course_id"`
	IncludeUnpublished bool               `json:"include_unpublished"`
	CursorCreatedAt    pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID           uuid.NullUUID      `json:"cursor_id"`
	PageSize           int32              `json:"page_size"`
}

func (q *Queries) ListCourseAssignments(ctx context.Context, arg ListCourseAssignmentsParams) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listCourseAssignments,
		arg.CourseID,
		arg.IncludeUnpublished,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CourseID,
			&i.LessonID,
			&i.Title,
			&i.Instructions,
			&i.DueAt,
			&i.MaximumScore,
			&i.PassingScore,
			&i.AllowedFileTypes,
			&i.MaximumSubmissions,
			&i.IsRequired,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionAssetIDs = `-- name: ListSubmissionAssetIDs :many
SELECT media_asset_id FROM assignment_submission_assets WHERE submission_id=$1 ORDER BY media_asset_id
`

func (q *Queries) ListSubmissionAssetIDs(ctx context.Context, submissionID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSubmissionAssetIDs, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var media_asset_id uuid.UUID
		if err := rows.Scan(&media_asset_id); err != nil {
			return nil, err
		}
		items = append(items, media_asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAssignmentSubmissionNumber = `-- name: NextAssignmentSubmissionNumber :one
SELECT COALESCE(max(submission_number),0)::integer+1 FROM assignment_submissions WHERE assignment_id=$1 AND student_id=$2
`

type NextAssignmentSubmissionNumberParams struct {
	AssignmentID uuid.UUID `json:"assignment_id"`
	StudentID    uuid.UUID `json:"student_id"`
}

func (q *Queries) NextAssignmentSubmissionNumber(ctx context.Context, arg NextAssignmentSubmissionNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextAssignmentSubmissionNumber, arg.AssignmentID, arg.StudentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setAssignmentStatus = `-- name: SetAssignmentStatus :one
UPDATE assignments SET status=$2,updated_at=now() WHERE id=$1 RETURNING id, organization_id, course_id, lesson_id, title, instructions, due_at, maximum_score, passing_score, allowed_file_types, maximum_submissions, is_required, status, created_at, updated_at
`

type SetAssignmentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetAssignmentStatus(ctx context.Context, arg SetAssignmentStatusParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, setAssignmentStatus, arg.ID, arg.Status)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.DueAt,
		&i.MaximumScore,
		&i.PassingScore,
		&i.AllowedFileTypes,
		&i.MaximumSubmissions,
		&i.IsRequired,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAssignmentSubmissionStatus = `-- name: SetAssignmentSubmissionStatus :one
UPDATE assignment_submissions SET status=$2,updated_at=now() WHERE id=$1 RETURNING id, assignment_id, enrollment_id, student_id, submission_number, status, text_content, submitted_at, created_at, updated_at
`

type SetAssignmentSubmissionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetAssignmentSubmissionStatus(ctx context.Context, arg SetAssignmentSubmissionStatusParams) (AssignmentSubmission, error) {
	row := q.db.QueryRow(ctx, setAssignmentSubmissionStatus, arg.ID, arg.Status)
	var i AssignmentSubmission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.SubmissionNumber,
		&i.Status,
		&i.TextContent,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitAssignmentSubmission = `-- name: SubmitAssignmentSubmission :one
UPDATE assignment_submissions SET status=$2,submitted_at=COALESCE(submitted_at,now()),updated_at=now() WHERE id=$1 AND status IN ('draft','returned') RETURNING id, assignment_id, enrollment_id, student_id, submission_number, status, text_content, submitted_at, created_at, updated_at
`

type SubmitAssignmentSubmissionParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SubmitAssignmentSubmission(ctx context.Context, arg SubmitAssignmentSubmissionParams) (AssignmentSubmission, error) {
	row := q.db.QueryRow(ctx, submitAssignmentSubmission, arg.ID, arg.Status)
	var i AssignmentSubmission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.SubmissionNumber,
		&i.Status,
		&i.TextContent,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments SET title=$1,instructions=$2,due_at=$3,maximum_score=$4,passing_score=$5,allowed_file_types=$6,maximum_submissions=$7,is_required=$8,updated_at=now() WHERE id=$9 RETURNING id, organization_id, course_id, lesson_id, title, instructions, due_at, maximum_score, passing_score, allowed_file_types, maximum_submissions, is_required, status, created_at, updated_at
`

type UpdateAssignmentParams struct {
	Title              string             `json:"title"`
	Instructions       string             `json:"instructions"`
	DueAt              pgtype.Timestamptz `json:"due_at"`
	MaximumScore       pgtype.Numeric     `json:"maximum_score"`
	PassingScore       pgtype.Numeric     `json:"passing_score"`
	AllowedFileTypes   []string           `json:"allowed_file_types"`
	MaximumSubmissions int32              `json:"maximum_submissions"`
	IsRequired         bool               `json:"is_required"`
	ID                 uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignment,
		arg.Title,
		arg.Instructions,
		arg.DueAt,
		arg.MaximumScore,
		arg.PassingScore,
		arg.AllowedFileTypes,
		arg.MaximumSubmissions,
		arg.IsRequired,
		arg.ID,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.DueAt,
		&i.MaximumScore,
		&i.PassingScore,
		&i.AllowedFileTypes,
		&i.MaximumSubmissions,
		&i.IsRequired,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignmentSubmissionDraft = `-- name: UpdateAssignmentSubmissionDraft :one
UPDATE assignment_submissions SET text_content=$2,updated_at=now() WHERE id=$1 AND status IN ('draft','returned') RETURNING id, assignment_id, enrollment_id, student_id, submission_number, status, text_content, submitted_at, created_at, updated_at
`

type UpdateAssignmentSubmissionDraftParams struct {
	ID          uuid.UUID `json:"id"`
	TextContent string    `json:"text_content"`
}

func (q *Queries) UpdateAssignmentSubmissionDraft(ctx context.Context, arg UpdateAssignmentSubmissionDraftParams) (AssignmentSubmission, error) {
	row := q.db.QueryRow(ctx, updateAssignmentSubmissionDraft, arg.ID, arg.TextContent)
	var i AssignmentSubmission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.SubmissionNumber,
		&i.Status,
		&i.TextContent,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAssignmentGrade = `-- name: UpsertAssignmentGrade :one
INSERT INTO grades (id,assignment_submission_id,student_id,graded_by,points,percentage,feedback)
VALUES ($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(assignment_submission_id) DO UPDATE SET graded_by=EXCLUDED.graded_by,points=EXCLUDED.points,percentage=EXCLUDED.percentage,feedback=EXCLUDED.feedback,updated_at=now() RETURNING id, assignment_submission_id, quiz_attempt_id, student_id, graded_by, points, percentage, feedback, created_at, updated_at
`

type UpsertAssignmentGradeParams struct {
	ID                     uuid.UUID      `json:"id"`
	AssignmentSubmissionID uuid.NullUUID  `json:"assignment_submission_id"`
	StudentID              uuid.UUID      `json:"student_id"`
	GradedBy               uuid.UUID      `json:"graded_by"`
	Points                 pgtype.Numeric `json:"points"`
	Percentage             pgtype.Numeric `json:"percentage"`
	Feedback               string         `json:"feedback"`
}

func (q *Queries) UpsertAssignmentGrade(ctx context.Context, arg UpsertAssignmentGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, upsertAssignmentGrade,
		arg.ID,
		arg.AssignmentSubmissionID,
		arg.StudentID,
		arg.GradedBy,
		arg.Points,
		arg.Percentage,
		arg.Feedback,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.AssignmentSubmissionID,
		&i.QuizAttemptID,
		&i.StudentID,
		&i.GradedBy,
		&i.Points,
		&i.Percentage,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
