// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package data

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveMembership = `-- name: GetActiveMembership :one
SELECT m.id, m.organization_id, m.user_id, m.status,
       COALESCE(array_agg(r.code ORDER BY r.code) FILTER (WHERE r.code IS NOT NULL), '{}')::text[] AS roles
FROM organization_memberships m
LEFT JOIN membership_roles mr ON mr.membership_id = m.id
LEFT JOIN roles r ON r.id = mr.role_id
WHERE m.user_id = $1 AND m.organization_id = $2
GROUP BY m.id
HAVING m.status = 'active'
`

type GetActiveMembershipParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type GetActiveMembershipRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Status         string    `json:"status"`
	Roles          []string  `json:"roles"`
}

func (q *Queries) GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (GetActiveMembershipRow, error) {
	row := q.db.QueryRow(ctx, getActiveMembership, arg.UserID, arg.OrganizationID)
	var i GetActiveMembershipRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.Roles,
	)
	return i, err
}

const getSuperAdminRoleForUser = `-- name: GetSuperAdminRoleForUser :one
SELECT EXISTS (
  SELECT 1 FROM organization_memberships m
  JOIN membership_roles mr ON mr.membership_id = m.id
  JOIN roles r ON r.id = mr.role_id
  WHERE m.user_id = $1 AND m.status = 'active' AND r.code = 'super_admin'
) AS is_super_admin
`

func (q *Queries) GetSuperAdminRoleForUser(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getSuperAdminRoleForUser, userID)
	var is_super_admin bool
	err := row.Scan(&is_super_admin)
	return is_super_admin, err
}

const getUser = `-- name: GetUser :one
SELECT id, firebase_uid, email, display_name, avatar_url, status, created_at, updated_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, firebase_uid, email, display_name, avatar_url, status, created_at, updated_at, last_login_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, display_name, avatar_url, status, created_at, updated_at, last_login_at FROM users WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const hasOrganizationRole = `-- name: HasOrganizationRole :one
SELECT EXISTS (
  SELECT 1 FROM organization_memberships m
  JOIN membership_roles mr ON mr.membership_id=m.id
  JOIN roles r ON r.id=mr.role_id
  WHERE m.organization_id=$1 AND m.user_id=$2
    AND m.status='active' AND r.code=$3
) AS allowed
`

type HasOrganizationRoleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	RoleCode       string    `json:"role_code"`
}

func (q *Queries) HasOrganizationRole(ctx context.Context, arg HasOrganizationRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOrganizationRole, arg.OrganizationID, arg.UserID, arg.RoleCode)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (id, organization_id, actor_user_id, action, resource_type, resource_id, request_id, before_data, after_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditLogParams struct {
	ID             uuid.UUID     `json:"id"`
	OrganizationID uuid.NullUUID `json:"organization_id"`
	ActorUserID    uuid.NullUUID `json:"actor_user_id"`
	Action         string        `json:"action"`
	ResourceType   string        `json:"resource_type"`
	ResourceID     uuid.NullUUID `json:"resource_id"`
	RequestID      pgtype.Text   `json:"request_id"`
	BeforeData     []byte        `json:"before_data"`
	AfterData      []byte        `json:"after_data"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.RequestID,
		arg.BeforeData,
		arg.AfterData,
	)
	return err
}

const listOrganizationAuditLogs = `-- name: ListOrganizationAuditLogs :many
SELECT a.id, a.organization_id, a.actor_user_id, a.action, a.resource_type, a.resource_id, a.request_id, a.ip_address, a.before_data, a.after_data, a.created_at,u.email AS actor_email
FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id
WHERE a.organization_id=$1
 AND ($2::timestamptz IS NULL OR (a.created_at,a.id)<($2,$3::uuid))
ORDER BY a.created_at DESC,a.id DESC LIMIT $4
`

type ListOrganizationAuditLogsParams struct {
	OrganizationID  uuid.NullUUID      `json:"organization_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListOrganizationAuditLogsRow struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.NullUUID      `json:"organization_id"`
	ActorUserID    uuid.NullUUID      `json:"actor_user_id"`
	Action         string             `json:"action"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     uuid.NullUUID      `json:"resource_id"`
	RequestID      pgtype.Text        `json:"request_id"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	BeforeData     []byte             `json:"before_data"`
	AfterData      []byte             `json:"after_data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActorEmail     pgtype.Text        `json:"actor_email"`
}

func (q *Queries) ListOrganizationAuditLogs(ctx context.Context, arg ListOrganizationAuditLogsParams) ([]ListOrganizationAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationAuditLogs,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationAuditLogsRow{}
	for rows.Next() {
		var i ListOrganizationAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.RequestID,
			&i.IpAddress,
			&i.BeforeData,
			&i.AfterData,
			&i.CreatedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT m.id, m.organization_id, o.name AS organization_name, o.slug AS organization_slug,
       m.status, COALESCE(array_agg(r.code ORDER BY r.code) FILTER (WHERE r.code IS NOT NULL), '{}')::text[] AS roles
FROM organization_memberships m
JOIN organizations o ON o.id = m.organization_id
LEFT JOIN membership_roles mr ON mr.membership_id = m.id
LEFT JOIN roles r ON r.id = mr.role_id
WHERE m.user_id = $1 AND m.status = 'active' AND o.status = 'active'
GROUP BY m.id, o.id
ORDER BY o.name, m.id
`

type ListUserMembershipsRow struct {
	ID               uuid.UUID `json:"id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
	OrganizationName string    `json:"organization_name"`
	OrganizationSlug string    `json:"organization_slug"`
	Status           string    `json:"status"`
	Roles            []string  `json:"roles"`
}

func (q *Queries) ListUserMemberships(ctx context.Context, userID uuid.UUID) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMembershipsRow{}
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.Status,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserByFirebaseUID = `-- name: UpsertUserByFirebaseUID :one
INSERT INTO users (id, firebase_uid, email, display_name, status, last_login_at)
VALUES ($1, $2, lower($3), $4, 'active', now())
ON CONFLICT (firebase_uid) DO UPDATE
SET email = lower(EXCLUDED.email),
    display_name = CASE WHEN EXCLUDED.display_name = '' THEN users.display_name ELSE EXCLUDED.display_name END,
    last_login_at = now(),
    updated_at = now()
RETURNING id, firebase_uid, email, display_name, avatar_url, status, created_at, updated_at, last_login_at
`

type UpsertUserByFirebaseUIDParams struct {
	ID          uuid.UUID `json:"id"`
	FirebaseUid string    `json:"firebase_uid"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) UpsertUserByFirebaseUID(ctx context.Context, arg UpsertUserByFirebaseUIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByFirebaseUID,
		arg.ID,
		arg.FirebaseUid,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
