// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificate.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completionRequirements = `-- name: CompletionRequirements :one
SELECT
 (SELECT count(*) FROM lessons l JOIN course_modules m ON m.id=l.module_id WHERE m.course_id=$1 AND l.is_published AND l.is_required) AS required_lessons,
 (SELECT count(*) FROM lessons l JOIN course_modules m ON m.id=l.module_id JOIN lesson_progress p ON p.lesson_id=l.id WHERE m.course_id=$1 AND l.is_published AND l.is_required AND p.enrollment_id=$2 AND p.state='completed') AS completed_lessons,
 (SELECT count(*) FROM quizzes q WHERE q.course_id=$1 AND q.status='published' AND q.is_required) AS required_quizzes,
 (SELECT count(DISTINCT q.id) FROM quizzes q JOIN quiz_attempts a ON a.quiz_id=q.id WHERE q.course_id=$1 AND q.status='published' AND q.is_required AND a.enrollment_id=$2 AND a.status='graded' AND a.passed) AS passed_quizzes,
 (SELECT count(*) FROM assignments a WHERE a.course_id=$1 AND a.status='published' AND a.is_required) AS required_assignments,
 (SELECT count(DISTINCT a.id) FROM assignments a JOIN assignment_submissions s ON s.assignment_id=a.id JOIN grades g ON g.assignment_submission_id=s.id WHERE a.course_id=$1 AND a.status='published' AND a.is_required AND s.enrollment_id=$2 AND s.status='graded' AND g.points>=a.passing_score) AS passed_assignments
`

type CompletionRequirementsParams struct {
	CourseID     uuid.UUID `json:"course_id"`
	EnrollmentID uuid.UUID `json:"enrollment_id"`
}

type CompletionRequirementsRow struct {
	RequiredLessons     int64 `json:"required_lessons"`
	CompletedLessons    int64 `json:"completed_lessons"`
	RequiredQuizzes     int64 `json:"required_quizzes"`
	PassedQuizzes       int64 `json:"passed_quizzes"`
	RequiredAssignments int64 `json:"required_assignments"`
	PassedAssignments   int64 `json:"passed_assignments"`
}

func (q *Queries) CompletionRequirements(ctx context.Context, arg CompletionRequirementsParams) (CompletionRequirementsRow, error) {
	row := q.db.QueryRow(ctx, completionRequirements, arg.CourseID, arg.EnrollmentID)
	var i CompletionRequirementsRow
	err := row.Scan(
		&i.RequiredLessons,
		&i.CompletedLessons,
		&i.RequiredQuizzes,
		&i.PassedQuizzes,
		&i.RequiredAssignments,
		&i.PassedAssignments,
	)
	return i, err
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (id,organization_id,enrollment_id,student_id,course_id,certificate_number,verification_code,status,issued_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,'pending',$8)
ON CONFLICT(enrollment_id) DO UPDATE SET updated_at=now() RETURNING id, organization_id, enrollment_id, student_id, course_id, template_id, certificate_number, verification_code, media_asset_id, status, issued_at, created_at, updated_at
`

type CreateCertificateParams struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	EnrollmentID      uuid.UUID          `json:"enrollment_id"`
	StudentID         uuid.UUID          `json:"student_id"`
	CourseID          uuid.UUID          `json:"course_id"`
	CertificateNumber string             `json:"certificate_number"`
	VerificationCode  string             `json:"verification_code"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		arg.ID,
		arg.OrganizationID,
		arg.EnrollmentID,
		arg.StudentID,
		arg.CourseID,
		arg.CertificateNumber,
		arg.VerificationCode,
		arg.IssuedAt,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.CourseID,
		&i.TemplateID,
		&i.CertificateNumber,
		&i.VerificationCode,
		&i.MediaAssetID,
		&i.Status,
		&i.IssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCompletionSnapshot = `-- name: CreateCompletionSnapshot :one
INSERT INTO course_completion_snapshots (id,enrollment_id,required_lessons,completed_lessons,required_quizzes,passed_quizzes,required_assignments,passed_assignments,percentage,is_complete)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, enrollment_id, required_lessons, completed_lessons, required_quizzes, passed_quizzes, required_assignments, passed_assignments, percentage, is_complete, created_at
`

type CreateCompletionSnapshotParams struct {
	ID                  uuid.UUID      `json:"id"`
	EnrollmentID        uuid.UUID      `json:"enrollment_id"`
	RequiredLessons     int32          `json:"required_lessons"`
	CompletedLessons    int32          `json:"completed_lessons"`
	RequiredQuizzes     int32          `json:"required_quizzes"`
	PassedQuizzes       int32          `json:"passed_quizzes"`
	RequiredAssignments int32          `json:"required_assignments"`
	PassedAssignments   int32          `json:"passed_assignments"`
	Percentage          pgtype.Numeric `json:"percentage"`
	IsComplete          bool           `json:"is_complete"`
}

func (q *Queries) CreateCompletionSnapshot(ctx context.Context, arg CreateCompletionSnapshotParams) (CourseCompletionSnapshot, error) {
	row := q.db.QueryRow(ctx, createCompletionSnapshot,
		arg.ID,
		arg.EnrollmentID,
		arg.RequiredLessons,
		arg.CompletedLessons,
		arg.RequiredQuizzes,
		arg.PassedQuizzes,
		arg.RequiredAssignments,
		arg.PassedAssignments,
		arg.Percentage,
		arg.IsComplete,
	)
	var i CourseCompletionSnapshot
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.RequiredLessons,
		&i.CompletedLessons,
		&i.RequiredQuizzes,
		&i.PassedQuizzes,
		&i.RequiredAssignments,
		&i.PassedAssignments,
		&i.Percentage,
		&i.IsComplete,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, organization_id, enrollment_id, student_id, course_id, template_id, certificate_number, verification_code, media_asset_id, status, issued_at, created_at, updated_at FROM certificates WHERE id=$1
`

func (q *Queries) GetCertificate(ctx context.Context, id uuid.UUID) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificate, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.CourseID,
		&i.TemplateID,
		&i.CertificateNumber,
		&i.VerificationCode,
		&i.MediaAssetID,
		&i.Status,
		&i.IssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificateForUpdate = `-- name: GetCertificateForUpdate :one
SELECT id, organization_id, enrollment_id, student_id, course_id, template_id, certificate_number, verification_code, media_asset_id, status, issued_at, created_at, updated_at FROM certificates WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetCertificateForUpdate(ctx context.Context, id uuid.UUID) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateForUpdate, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.CourseID,
		&i.TemplateID,
		&i.CertificateNumber,
		&i.VerificationCode,
		&i.MediaAssetID,
		&i.Status,
		&i.IssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserCertificates = `-- name: ListUserCertificates :many
SELECT id, organization_id, enrollment_id, student_id, course_id, template_id, certificate_number, verification_code, media_asset_id, status, issued_at, created_at, updated_at FROM certificates WHERE student_id=$1
 AND ($2::timestamptz IS NULL OR (issued_at,id)<($2,$3::uuid))
ORDER BY issued_at DESC,id DESC LIMIT $4
`

type ListUserCertificatesParams struct {
	StudentID      uuid.UUID          `json:"student_id"`
	CursorIssuedAt pgtype.Timestamptz `json:"cursor_issued_at"`
	CursorID       uuid.NullUUID      `json:"cursor_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListUserCertificates(ctx context.Context, arg ListUserCertificatesParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, listUserCertificates,
		arg.StudentID,
		arg.CursorIssuedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EnrollmentID,
			&i.StudentID,
			&i.CourseID,
			&i.TemplateID,
			&i.CertificateNumber,
			&i.VerificationCode,
			&i.MediaAssetID,
			&i.Status,
			&i.IssuedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCertificateReady = `-- name: SetCertificateReady :one
UPDATE certificates SET status='ready',media_asset_id=$2,updated_at=now() WHERE id=$1 AND status='pending' RETURNING id, organization_id, enrollment_id, student_id, course_id, template_id, certificate_number, verification_code, media_asset_id, status, issued_at, created_at, updated_at
`

type SetCertificateReadyParams struct {
	ID           uuid.UUID     `json:"id"`
	MediaAssetID uuid.NullUUID `json:"media_asset_id"`
}

func (q *Queries) SetCertificateReady(ctx context.Context, arg SetCertificateReadyParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, setCertificateReady, arg.ID, arg.MediaAssetID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.CourseID,
		&i.TemplateID,
		&i.CertificateNumber,
		&i.VerificationCode,
		&i.MediaAssetID,
		&i.Status,
		&i.IssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyCertificate = `-- name: VerifyCertificate :one
SELECT c.certificate_number,c.status,c.issued_at,u.display_name AS student_name,co.title AS course_title,o.name AS organization_name
FROM certificates c JOIN users u ON u.id=c.student_id JOIN courses co ON co.id=c.course_id JOIN organizations o ON o.id=c.organization_id
WHERE c.verification_code=$1
`

type VerifyCertificateRow struct {
	CertificateNumber string             `json:"certificate_number"`
	Status            string             `json:"status"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
	StudentName       string             `json:"student_name"`
	CourseTitle       string             `json:"course_title"`
	OrganizationName  string             `json:"organization_name"`
}

func (q *Queries) VerifyCertificate(ctx context.Context, verificationCode string) (VerifyCertificateRow, error) {
	row := q.db.QueryRow(ctx, verifyCertificate, verificationCode)
	var i VerifyCertificateRow
	err := row.Scan(
		&i.CertificateNumber,
		&i.Status,
		&i.IssuedAt,
		&i.StudentName,
		&i.CourseTitle,
		&i.OrganizationName,
	)
	return i, err
}
