// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignCourseInstructor = `-- name: AssignCourseInstructor :exec
INSERT INTO course_instructors (course_id,instructor_id,assigned_by) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type AssignCourseInstructorParams struct {
	CourseID     uuid.UUID `json:"course_id"`
	InstructorID uuid.UUID `json:"instructor_id"`
	AssignedBy   uuid.UUID `json:"assigned_by"`
}

func (q *Queries) AssignCourseInstructor(ctx context.Context, arg AssignCourseInstructorParams) error {
	_, err := q.db.Exec(ctx, assignCourseInstructor, arg.CourseID, arg.InstructorID, arg.AssignedBy)
	return err
}

const countCourseInstructors = `-- name: CountCourseInstructors :one
SELECT count(*) FROM course_instructors WHERE course_id=$1
`

func (q *Queries) CountCourseInstructors(ctx context.Context, courseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCourseInstructors, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const coursePublishFacts = `-- name: CoursePublishFacts :one
SELECT c.id,c.title,c.description,c.is_free,c.price_minor,c.thumbnail_asset_id,
 (SELECT count(*) FROM course_instructors ci WHERE ci.course_id=c.id) AS instructor_count,
 (SELECT count(*) FROM course_modules m WHERE m.course_id=c.id) AS module_count,
 (SELECT count(*) FROM lessons l JOIN course_modules m ON m.id=l.module_id WHERE m.course_id=c.id AND l.is_published) AS published_lesson_count,
 ((SELECT count(*) FROM lessons l JOIN course_modules m ON m.id=l.module_id LEFT JOIN media_assets a ON a.id=l.media_asset_id WHERE m.course_id=c.id AND l.media_asset_id IS NOT NULL AND a.status <> 'ready')
  + (SELECT count(*) FROM media_assets a WHERE a.id=c.thumbnail_asset_id AND a.status <> 'ready')) AS unready_media_count
FROM courses c WHERE c.id=$1
`

type CoursePublishFactsRow struct {
	ID                   uuid.UUID     `json:"id"`
	Title                string        `json:"title"`
	Description          string        `json:"description"`
	IsFree               bool          `json:"is_free"`
	PriceMinor           int64         `json:"price_minor"`
	ThumbnailAssetID     uuid.NullUUID `json:"thumbnail_asset_id"`
	InstructorCount      int64         `json:"instructor_count"`
	ModuleCount          int64         `json:"module_count"`
	PublishedLessonCount int64         `json:"published_lesson_count"`
	UnreadyMediaCount    int32         `json:"unready_media_count"`
}

func (q *Queries) CoursePublishFacts(ctx context.Context, id uuid.UUID) (CoursePublishFactsRow, error) {
	row := q.db.QueryRow(ctx, coursePublishFacts, id)
	var i CoursePublishFactsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsFree,
		&i.PriceMinor,
		&i.ThumbnailAssetID,
		&i.InstructorCount,
		&i.ModuleCount,
		&i.PublishedLessonCount,
		&i.UnreadyMediaCount,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO course_categories (id, organization_id, name, slug, description) VALUES ($1,$2,$3,$4,$5) RETURNING id, organization_id, name, slug, description, created_at, updated_at
`

type CreateCategoryParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    string    `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CourseCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i CourseCategory
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (id, organization_id, category_id, thumbnail_asset_id, title, slug, description, language, level, is_free, price_minor, currency, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id, organization_id, category_id, thumbnail_asset_id, title, slug, description, language, level, status, is_free, price_minor, currency, completion_video_threshold, version, published_at, created_by, created_at, updated_at, search_vector, passing_percentage
`

type CreateCourseParams struct {
	ID               uuid.UUID     `json:"id"`
	OrganizationID   uuid.UUID     `json:"organization_id"`
	CategoryID       uuid.NullUUID `json:"category_id"`
	ThumbnailAssetID uuid.NullUUID `json:"thumbnail_asset_id"`
	Title            string        `json:"title"`
	Slug             string        `json:"slug"`
	Description      string        `json:"description"`
	Language         string        `json:"language"`
	Level            string        `json:"level"`
	IsFree           bool          `json:"is_free"`
	PriceMinor       int64         `json:"price_minor"`
	Currency         string        `json:"currency"`
	CreatedBy        uuid.UUID     `json:"created_by"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.ID,
		arg.OrganizationID,
		arg.CategoryID,
		arg.ThumbnailAssetID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Language,
		arg.Level,
		arg.IsFree,
		arg.PriceMinor,
		arg.Currency,
		arg.CreatedBy,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.ThumbnailAssetID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Language,
		&i.Level,
		&i.Status,
		&i.IsFree,
		&i.PriceMinor,
		&i.Currency,
		&i.CompletionVideoThreshold,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.PassingPercentage,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (id,module_id,title,description,lesson_type,media_asset_id,body,position,is_preview,is_required,is_published,duration_seconds)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id, module_id, title, description, lesson_type, media_asset_id, body, position, is_preview, is_required, is_published, duration_seconds, metadata, created_at, updated_at
`

type CreateLessonParams struct {
	ID              uuid.UUID     `json:"id"`
	ModuleID        uuid.UUID     `json:"module_id"`
	Title           string        `json:"title"`
	Description     string        `json:"description"`
	LessonType      string        `json:"lesson_type"`
	MediaAssetID    uuid.NullUUID `json:"media_asset_id"`
	Body            string        `json:"body"`
	Position        int32         `json:"position"`
	IsPreview       bool          `json:"is_preview"`
	IsRequired      bool          `json:"is_required"`
	IsPublished     bool          `json:"is_published"`
	DurationSeconds pgtype.Int4   `json:"duration_seconds"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.ID,
		arg.ModuleID,
		arg.Title,
		arg.Description,
		arg.LessonType,
		arg.MediaAssetID,
		arg.Body,
		arg.Position,
		arg.IsPreview,
		arg.IsRequired,
		arg.IsPublished,
		arg.DurationSeconds,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.LessonType,
		&i.MediaAssetID,
		&i.Body,
		&i.Position,
		&i.IsPreview,
		&i.IsRequired,
		&i.IsPublished,
		&i.DurationSeconds,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createModule = `-- name: CreateModule :one
INSERT INTO course_modules (id,course_id,title,description,position) VALUES ($1,$2,$3,$4,$5) RETURNING id, course_id, title, description, position, created_at, updated_at
`

type CreateModuleParams struct {
	ID          uuid.UUID `json:"id"`
	CourseID    uuid.UUID `json:"course_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Position    int32     `json:"position"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (CourseModule, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.ID,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i CourseModule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM course_categories WHERE id=$1 AND organization_id=$2
`

type DeleteCategoryParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLesson = `-- name: DeleteLesson :execrows
DELETE FROM lessons WHERE id=$1
`

func (q *Queries) DeleteLesson(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLesson, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteModule = `-- name: DeleteModule :execrows
DELETE FROM course_modules WHERE id=$1
`

func (q *Queries) DeleteModule(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCourse = `-- name: GetCourse :one
SELECT id, organization_id, category_id, thumbnail_asset_id, title, slug, description, language, level, status, is_free, price_minor, currency, completion_video_threshold, version, published_at, created_by, created_at, updated_at, search_vector, passing_percentage FROM courses WHERE id=$1
`

func (q *Queries) GetCourse(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.ThumbnailAssetID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Language,
		&i.Level,
		&i.Status,
		&i.IsFree,
		&i.PriceMinor,
		&i.Currency,
		&i.CompletionVideoThreshold,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.PassingPercentage,
	)
	return i, err
}

const getCourseByLesson = `-- name: GetCourseByLesson :one
SELECT c.id, c.organization_id, c.category_id, c.thumbnail_asset_id, c.title, c.slug, c.description, c.language, c.level, c.status, c.is_free, c.price_minor, c.currency, c.completion_video_threshold, c.version, c.published_at, c.created_by, c.created_at, c.updated_at, c.search_vector, c.passing_percentage FROM courses c JOIN course_modules m ON m.course_id=c.id JOIN lessons l ON l.module_id=m.id WHERE l.id=$1
`

func (q *Queries) GetCourseByLesson(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByLesson, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.ThumbnailAssetID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Language,
		&i.Level,
		&i.Status,
		&i.IsFree,
		&i.PriceMinor,
		&i.Currency,
		&i.CompletionVideoThreshold,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.PassingPercentage,
	)
	return i, err
}

const getCourseByModule = `-- name: GetCourseByModule :one
SELECT c.id, c.organization_id, c.category_id, c.thumbnail_asset_id, c.title, c.slug, c.description, c.language, c.level, c.status, c.is_free, c.price_minor, c.currency, c.completion_video_threshold, c.version, c.published_at, c.created_by, c.created_at, c.updated_at, c.search_vector, c.passing_percentage FROM courses c JOIN course_modules m ON m.course_id=c.id WHERE m.id=$1
`

func (q *Queries) GetCourseByModule(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByModule, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.ThumbnailAssetID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Language,
		&i.Level,
		&i.Status,
		&i.IsFree,
		&i.PriceMinor,
		&i.Currency,
		&i.CompletionVideoThreshold,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.PassingPercentage,
	)
	return i, err
}

const getCourseForUpdate = `-- name: GetCourseForUpdate :one
SELECT id, organization_id, category_id, thumbnail_asset_id, title, slug, description, language, level, status, is_free, price_minor, currency, completion_video_threshold, version, published_at, created_by, created_at, updated_at, search_vector, passing_percentage FROM courses WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetCourseForUpdate(ctx context.Context, id uuid.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseForUpdate, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.ThumbnailAssetID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Language,
		&i.Level,
		&i.Status,
		&i.IsFree,
		&i.PriceMinor,
		&i.Currency,
		&i.CompletionVideoThreshold,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.PassingPercentage,
	)
	return i, err
}

const getLesson = `-- name: GetLesson :one
SELECT id, module_id, title, description, lesson_type, media_asset_id, body, position, is_preview, is_required, is_published, duration_seconds, metadata, created_at, updated_at FROM lessons WHERE id=$1
`

func (q *Queries) GetLesson(ctx context.Context, id uuid.UUID) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLesson, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.LessonType,
		&i.MediaAssetID,
		&i.Body,
		&i.Position,
		&i.IsPreview,
		&i.IsRequired,
		&i.IsPublished,
		&i.DurationSeconds,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedCourseBySlug = `-- name: GetPublishedCourseBySlug :one
SELECT id, organization_id, category_id, thumbnail_asset_id, title, slug, description, language, level, status, is_free, price_minor, currency, completion_video_threshold, version, published_at, created_by, created_at, updated_at, search_vector, passing_percentage FROM courses WHERE slug = $1 AND status = 'published'
`

func (q *Queries) GetPublishedCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getPublishedCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.ThumbnailAssetID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Language,
		&i.Level,
		&i.Status,
		&i.IsFree,
		&i.PriceMinor,
		&i.Currency,
		&i.CompletionVideoThreshold,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.PassingPercentage,
	)
	return i, err
}

const isCourseInstructor = `-- name: IsCourseInstructor :one
SELECT EXISTS(SELECT 1 FROM course_instructors WHERE course_id=$1 AND instructor_id=$2) AS assigned
`

type IsCourseInstructorParams struct {
	CourseID     uuid.UUID `json:"course_id"`
	InstructorID uuid.UUID `json:"instructor_id"`
}

func (q *Queries) IsCourseInstructor(ctx context.Context, arg IsCourseInstructorParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCourseInstructor, arg.CourseID, arg.InstructorID)
	var assigned bool
	err := row.Scan(&assigned)
	return assigned, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, organization_id, name, slug, description, created_at, updated_at FROM course_categories WHERE organization_id=$1
 AND ($2::timestamptz IS NULL OR (created_at,id)<($2,$3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $4
`

type ListCategoriesParams struct {
	OrganizationID  uuid.UUID          `json:"organization_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]CourseCategory, error) {
	rows, err := q.db.Query(ctx, listCategories,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseCategory{}
	for rows.Next() {
		var i CourseCategory
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseContent = `-- name: ListCourseContent :many
SELECT m.id AS module_id,m.title AS module_title,m.description AS module_description,m.position AS module_position,
 l.id AS lesson_id,l.title AS lesson_title,l.description AS lesson_description,l.lesson_type,l.media_asset_id,l.body,l.position AS lesson_position,l.is_preview,l.is_required,l.is_published,l.duration_seconds
FROM course_modules m LEFT JOIN lessons l ON l.module_id=m.id
WHERE m.course_id=$1 ORDER BY m.position,m.id,l.position,l.id
`

type ListCourseContentRow struct {
	ModuleID          uuid.UUID     `json:"module_id"`
	ModuleTitle       string        `json:"module_title"`
	ModuleDescription string        `json:"module_description"`
	ModulePosition    int32         `json:"module_position"`
	LessonID          uuid.NullUUID `json:"lesson_id"`
	LessonTitle       pgtype.Text   `json:"lesson_title"`
	LessonDescription pgtype.Text   `json:"lesson_description"`
	LessonType        pgtype.Text   `json:"lesson_type"`
	MediaAssetID      uuid.NullUUID `json:"media_asset_id"`
	Body              pgtype.Text   `json:"body"`
	LessonPosition    pgtype.Int4   `json:"lesson_position"`
	IsPreview         pgtype.Bool   `json:"is_preview"`
	IsRequired        pgtype.Bool   `json:"is_required"`
	IsPublished       pgtype.Bool   `json:"is_published"`
	DurationSeconds   pgtype.Int4   `json:"duration_seconds"`
}

func (q *Queries) ListCourseContent(ctx context.Context, courseID uuid.UUID) ([]ListCourseContentRow, error) {
	rows, err := q.db.Query(ctx, listCourseContent, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseContentRow{}
	for rows.Next() {
		var i ListCourseContentRow
		if err := rows.Scan(
			&i.ModuleID,
			&i.ModuleTitle,
			&i.ModuleDescription,
			&i.ModulePosition,
			&i.LessonID,
			&i.LessonTitle,
			&i.LessonDescription,
			&i.LessonType,
			&i.MediaAssetID,
			&i.Body,
			&i.LessonPosition,
			&i.IsPreview,
			&i.IsRequired,
			&i.IsPublished,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedCourses = `-- name: ListManagedCourses :many
SELECT DISTINCT c.id, c.organization_id, c.category_id, c.thumbnail_asset_id, c.title, c.slug, c.description, c.language, c.level, c.status, c.is_free, c.price_minor, c.currency, c.completion_video_threshold, c.version, c.published_at, c.created_by, c.created_at, c.updated_at, c.search_vector, c.passing_percentage FROM courses c
LEFT JOIN course_instructors ci ON ci.course_id=c.id
WHERE c.organization_id=$1
  AND ($2::uuid IS NULL OR ci.instructor_id=$2)
  AND ($3::timestamptz IS NULL OR (c.created_at,c.id)<($3,$4::uuid))
ORDER BY c.created_at DESC,c.id DESC LIMIT $5
`

type ListManagedCoursesParams struct {
	OrganizationID  uuid.UUID          `json:"organization_id"`
	InstructorID    uuid.NullUUID      `json:"instructor_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListManagedCourses(ctx context.Context, arg ListManagedCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listManagedCourses,
		arg.OrganizationID,
		arg.InstructorID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CategoryID,
			&i.ThumbnailAssetID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Language,
			&i.Level,
			&i.Status,
			&i.IsFree,
			&i.PriceMinor,
			&i.Currency,
			&i.CompletionVideoThreshold,
			&i.Version,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.PassingPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCourses = `-- name: ListPublishedCourses :many
SELECT c.id, c.organization_id, c.category_id, c.thumbnail_asset_id, c.title, c.slug, c.description, c.language, c.level, c.status, c.is_free, c.price_minor, c.currency, c.completion_video_threshold, c.version, c.published_at, c.created_by, c.created_at, c.updated_at, c.search_vector, c.passing_percentage, cc.name AS category_name
FROM courses c LEFT JOIN course_categories cc ON cc.id=c.category_id
WHERE c.status='published'
  AND ($1::uuid IS NULL OR c.organization_id=$1)
  AND ($2::text = '' OR c.search_vector @@ websearch_to_tsquery('simple', $2) OR c.title % $2)
  AND ($3::uuid IS NULL OR c.category_id=$3)
  AND ($4::text IS NULL OR c.level=$4)
  AND ($5::timestamptz IS NULL OR (c.published_at, c.id) < ($5, $6::uuid))
ORDER BY c.published_at DESC, c.id DESC LIMIT $7
`

type ListPublishedCoursesParams struct {
	OrganizationID    uuid.NullUUID      `json:"organization_id"`
	Search            string             `json:"search"`
	CategoryID        uuid.NullUUID      `json:"category_id"`
	Level             pgtype.Text        `json:"level"`
	CursorPublishedAt pgtype.Timestamptz `json:"cursor_published_at"`
	CursorID          uuid.NullUUID      `json:"cursor_id"`
	PageSize          int32              `json:"page_size"`
}

type ListPublishedCoursesRow struct {
	ID                       uuid.UUID          `json:"id"`
	OrganizationID           uuid.UUID          `json:"organization_id"`
	CategoryID               uuid.NullUUID      `json:"category_id"`
	ThumbnailAssetID         uuid.NullUUID      `json:"thumbnail_asset_id"`
	Title                    string             `json:"title"`
	Slug                     string             `json:"slug"`
	Description              string             `json:"description"`
	Language                 string             `json:"language"`
	Level                    string             `json:"level"`
	Status                   string             `json:"status"`
	IsFree                   bool               `json:"is_free"`
	PriceMinor               int64              `json:"price_minor"`
	Currency                 string             `json:"currency"`
	CompletionVideoThreshold pgtype.Numeric     `json:"completion_video_threshold"`
	Version                  int64              `json:"version"`
	PublishedAt              pgtype.Timestamptz `json:"published_at"`
	CreatedBy                uuid.UUID          `json:"created_by"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	SearchVector             interface{}        `json:"search_vector"`
	PassingPercentage        pgtype.Numeric     `json:"passing_percentage"`
	CategoryName             pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListPublishedCourses(ctx context.Context, arg ListPublishedCoursesParams) ([]ListPublishedCoursesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedCourses,
		arg.OrganizationID,
		arg.Search,
		arg.CategoryID,
		arg.Level,
		arg.CursorPublishedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedCoursesRow{}
	for rows.Next() {
		var i ListPublishedCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CategoryID,
			&i.ThumbnailAssetID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Language,
			&i.Level,
			&i.Status,
			&i.IsFree,
			&i.PriceMinor,
			&i.Currency,
			&i.CompletionVideoThreshold,
			&i.Version,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.PassingPercentage,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCourseInstructor = `-- name: RemoveCourseInstructor :execrows
DELETE FROM course_instructors WHERE course_id=$1 AND instructor_id=$2
`

type RemoveCourseInstructorParams struct {
	CourseID     uuid.UUID `json:"course_id"`
	InstructorID uuid.UUID `json:"instructor_id"`
}

func (q *Queries) RemoveCourseInstructor(ctx context.Context, arg RemoveCourseInstructorParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeCourseInstructor, arg.CourseID, arg.InstructorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCourseStatus = `-- name: SetCourseStatus :one
UPDATE courses SET status=$2,published_at=CASE WHEN $2='published' THEN COALESCE(published_at,now()) ELSE published_at END,version=version+1,updated_at=now() WHERE id=$1 RETURNING id, organization_id, category_id, thumbnail_asset_id, title, slug, description, language, level, status, is_free, price_minor, currency, completion_video_threshold, version, published_at, created_by, created_at, updated_at, search_vector, passing_percentage
`

type SetCourseStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetCourseStatus(ctx context.Context, arg SetCourseStatusParams) (Course, error) {
	row := q.db.QueryRow(ctx, setCourseStatus, arg.ID, arg.Status)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.ThumbnailAssetID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Language,
		&i.Level,
		&i.Status,
		&i.IsFree,
		&i.PriceMinor,
		&i.Currency,
		&i.CompletionVideoThreshold,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.PassingPercentage,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE course_categories SET name=$3, slug=$4, description=$5, updated_at=now()
WHERE id=$1 AND organization_id=$2 RETURNING id, organization_id, name, slug, description, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    string    `json:"description"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (CourseCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i CourseCategory
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses SET category_id=$1, thumbnail_asset_id=$2, title=$3, slug=$4, description=$5,
 language=$6, level=$7, is_free=$8, price_minor=$9, currency=$10,
 version=version+1, updated_at=now()
WHERE id=$11 AND organization_id=$12 AND version=$13 RETURNING id, organization_id, category_id, thumbnail_asset_id, title, slug, description, language, level, status, is_free, price_minor, currency, completion_video_threshold, version, published_at, created_by, created_at, updated_at, search_vector, passing_percentage
`

type UpdateCourseParams struct {
	CategoryID       uuid.NullUUID `json:"category_id"`
	ThumbnailAssetID uuid.NullUUID `json:"thumbnail_asset_id"`
	Title            string        `json:"title"`
	Slug             string        `json:"slug"`
	Description      string        `json:"description"`
	Language         string        `json:"language"`
	Level            string        `json:"level"`
	IsFree           bool          `json:"is_free"`
	PriceMinor       int64         `json:"price_minor"`
	Currency         string        `json:"currency"`
	ID               uuid.UUID     `json:"id"`
	OrganizationID   uuid.UUID     `json:"organization_id"`
	ExpectedVersion  int64         `json:"expected_version"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.CategoryID,
		arg.ThumbnailAssetID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Language,
		arg.Level,
		arg.IsFree,
		arg.PriceMinor,
		arg.Currency,
		arg.ID,
		arg.OrganizationID,
		arg.ExpectedVersion,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CategoryID,
		&i.ThumbnailAssetID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Language,
		&i.Level,
		&i.Status,
		&i.IsFree,
		&i.PriceMinor,
		&i.Currency,
		&i.CompletionVideoThreshold,
		&i.Version,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.PassingPercentage,
	)
	return i, err
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lessons SET title=$1,description=$2,lesson_type=$3,media_asset_id=$4,body=$5,position=$6,is_preview=$7,is_required=$8,is_published=$9,duration_seconds=$10,updated_at=now()
WHERE id=$11 RETURNING id, module_id, title, description, lesson_type, media_asset_id, body, position, is_preview, is_required, is_published, duration_seconds, metadata, created_at, updated_at
`

type UpdateLessonParams struct {
	Title           string        `json:"title"`
	Description     string        `json:"description"`
	LessonType      string        `json:"lesson_type"`
	MediaAssetID    uuid.NullUUID `json:"media_asset_id"`
	Body            string        `json:"body"`
	Position        int32         `json:"position"`
	IsPreview       bool          `json:"is_preview"`
	IsRequired      bool          `json:"is_required"`
	IsPublished     bool          `json:"is_published"`
	DurationSeconds pgtype.Int4   `json:"duration_seconds"`
	ID              uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.Title,
		arg.Description,
		arg.LessonType,
		arg.MediaAssetID,
		arg.Body,
		arg.Position,
		arg.IsPreview,
		arg.IsRequired,
		arg.IsPublished,
		arg.DurationSeconds,
		arg.ID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Description,
		&i.LessonType,
		&i.MediaAssetID,
		&i.Body,
		&i.Position,
		&i.IsPreview,
		&i.IsRequired,
		&i.IsPublished,
		&i.DurationSeconds,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModule = `-- name: UpdateModule :one
UPDATE course_modules SET title=$2,description=$3,position=$4,updated_at=now() WHERE id=$1 RETURNING id, course_id, title, description, position, created_at, updated_at
`

type UpdateModuleParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Position    int32     `json:"position"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (CourseModule, error) {
	row := q.db.QueryRow(ctx, updateModule,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i CourseModule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
