// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const calculateLessonCompletion = `-- name: CalculateLessonCompletion :one
SELECT count(*) FILTER(WHERE l.is_required) AS required_count,
 count(*) FILTER(WHERE l.is_required AND p.state='completed') AS completed_count
FROM lessons l JOIN course_modules m ON m.id=l.module_id
LEFT JOIN lesson_progress p ON p.lesson_id=l.id AND p.enrollment_id=$1
WHERE m.course_id=$2 AND l.is_published
`

type CalculateLessonCompletionParams struct {
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	CourseID     uuid.UUID `json:"course_id"`
}

type CalculateLessonCompletionRow struct {
	RequiredCount  int64 `json:"required_count"`
	CompletedCount int64 `json:"completed_count"`
}

func (q *Queries) CalculateLessonCompletion(ctx context.Context, arg CalculateLessonCompletionParams) (CalculateLessonCompletionRow, error) {
	row := q.db.QueryRow(ctx, calculateLessonCompletion, arg.EnrollmentID, arg.CourseID)
	var i CalculateLessonCompletionRow
	err := row.Scan(&i.RequiredCount, &i.CompletedCount)
	return i, err
}

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (id,organization_id,course_id,student_id,status,source,price_minor_snapshot,currency_snapshot,enrolled_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $5='active' THEN now() ELSE NULL END)
ON CONFLICT (course_id,student_id) DO UPDATE SET updated_at=now()
RETURNING id, organization_id, course_id, student_id, status, source, price_minor_snapshot, currency_snapshot, completion_percentage, enrolled_at, completed_at, expires_at, created_at, updated_at
`

type CreateEnrollmentParams struct {
	ID                 uuid.UUID `json:"id"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	CourseID           uuid.UUID `json:"course_id"`
	StudentID          uuid.UUID `json:"student_id"`
	Status             string    `json:"status"`
	Source             string    `json:"source"`
	PriceMinorSnapshot int64     `json:"price_minor_snapshot"`
	CurrencySnapshot   string    `json:"currency_snapshot"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.ID,
		arg.OrganizationID,
		arg.CourseID,
		arg.StudentID,
		arg.Status,
		arg.Source,
		arg.PriceMinorSnapshot,
		arg.CurrencySnapshot,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.StudentID,
		&i.Status,
		&i.Source,
		&i.PriceMinorSnapshot,
		&i.CurrencySnapshot,
		&i.CompletionPercentage,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireDueEnrollments = `-- name: ExpireDueEnrollments :many
WITH due AS (
 SELECT id FROM enrollments WHERE status='active' AND expires_at<=now() ORDER BY expires_at,id FOR UPDATE SKIP LOCKED LIMIT $1
)
UPDATE enrollments e SET status='expired',updated_at=now() FROM due WHERE e.id=due.id RETURNING e.id
`

func (q *Queries) ExpireDueEnrollments(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, expireDueEnrollments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseEnrollment = `-- name: GetCourseEnrollment :one
SELECT id, organization_id, course_id, student_id, status, source, price_minor_snapshot, currency_snapshot, completion_percentage, enrolled_at, completed_at, expires_at, created_at, updated_at FROM enrollments WHERE course_id=$1 AND student_id=$2
`

type GetCourseEnrollmentParams struct {
	CourseID  uuid.UUID `json:"course_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) GetCourseEnrollment(ctx context.Context, arg GetCourseEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getCourseEnrollment, arg.CourseID, arg.StudentID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.StudentID,
		&i.Status,
		&i.Source,
		&i.PriceMinorSnapshot,
		&i.CurrencySnapshot,
		&i.CompletionPercentage,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, organization_id, course_id, student_id, status, source, price_minor_snapshot, currency_snapshot, completion_percentage, enrolled_at, completed_at, expires_at, created_at, updated_at FROM enrollments WHERE id=$1
`

func (q *Queries) GetEnrollment(ctx context.Context, id uuid.UUID) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.StudentID,
		&i.Status,
		&i.Source,
		&i.PriceMinorSnapshot,
		&i.CurrencySnapshot,
		&i.CompletionPercentage,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollmentForUpdate = `-- name: GetEnrollmentForUpdate :one
SELECT id, organization_id, course_id, student_id, status, source, price_minor_snapshot, currency_snapshot, completion_percentage, enrolled_at, completed_at, expires_at, created_at, updated_at FROM enrollments WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetEnrollmentForUpdate(ctx context.Context, id uuid.UUID) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentForUpdate, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.StudentID,
		&i.Status,
		&i.Source,
		&i.PriceMinorSnapshot,
		&i.CurrencySnapshot,
		&i.CompletionPercentage,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonProgress = `-- name: GetLessonProgress :one
SELECT id, enrollment_id, lesson_id, state, last_position_seconds, total_watched_seconds, completed_at, created_at, updated_at FROM lesson_progress WHERE enrollment_id=$1 AND lesson_id=$2
`

type GetLessonProgressParams struct {
	EnrollmentID uuid.UUID `json:"enrollment_id"`
	LessonID     uuid.UUID `json:"lesson_id"`
}

func (q *Queries) GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRow(ctx, getLessonProgress, arg.EnrollmentID, arg.LessonID)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.LessonID,
		&i.State,
		&i.LastPositionSeconds,
		&i.TotalWatchedSeconds,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminEnrollments = `-- name: ListAdminEnrollments :many
SELECT e.id, e.organization_id, e.course_id, e.student_id, e.status, e.source, e.price_minor_snapshot, e.currency_snapshot, e.completion_percentage, e.enrolled_at, e.completed_at, e.expires_at, e.created_at, e.updated_at, c.title AS course_title, u.email AS student_email, u.display_name AS student_name
FROM enrollments e
JOIN courses c ON c.id=e.course_id
JOIN users u ON u.id=e.student_id
WHERE e.organization_id=$1
  AND ($2::text IS NULL OR e.status=$2)
  AND ($3::uuid IS NULL OR e.course_id=$3)
  AND ($4::uuid IS NULL OR e.student_id=$4)
  AND ($5::timestamptz IS NULL OR (e.created_at,e.id)<($5,$6::uuid))
ORDER BY e.created_at DESC,e.id DESC LIMIT $7
`

type ListAdminEnrollmentsParams struct {
	OrganizationID  uuid.UUID          `json:"organization_id"`
	Status          pgtype.Text        `json:"status"`
	CourseID        uuid.NullUUID      `json:"course_id"`
	StudentID       uuid.NullUUID      `json:"student_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListAdminEnrollmentsRow struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	CourseID             uuid.UUID          `json:"course_id"`
	StudentID            uuid.UUID          `json:"student_id"`
	Status               string             `json:"status"`
	Source               string             `json:"source"`
	PriceMinorSnapshot   int64              `json:"price_minor_snapshot"`
	CurrencySnapshot     string             `json:"currency_snapshot"`
	CompletionPercentage pgtype.Numeric     `json:"completion_percentage"`
	EnrolledAt           pgtype.Timestamptz `json:"enrolled_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CourseTitle          string             `json:"course_title"`
	StudentEmail         string             `json:"student_email"`
	StudentName          string             `json:"student_name"`
}

func (q *Queries) ListAdminEnrollments(ctx context.Context, arg ListAdminEnrollmentsParams) ([]ListAdminEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listAdminEnrollments,
		arg.OrganizationID,
		arg.Status,
		arg.CourseID,
		arg.StudentID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminEnrollmentsRow{}
	for rows.Next() {
		var i ListAdminEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CourseID,
			&i.StudentID,
			&i.Status,
			&i.Source,
			&i.PriceMinorSnapshot,
			&i.CurrencySnapshot,
			&i.CompletionPercentage,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseTitle,
			&i.StudentEmail,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseEnrollments = `-- name: ListCourseEnrollments :many
SELECT e.id, e.organization_id, e.course_id, e.student_id, e.status, e.source, e.price_minor_snapshot, e.currency_snapshot, e.completion_percentage, e.enrolled_at, e.completed_at, e.expires_at, e.created_at, e.updated_at,u.email,u.display_name FROM enrollments e JOIN users u ON u.id=e.student_id
WHERE e.course_id=$1
 AND ($2::timestamptz IS NULL OR (e.created_at,e.id)<($2,$3::uuid))
ORDER BY e.created_at DESC,e.id DESC LIMIT $4
`

type ListCourseEnrollmentsParams struct {
	CourseID        uuid.UUID          `json:"course_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListCourseEnrollmentsRow struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	CourseID             uuid.UUID          `json:"course_id"`
	StudentID            uuid.UUID          `json:"student_id"`
	Status               string             `json:"status"`
	Source               string             `json:"source"`
	PriceMinorSnapshot   int64              `json:"price_minor_snapshot"`
	CurrencySnapshot     string             `json:"currency_snapshot"`
	CompletionPercentage pgtype.Numeric     `json:"completion_percentage"`
	EnrolledAt           pgtype.Timestamptz `json:"enrolled_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Email                string             `json:"email"`
	DisplayName          string             `json:"display_name"`
}

func (q *Queries) ListCourseEnrollments(ctx context.Context, arg ListCourseEnrollmentsParams) ([]ListCourseEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listCourseEnrollments,
		arg.CourseID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseEnrollmentsRow{}
	for rows.Next() {
		var i ListCourseEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CourseID,
			&i.StudentID,
			&i.Status,
			&i.Source,
			&i.PriceMinorSnapshot,
			&i.CurrencySnapshot,
			&i.CompletionPercentage,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentProgress = `-- name: ListEnrollmentProgress :many
SELECT p.id, p.enrollment_id, p.lesson_id, p.state, p.last_position_seconds, p.total_watched_seconds, p.completed_at, p.created_at, p.updated_at,l.title AS lesson_title,l.lesson_type,l.duration_seconds
FROM lesson_progress p JOIN lessons l ON l.id=p.lesson_id WHERE p.enrollment_id=$1
 AND ($2::timestamptz IS NULL OR (p.updated_at,p.id)<($2,$3::uuid))
ORDER BY p.updated_at DESC,p.id DESC LIMIT $4
`

type ListEnrollmentProgressParams struct {
	EnrollmentID    uuid.UUID          `json:"enrollment_id"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListEnrollmentProgressRow struct {
	ID                  uuid.UUID          `json:"id"`
	EnrollmentID        uuid.UUID          `json:"enrollment_id"`
	LessonID            uuid.UUID          `json:"lesson_id"`
	State               string             `json:"state"`
	LastPositionSeconds int32              `json:"last_position_seconds"`
	TotalWatchedSeconds int32              `json:"total_watched_seconds"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LessonTitle         string             `json:"lesson_title"`
	LessonType          string             `json:"lesson_type"`
	DurationSeconds     pgtype.Int4        `json:"duration_seconds"`
}

func (q *Queries) ListEnrollmentProgress(ctx context.Context, arg ListEnrollmentProgressParams) ([]ListEnrollmentProgressRow, error) {
	rows, err := q.db.Query(ctx, listEnrollmentProgress,
		arg.EnrollmentID,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnrollmentProgressRow{}
	for rows.Next() {
		var i ListEnrollmentProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.LessonID,
			&i.State,
			&i.LastPositionSeconds,
			&i.TotalWatchedSeconds,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LessonTitle,
			&i.LessonType,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentEnrollments = `-- name: ListStudentEnrollments :many
SELECT e.id, e.organization_id, e.course_id, e.student_id, e.status, e.source, e.price_minor_snapshot, e.currency_snapshot, e.completion_percentage, e.enrolled_at, e.completed_at, e.expires_at, e.created_at, e.updated_at,c.title AS course_title,c.slug AS course_slug,c.thumbnail_asset_id
FROM enrollments e JOIN courses c ON c.id=e.course_id
WHERE e.student_id=$1
 AND ($2::timestamptz IS NULL OR (e.updated_at,e.id)<($2,$3::uuid))
ORDER BY e.updated_at DESC,e.id DESC LIMIT $4
`

type ListStudentEnrollmentsParams struct {
	StudentID       uuid.UUID          `json:"student_id"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListStudentEnrollmentsRow struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	CourseID             uuid.UUID          `json:"course_id"`
	StudentID            uuid.UUID          `json:"student_id"`
	Status               string             `json:"status"`
	Source               string             `json:"source"`
	PriceMinorSnapshot   int64              `json:"price_minor_snapshot"`
	CurrencySnapshot     string             `json:"currency_snapshot"`
	CompletionPercentage pgtype.Numeric     `json:"completion_percentage"`
	EnrolledAt           pgtype.Timestamptz `json:"enrolled_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CourseTitle          string             `json:"course_title"`
	CourseSlug           string             `json:"course_slug"`
	ThumbnailAssetID     uuid.NullUUID      `json:"thumbnail_asset_id"`
}

func (q *Queries) ListStudentEnrollments(ctx context.Context, arg ListStudentEnrollmentsParams) ([]ListStudentEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listStudentEnrollments,
		arg.StudentID,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentEnrollmentsRow{}
	for rows.Next() {
		var i ListStudentEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CourseID,
			&i.StudentID,
			&i.Status,
			&i.Source,
			&i.PriceMinorSnapshot,
			&i.CurrencySnapshot,
			&i.CompletionPercentage,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseTitle,
			&i.CourseSlug,
			&i.ThumbnailAssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resumeLearning = `-- name: ResumeLearning :one
SELECT e.id AS enrollment_id,c.id AS course_id,c.title AS course_title,l.id AS lesson_id,l.title AS lesson_title,p.last_position_seconds,p.updated_at
FROM enrollments e JOIN courses c ON c.id=e.course_id
JOIN lesson_progress p ON p.enrollment_id=e.id
JOIN lessons l ON l.id=p.lesson_id
WHERE e.student_id=$1 AND e.status='active' AND p.state<>'completed'
ORDER BY p.updated_at DESC,p.id DESC LIMIT 1
`

type ResumeLearningRow struct {
	EnrollmentID        uuid.UUID          `json:"enrollment_id"`
	CourseID            uuid.UUID          `json:"course_id"`
	CourseTitle         string             `json:"course_title"`
	LessonID            uuid.UUID          `json:"lesson_id"`
	LessonTitle         string             `json:"lesson_title"`
	LastPositionSeconds int32              `json:"last_position_seconds"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ResumeLearning(ctx context.Context, studentID uuid.UUID) (ResumeLearningRow, error) {
	row := q.db.QueryRow(ctx, resumeLearning, studentID)
	var i ResumeLearningRow
	err := row.Scan(
		&i.EnrollmentID,
		&i.CourseID,
		&i.CourseTitle,
		&i.LessonID,
		&i.LessonTitle,
		&i.LastPositionSeconds,
		&i.UpdatedAt,
	)
	return i, err
}

const setEnrollmentStatus = `-- name: SetEnrollmentStatus :one
UPDATE enrollments SET status=$2,enrolled_at=CASE WHEN $2='active' THEN COALESCE(enrolled_at,now()) ELSE enrolled_at END,completed_at=CASE WHEN $2='completed' THEN COALESCE(completed_at,now()) ELSE completed_at END,updated_at=now() WHERE id=$1 RETURNING id, organization_id, course_id, student_id, status, source, price_minor_snapshot, currency_snapshot, completion_percentage, enrolled_at, completed_at, expires_at, created_at, updated_at
`

type SetEnrollmentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetEnrollmentStatus(ctx context.Context, arg SetEnrollmentStatusParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, setEnrollmentStatus, arg.ID, arg.Status)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.StudentID,
		&i.Status,
		&i.Source,
		&i.PriceMinorSnapshot,
		&i.CurrencySnapshot,
		&i.CompletionPercentage,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnrollmentCompletionPercentage = `-- name: UpdateEnrollmentCompletionPercentage :one
UPDATE enrollments SET completion_percentage=$2,updated_at=now() WHERE id=$1 RETURNING id, organization_id, course_id, student_id, status, source, price_minor_snapshot, currency_snapshot, completion_percentage, enrolled_at, completed_at, expires_at, created_at, updated_at
`

type UpdateEnrollmentCompletionPercentageParams struct {
	ID                   uuid.UUID      `json:"id"`
	CompletionPercentage pgtype.Numeric `json:"completion_percentage"`
}

func (q *Queries) UpdateEnrollmentCompletionPercentage(ctx context.Context, arg UpdateEnrollmentCompletionPercentageParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollmentCompletionPercentage, arg.ID, arg.CompletionPercentage)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.StudentID,
		&i.Status,
		&i.Source,
		&i.PriceMinorSnapshot,
		&i.CurrencySnapshot,
		&i.CompletionPercentage,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLessonProgress = `-- name: UpsertLessonProgress :one
INSERT INTO lesson_progress (id,enrollment_id,lesson_id,state,last_position_seconds,total_watched_seconds,completed_at)
VALUES ($1,$2,$3,$4,$5,$6,CASE WHEN $4::text='completed' THEN now() ELSE NULL END)
ON CONFLICT (enrollment_id,lesson_id) DO UPDATE SET
 state=CASE WHEN lesson_progress.state='completed' THEN 'completed' ELSE EXCLUDED.state END,
 last_position_seconds=EXCLUDED.last_position_seconds,
 total_watched_seconds=LEAST($7,GREATEST(lesson_progress.total_watched_seconds,LEAST(EXCLUDED.total_watched_seconds,lesson_progress.total_watched_seconds+120))),
 completed_at=CASE WHEN lesson_progress.completed_at IS NOT NULL THEN lesson_progress.completed_at WHEN EXCLUDED.state='completed' THEN now() ELSE NULL END,
 updated_at=now()
RETURNING id, enrollment_id, lesson_id, state, last_position_seconds, total_watched_seconds, completed_at, created_at, updated_at
`

type UpsertLessonProgressParams struct {
	ID                  uuid.UUID `json:"id"`
	EnrollmentID        uuid.UUID `json:"enrollment_id"`
	LessonID            uuid.UUID `json:"lesson_id"`
	State               string    `json:"state"`
	LastPositionSeconds int32     `json:"last_position_seconds"`
	TotalWatchedSeconds int32     `json:"total_watched_seconds"`
	DurationCap         int32     `json:"duration_cap"`
}

func (q *Queries) UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRow(ctx, upsertLessonProgress,
		arg.ID,
		arg.EnrollmentID,
		arg.LessonID,
		arg.State,
		arg.LastPositionSeconds,
		arg.TotalWatchedSeconds,
		arg.DurationCap,
	)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.LessonID,
		&i.State,
		&i.LastPositionSeconds,
		&i.TotalWatchedSeconds,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
