// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignGlobalRole = `-- name: AssignGlobalRole :exec
INSERT INTO user_roles (user_id, role_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AssignGlobalRoleParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	RoleID     uuid.UUID     `json:"role_id"`
	AssignedBy uuid.NullUUID `json:"assigned_by"`
}

func (q *Queries) AssignGlobalRole(ctx context.Context, arg AssignGlobalRoleParams) error {
	_, err := q.db.Exec(ctx, assignGlobalRole, arg.UserID, arg.RoleID, arg.AssignedBy)
	return err
}

const consumeEmailVerificationToken = `-- name: ConsumeEmailVerificationToken :one
UPDATE email_verification_tokens
SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumeEmailVerificationToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerificationToken, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :exec
INSERT INTO email_verification_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateEmailVerificationTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailVerificationToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordResetTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createPasswordUser = `-- name: CreatePasswordUser :one
INSERT INTO users (
    id, firebase_uid, email, display_name, password_hash, status
) VALUES (
    $1, 'local:' || ($1::uuid)::text, lower($2),
    $3, $4, 'pending'
)
RETURNING id, firebase_uid, email, display_name, avatar_url, status, created_at, updated_at, last_login_at, password_hash, email_verified_at, failed_login_count, locked_until
`

type CreatePasswordUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreatePasswordUser(ctx context.Context, arg CreatePasswordUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createPasswordUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
	)
	return i, err
}

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (
    id, family_id, parent_id, user_id, token_hash, expires_at, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    nullif($7::text, '')::inet, $8
)
RETURNING id, family_id, parent_id, user_id, token_hash, expires_at, last_used_at, rotated_at, revoked_at, reuse_detected_at, ip_address, user_agent, created_at
`

type CreateRefreshSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	FamilyID  uuid.UUID          `json:"family_id"`
	ParentID  uuid.NullUUID      `json:"parent_id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IpAddress string             `json:"ip_address"`
	UserAgent string             `json:"user_agent"`
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.ID,
		arg.FamilyID,
		arg.ParentID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ParentID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.ReuseDetectedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createStudentProfile = `-- name: CreateStudentProfile :exec
INSERT INTO student_profiles (user_id) VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) CreateStudentProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createStudentProfile, userID)
	return err
}

const createTeacherProfile = `-- name: CreateTeacherProfile :exec
INSERT INTO teacher_profiles (user_id) VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) CreateTeacherProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createTeacherProfile, userID)
	return err
}

const createUserProfile = `-- name: CreateUserProfile :exec
INSERT INTO user_profiles (user_id, first_name, last_name)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
`

type CreateUserProfileParams struct {
	UserID    uuid.UUID `json:"user_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error {
	_, err := q.db.Exec(ctx, createUserProfile, arg.UserID, arg.FirstName, arg.LastName)
	return err
}

const deleteActiveEmailVerificationTokens = `-- name: DeleteActiveEmailVerificationTokens :exec
DELETE FROM email_verification_tokens WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteActiveEmailVerificationTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteActiveEmailVerificationTokens, userID)
	return err
}

const deleteActivePasswordResetTokens = `-- name: DeleteActivePasswordResetTokens :exec
DELETE FROM password_reset_tokens WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteActivePasswordResetTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteActivePasswordResetTokens, userID)
	return err
}

const deleteGlobalRoles = `-- name: DeleteGlobalRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteGlobalRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGlobalRoles, userID)
	return err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT u.id, u.email, u.display_name, u.status, u.email_verified_at,
       u.created_at, u.updated_at,
       COALESCE(array_agg(DISTINCT r.code ORDER BY r.code)
           FILTER (WHERE r.code IS NOT NULL), '{}')::text[] AS roles
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
WHERE u.id = $1
GROUP BY u.id
`

type GetAdminUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Roles           []string           `json:"roles"`
}

func (q *Queries) GetAdminUser(ctx context.Context, id uuid.UUID) (GetAdminUserRow, error) {
	row := q.db.QueryRow(ctx, getAdminUser, id)
	var i GetAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Roles,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, status, created_at, updated_at FROM organizations WHERE slug = $1 AND status = 'active'
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshSessionForUpdate = `-- name: GetRefreshSessionForUpdate :one
SELECT id, family_id, parent_id, user_id, token_hash, expires_at, last_used_at, rotated_at, revoked_at, reuse_detected_at, ip_address, user_agent, created_at FROM refresh_sessions WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetRefreshSessionForUpdate(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionForUpdate, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ParentID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.ReuseDetectedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT u.id, u.email, u.display_name, u.status, u.avatar_url, u.email_verified_at,
       p.first_name, p.last_name, p.phone, p.timezone, p.locale,
       t.biography, t.expertise, t.status AS teacher_status,
       s.headline AS student_headline,
       COALESCE(array_agg(DISTINCT r.code ORDER BY r.code)
           FILTER (WHERE r.code IS NOT NULL), '{}')::text[] AS roles
FROM users u
LEFT JOIN user_profiles p ON p.user_id = u.id
LEFT JOIN teacher_profiles t ON t.user_id = u.id
LEFT JOIN student_profiles s ON s.user_id = u.id
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
WHERE u.id = $1
GROUP BY u.id, p.user_id, t.user_id, s.user_id
`

type GetUserProfileRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	Status          string             `json:"status"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	FirstName       pgtype.Text        `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	Phone           pgtype.Text        `json:"phone"`
	Timezone        pgtype.Text        `json:"timezone"`
	Locale          pgtype.Text        `json:"locale"`
	Biography       pgtype.Text        `json:"biography"`
	Expertise       []string           `json:"expertise"`
	TeacherStatus   pgtype.Text        `json:"teacher_status"`
	StudentHeadline pgtype.Text        `json:"student_headline"`
	Roles           []string           `json:"roles"`
}

func (q *Queries) GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.AvatarUrl,
		&i.EmailVerifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Timezone,
		&i.Locale,
		&i.Biography,
		&i.Expertise,
		&i.TeacherStatus,
		&i.StudentHeadline,
		&i.Roles,
	)
	return i, err
}

const insertSecurityAudit = `-- name: InsertSecurityAudit :exec
INSERT INTO audit_logs (
    id, actor_user_id, action, resource_type, resource_id, request_id,
    ip_address, user_agent, metadata
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    nullif($7::text, '')::inet, $8,
    $9
)
`

type InsertSecurityAuditParams struct {
	ID           uuid.UUID     `json:"id"`
	ActorUserID  uuid.NullUUID `json:"actor_user_id"`
	Action       string        `json:"action"`
	ResourceType string        `json:"resource_type"`
	ResourceID   uuid.NullUUID `json:"resource_id"`
	RequestID    pgtype.Text   `json:"request_id"`
	IpAddress    string        `json:"ip_address"`
	UserAgent    string        `json:"user_agent"`
	Metadata     []byte        `json:"metadata"`
}

func (q *Queries) InsertSecurityAudit(ctx context.Context, arg InsertSecurityAuditParams) error {
	_, err := q.db.Exec(ctx, insertSecurityAudit,
		arg.ID,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.RequestID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT u.id, u.email, u.display_name, u.status, u.email_verified_at,
       u.created_at, u.updated_at,
       COALESCE(array_agg(DISTINCT r.code ORDER BY r.code)
           FILTER (WHERE r.code IS NOT NULL), '{}')::text[] AS roles
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
WHERE ($1::text IS NULL OR u.status = $1)
  AND ($2::text IS NULL OR EXISTS (
      SELECT 1 FROM user_roles ur2 JOIN roles r2 ON r2.id = ur2.role_id
      WHERE ur2.user_id = u.id AND r2.code = $2
  ))
  AND ($3::text = '' OR
       u.email ILIKE '%' || $3 || '%' OR
       u.display_name ILIKE '%' || $3 || '%')
  AND ($4::timestamptz IS NULL OR
       (u.created_at, u.id) < ($4, $5::uuid))
GROUP BY u.id
ORDER BY u.created_at DESC, u.id DESC
LIMIT $6
`

type ListAdminUsersParams struct {
	Status          pgtype.Text        `json:"status"`
	RoleCode        pgtype.Text        `json:"role_code"`
	Search          string             `json:"search"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListAdminUsersRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Roles           []string           `json:"roles"`
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers,
		arg.Status,
		arg.RoleCode,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalRoleCodes = `-- name: ListGlobalRoleCodes :many
SELECT r.code
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.code
`

func (q *Queries) ListGlobalRoleCodes(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listGlobalRoleCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshSessionRotated = `-- name: MarkRefreshSessionRotated :exec
UPDATE refresh_sessions
SET rotated_at = now(), last_used_at = now()
WHERE id = $1 AND rotated_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) MarkRefreshSessionRotated(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRefreshSessionRotated, id)
	return err
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE users
SET failed_login_count = failed_login_count + 1,
    locked_until = CASE
        WHEN failed_login_count + 1 >= $1
        THEN now() + $2::interval
        ELSE locked_until
    END,
    updated_at = now()
WHERE id = $3
RETURNING failed_login_count, locked_until
`

type RecordFailedLoginParams struct {
	LockAfter    int32           `json:"lock_after"`
	LockDuration pgtype.Interval `json:"lock_duration"`
	ID           uuid.UUID       `json:"id"`
}

type RecordFailedLoginRow struct {
	FailedLoginCount int32              `json:"failed_login_count"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (RecordFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, arg.LockAfter, arg.LockDuration, arg.ID)
	var i RecordFailedLoginRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const recordSuccessfulLogin = `-- name: RecordSuccessfulLogin :one
UPDATE users
SET failed_login_count = 0, locked_until = NULL, last_login_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, firebase_uid, email, display_name, avatar_url, status, created_at, updated_at, last_login_at, password_hash, email_verified_at, failed_login_count, locked_until
`

func (q *Queries) RecordSuccessfulLogin(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, recordSuccessfulLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
	)
	return i, err
}

const removeGlobalRole = `-- name: RemoveGlobalRole :execrows
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
`

type RemoveGlobalRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) RemoveGlobalRole(ctx context.Context, arg RemoveGlobalRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGlobalRole, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllRefreshSessions = `-- name: RevokeAllRefreshSessions :execrows
UPDATE refresh_sessions SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllRefreshSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshFamilyForReuse = `-- name: RevokeRefreshFamilyForReuse :exec
UPDATE refresh_sessions
SET revoked_at = COALESCE(revoked_at, now()), reuse_detected_at = now()
WHERE family_id = $1
`

func (q *Queries) RevokeRefreshFamilyForReuse(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamilyForReuse, familyID)
	return err
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :execrows
UPDATE refresh_sessions SET revoked_at = COALESCE(revoked_at, now())
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshSession(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserPassword = `-- name: SetUserPassword :one
UPDATE users
SET password_hash = $1, failed_login_count = 0,
    locked_until = NULL, updated_at = now()
WHERE id = $2
RETURNING id, firebase_uid, email, display_name, avatar_url, status, created_at, updated_at, last_login_at, password_hash, email_verified_at, failed_login_count, locked_until
`

type SetUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, firebase_uid, email, display_name, avatar_url, status, created_at, updated_at, last_login_at, password_hash, email_verified_at, failed_login_count, locked_until
`

type SetUserStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users SET display_name = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserDisplayNameParams struct {
	DisplayName string    `json:"display_name"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateUserDisplayName, arg.DisplayName, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE user_profiles
SET first_name = $1, last_name = $2,
    phone = $3, timezone = $4,
    locale = $5, updated_at = now()
WHERE user_id = $6
`

type UpdateUserProfileParams struct {
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Phone     pgtype.Text `json:"phone"`
	Timezone  string      `json:"timezone"`
	Locale    string      `json:"locale"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Timezone,
		arg.Locale,
		arg.UserID,
	)
	return err
}

const upsertTeacherProfile = `-- name: UpsertTeacherProfile :exec
INSERT INTO teacher_profiles (user_id, biography, expertise)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET biography = EXCLUDED.biography,
    expertise = EXCLUDED.expertise, updated_at = now()
`

type UpsertTeacherProfileParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Biography string    `json:"biography"`
	Expertise []string  `json:"expertise"`
}

func (q *Queries) UpsertTeacherProfile(ctx context.Context, arg UpsertTeacherProfileParams) error {
	_, err := q.db.Exec(ctx, upsertTeacherProfile, arg.UserID, arg.Biography, arg.Expertise)
	return err
}

const userHasGlobalRole = `-- name: UserHasGlobalRole :one
SELECT EXISTS (
    SELECT 1 FROM user_roles ur JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = $1 AND r.code = $2
) AS allowed
`

type UserHasGlobalRoleParams struct {
	UserID   uuid.UUID `json:"user_id"`
	RoleCode string    `json:"role_code"`
}

func (q *Queries) UserHasGlobalRole(ctx context.Context, arg UserHasGlobalRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasGlobalRole, arg.UserID, arg.RoleCode)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, now()),
    status = CASE WHEN status = 'pending' THEN 'active' ELSE status END,
    updated_at = now()
WHERE id = $1
RETURNING id, firebase_uid, email, display_name, avatar_url, status, created_at, updated_at, last_login_at, password_hash, email_verified_at, failed_login_count, locked_until
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
	)
	return i, err
}
