// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: liveclass.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeAttendanceInterval = `-- name: CloseAttendanceInterval :one
UPDATE live_attendance_sessions SET left_at=$2,duration_seconds=GREATEST(0,extract(epoch FROM ($2-joined_at))::integer) WHERE id=$1 RETURNING id, live_session_id, user_id, participant_identity, joined_at, left_at, duration_seconds, created_at
`

type CloseAttendanceIntervalParams struct {
	ID     uuid.UUID          `json:"id"`
	LeftAt pgtype.Timestamptz `json:"left_at"`
}

func (q *Queries) CloseAttendanceInterval(ctx context.Context, arg CloseAttendanceIntervalParams) (LiveAttendanceSession, error) {
	row := q.db.QueryRow(ctx, closeAttendanceInterval, arg.ID, arg.LeftAt)
	var i LiveAttendanceSession
	err := row.Scan(
		&i.ID,
		&i.LiveSessionID,
		&i.UserID,
		&i.ParticipantIdentity,
		&i.JoinedAt,
		&i.LeftAt,
		&i.DurationSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const createLiveSession = `-- name: CreateLiveSession :one
INSERT INTO live_sessions (id,organization_id,course_id,title,description,room_name,scheduled_start_at,scheduled_end_at,created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, organization_id, course_id, title, description, room_name, status, scheduled_start_at, scheduled_end_at, started_at, ended_at, created_by, created_at, updated_at
`

type CreateLiveSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	CourseID         uuid.UUID          `json:"course_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	RoomName         string             `json:"room_name"`
	ScheduledStartAt pgtype.Timestamptz `json:"scheduled_start_at"`
	ScheduledEndAt   pgtype.Timestamptz `json:"scheduled_end_at"`
	CreatedBy        uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreateLiveSession(ctx context.Context, arg CreateLiveSessionParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, createLiveSession,
		arg.ID,
		arg.OrganizationID,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.RoomName,
		arg.ScheduledStartAt,
		arg.ScheduledEndAt,
		arg.CreatedBy,
	)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.RoomName,
		&i.Status,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLiveWebhookEvent = `-- name: CreateLiveWebhookEvent :execrows
INSERT INTO live_webhook_events (id,provider_event_id,event_type,payload,processed_at) VALUES ($1,$2,$3,$4,now()) ON CONFLICT(provider_event_id) DO NOTHING
`

type CreateLiveWebhookEventParams struct {
	ID              uuid.UUID `json:"id"`
	ProviderEventID string    `json:"provider_event_id"`
	EventType       string    `json:"event_type"`
	Payload         []byte    `json:"payload"`
}

func (q *Queries) CreateLiveWebhookEvent(ctx context.Context, arg CreateLiveWebhookEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createLiveWebhookEvent,
		arg.ID,
		arg.ProviderEventID,
		arg.EventType,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, organization_id, course_id, title, description, room_name, status, scheduled_start_at, scheduled_end_at, started_at, ended_at, created_by, created_at, updated_at FROM live_sessions WHERE id=$1
`

func (q *Queries) GetLiveSession(ctx context.Context, id uuid.UUID) (LiveSession, error) {
	row := q.db.QueryRow(ctx, getLiveSession, id)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.RoomName,
		&i.Status,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveSessionByRoom = `-- name: GetLiveSessionByRoom :one
SELECT id, organization_id, course_id, title, description, room_name, status, scheduled_start_at, scheduled_end_at, started_at, ended_at, created_by, created_at, updated_at FROM live_sessions WHERE room_name=$1
`

func (q *Queries) GetLiveSessionByRoom(ctx context.Context, roomName string) (LiveSession, error) {
	row := q.db.QueryRow(ctx, getLiveSessionByRoom, roomName)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.RoomName,
		&i.Status,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenAttendanceIntervalForUpdate = `-- name: GetOpenAttendanceIntervalForUpdate :one
SELECT id, live_session_id, user_id, participant_identity, joined_at, left_at, duration_seconds, created_at FROM live_attendance_sessions WHERE live_session_id=$1 AND participant_identity=$2 AND left_at IS NULL ORDER BY joined_at DESC LIMIT 1 FOR UPDATE
`

type GetOpenAttendanceIntervalForUpdateParams struct {
	LiveSessionID       uuid.UUID `json:"live_session_id"`
	ParticipantIdentity string    `json:"participant_identity"`
}

func (q *Queries) GetOpenAttendanceIntervalForUpdate(ctx context.Context, arg GetOpenAttendanceIntervalForUpdateParams) (LiveAttendanceSession, error) {
	row := q.db.QueryRow(ctx, getOpenAttendanceIntervalForUpdate, arg.LiveSessionID, arg.ParticipantIdentity)
	var i LiveAttendanceSession
	err := row.Scan(
		&i.ID,
		&i.LiveSessionID,
		&i.UserID,
		&i.ParticipantIdentity,
		&i.JoinedAt,
		&i.LeftAt,
		&i.DurationSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const listLiveSessions = `-- name: ListLiveSessions :many
SELECT id, organization_id, course_id, title, description, room_name, status, scheduled_start_at, scheduled_end_at, started_at, ended_at, created_by, created_at, updated_at FROM live_sessions
WHERE organization_id=$1 AND status=ANY($2::text[])
 AND ($3::timestamptz IS NULL OR (scheduled_start_at,id)>($3,$4::uuid))
ORDER BY scheduled_start_at,id LIMIT $5
`

type ListLiveSessionsParams struct {
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Statuses          []string           `json:"statuses"`
	CursorScheduledAt pgtype.Timestamptz `json:"cursor_scheduled_at"`
	CursorID          uuid.NullUUID      `json:"cursor_id"`
	PageSize          int32              `json:"page_size"`
}

func (q *Queries) ListLiveSessions(ctx context.Context, arg ListLiveSessionsParams) ([]LiveSession, error) {
	rows, err := q.db.Query(ctx, listLiveSessions,
		arg.OrganizationID,
		arg.Statuses,
		arg.CursorScheduledAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveSession{}
	for rows.Next() {
		var i LiveSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.RoomName,
			&i.Status,
			&i.ScheduledStartAt,
			&i.ScheduledEndAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLiveSessionStatus = `-- name: SetLiveSessionStatus :one
UPDATE live_sessions SET status=$2,started_at=CASE WHEN $2='live' THEN COALESCE(started_at,now()) ELSE started_at END,ended_at=CASE WHEN $2='ended' THEN COALESCE(ended_at,now()) ELSE ended_at END,updated_at=now() WHERE id=$1 RETURNING id, organization_id, course_id, title, description, room_name, status, scheduled_start_at, scheduled_end_at, started_at, ended_at, created_by, created_at, updated_at
`

type SetLiveSessionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetLiveSessionStatus(ctx context.Context, arg SetLiveSessionStatusParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, setLiveSessionStatus, arg.ID, arg.Status)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.RoomName,
		&i.Status,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startAttendanceInterval = `-- name: StartAttendanceInterval :execrows
INSERT INTO live_attendance_sessions (id,live_session_id,user_id,participant_identity,joined_at) VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING
`

type StartAttendanceIntervalParams struct {
	ID                  uuid.UUID          `json:"id"`
	LiveSessionID       uuid.UUID          `json:"live_session_id"`
	UserID              uuid.UUID          `json:"user_id"`
	ParticipantIdentity string             `json:"participant_identity"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) StartAttendanceInterval(ctx context.Context, arg StartAttendanceIntervalParams) (int64, error) {
	result, err := q.db.Exec(ctx, startAttendanceInterval,
		arg.ID,
		arg.LiveSessionID,
		arg.UserID,
		arg.ParticipantIdentity,
		arg.JoinedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLiveSession = `-- name: UpdateLiveSession :one
UPDATE live_sessions SET title=$2,description=$3,scheduled_start_at=$4,scheduled_end_at=$5,updated_at=now()
WHERE id=$1 AND status='scheduled' RETURNING id, organization_id, course_id, title, description, room_name, status, scheduled_start_at, scheduled_end_at, started_at, ended_at, created_by, created_at, updated_at
`

type UpdateLiveSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	ScheduledStartAt pgtype.Timestamptz `json:"scheduled_start_at"`
	ScheduledEndAt   pgtype.Timestamptz `json:"scheduled_end_at"`
}

func (q *Queries) UpdateLiveSession(ctx context.Context, arg UpdateLiveSessionParams) (LiveSession, error) {
	row := q.db.QueryRow(ctx, updateLiveSession,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ScheduledStartAt,
		arg.ScheduledEndAt,
	)
	var i LiveSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.RoomName,
		&i.Status,
		&i.ScheduledStartAt,
		&i.ScheduledEndAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
