// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const canUserAccessMedia = `-- name: CanUserAccessMedia :one
SELECT EXISTS(
 SELECT 1 FROM media_assets a WHERE a.id=$1 AND a.owner_user_id=$2
 UNION ALL
 SELECT 1 FROM lessons l JOIN course_modules m ON m.id=l.module_id JOIN enrollments e ON e.course_id=m.course_id
 WHERE l.media_asset_id=$1 AND e.student_id=$2 AND e.status IN ('active','completed')
 UNION ALL
 SELECT 1 FROM lessons l JOIN course_modules m ON m.id=l.module_id
 WHERE l.media_asset_id=$1 AND l.is_preview AND l.is_published
 UNION ALL
 SELECT 1 FROM courses c WHERE c.thumbnail_asset_id=$1 AND c.status='published'
 UNION ALL
 SELECT 1 FROM lessons l JOIN course_modules m ON m.id=l.module_id JOIN course_instructors ci ON ci.course_id=m.course_id
 WHERE l.media_asset_id=$1 AND ci.instructor_id=$2
 UNION ALL
 SELECT 1 FROM assignment_submission_assets sa JOIN assignment_submissions s ON s.id=sa.submission_id
 WHERE sa.media_asset_id=$1 AND s.student_id=$2
 UNION ALL
 SELECT 1 FROM assignment_submission_assets sa JOIN assignment_submissions s ON s.id=sa.submission_id
 JOIN assignments x ON x.id=s.assignment_id JOIN course_instructors ci ON ci.course_id=x.course_id
 WHERE sa.media_asset_id=$1 AND ci.instructor_id=$2
 UNION ALL
 SELECT 1 FROM assignment_assets aa JOIN assignments x ON x.id=aa.assignment_id
 JOIN enrollments e ON e.course_id=x.course_id
 WHERE aa.media_asset_id=$1 AND e.student_id=$2 AND e.status IN ('active','completed') AND x.status='published'
 UNION ALL
 SELECT 1 FROM assignment_assets aa JOIN assignments x ON x.id=aa.assignment_id JOIN course_instructors ci ON ci.course_id=x.course_id
 WHERE aa.media_asset_id=$1 AND ci.instructor_id=$2
 UNION ALL
 SELECT 1 FROM certificates c WHERE c.media_asset_id=$1 AND c.student_id=$2
) AS allowed
`

type CanUserAccessMediaParams struct {
	MediaAssetID uuid.UUID `json:"media_asset_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) CanUserAccessMedia(ctx context.Context, arg CanUserAccessMediaParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserAccessMedia, arg.MediaAssetID, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const completeUploadIntent = `-- name: CompleteUploadIntent :one
UPDATE upload_intents SET status='completed',completed_at=COALESCE(completed_at,now()) WHERE id=$1 AND status IN ('pending','completed') RETURNING id, media_asset_id, owner_user_id, expected_size_bytes, expected_content_type, expected_checksum_sha256, status, expires_at, completed_at, created_at
`

func (q *Queries) CompleteUploadIntent(ctx context.Context, id uuid.UUID) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, completeUploadIntent, id)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.MediaAssetID,
		&i.OwnerUserID,
		&i.ExpectedSizeBytes,
		&i.ExpectedContentType,
		&i.ExpectedChecksumSha256,
		&i.Status,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (id,organization_id,owner_user_id,kind,status,storage_key,original_filename,content_type,size_bytes,checksum_sha256)
VALUES ($1,$2,$3,$4,'pending',$5,$6,$7,$8,$9) RETURNING id, organization_id, owner_user_id, kind, status, storage_key, original_filename, content_type, size_bytes, checksum_sha256, duration_seconds, width, height, metadata, failure_reason, created_at, updated_at
`

type CreateMediaAssetParams struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	OwnerUserID      uuid.UUID   `json:"owner_user_id"`
	Kind             string      `json:"kind"`
	StorageKey       string      `json:"storage_key"`
	OriginalFilename string      `json:"original_filename"`
	ContentType      string      `json:"content_type"`
	SizeBytes        int64       `json:"size_bytes"`
	ChecksumSha256   pgtype.Text `json:"checksum_sha256"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.ID,
		arg.OrganizationID,
		arg.OwnerUserID,
		arg.Kind,
		arg.StorageKey,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.ChecksumSha256,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerUserID,
		&i.Kind,
		&i.Status,
		&i.StorageKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.DurationSeconds,
		&i.Width,
		&i.Height,
		&i.Metadata,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUploadIntent = `-- name: CreateUploadIntent :one
INSERT INTO upload_intents (id,media_asset_id,owner_user_id,expected_size_bytes,expected_content_type,expected_checksum_sha256,expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, media_asset_id, owner_user_id, expected_size_bytes, expected_content_type, expected_checksum_sha256, status, expires_at, completed_at, created_at
`

type CreateUploadIntentParams struct {
	ID                     uuid.UUID          `json:"id"`
	MediaAssetID           uuid.UUID          `json:"media_asset_id"`
	OwnerUserID            uuid.UUID          `json:"owner_user_id"`
	ExpectedSizeBytes      int64              `json:"expected_size_bytes"`
	ExpectedContentType    string             `json:"expected_content_type"`
	ExpectedChecksumSha256 pgtype.Text        `json:"expected_checksum_sha256"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUploadIntent(ctx context.Context, arg CreateUploadIntentParams) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, createUploadIntent,
		arg.ID,
		arg.MediaAssetID,
		arg.OwnerUserID,
		arg.ExpectedSizeBytes,
		arg.ExpectedContentType,
		arg.ExpectedChecksumSha256,
		arg.ExpiresAt,
	)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.MediaAssetID,
		&i.OwnerUserID,
		&i.ExpectedSizeBytes,
		&i.ExpectedContentType,
		&i.ExpectedChecksumSha256,
		&i.Status,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, organization_id, owner_user_id, kind, status, storage_key, original_filename, content_type, size_bytes, checksum_sha256, duration_seconds, width, height, metadata, failure_reason, created_at, updated_at FROM media_assets WHERE id=$1
`

func (q *Queries) GetMediaAsset(ctx context.Context, id uuid.UUID) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAsset, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerUserID,
		&i.Kind,
		&i.Status,
		&i.StorageKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.DurationSeconds,
		&i.Width,
		&i.Height,
		&i.Metadata,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadIntentForUpdate = `-- name: GetUploadIntentForUpdate :one
SELECT id, media_asset_id, owner_user_id, expected_size_bytes, expected_content_type, expected_checksum_sha256, status, expires_at, completed_at, created_at FROM upload_intents WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetUploadIntentForUpdate(ctx context.Context, id uuid.UUID) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, getUploadIntentForUpdate, id)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.MediaAssetID,
		&i.OwnerUserID,
		&i.ExpectedSizeBytes,
		&i.ExpectedContentType,
		&i.ExpectedChecksumSha256,
		&i.Status,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadIntentWithAsset = `-- name: GetUploadIntentWithAsset :one
SELECT i.id,i.media_asset_id,i.owner_user_id,i.expected_size_bytes,i.expected_content_type,i.expected_checksum_sha256,i.status,i.expires_at,i.completed_at,
 a.organization_id,a.kind,a.status AS asset_status,a.storage_key,a.content_type,a.size_bytes,a.checksum_sha256
FROM upload_intents i JOIN media_assets a ON a.id=i.media_asset_id WHERE i.id=$1
`

type GetUploadIntentWithAssetRow struct {
	ID                     uuid.UUID          `json:"id"`
	MediaAssetID           uuid.UUID          `json:"media_asset_id"`
	OwnerUserID            uuid.UUID          `json:"owner_user_id"`
	ExpectedSizeBytes      int64              `json:"expected_size_bytes"`
	ExpectedContentType    string             `json:"expected_content_type"`
	ExpectedChecksumSha256 pgtype.Text        `json:"expected_checksum_sha256"`
	Status                 string             `json:"status"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	OrganizationID         uuid.UUID          `json:"organization_id"`
	Kind                   string             `json:"kind"`
	AssetStatus            string             `json:"asset_status"`
	StorageKey             string             `json:"storage_key"`
	ContentType            string             `json:"content_type"`
	SizeBytes              int64              `json:"size_bytes"`
	ChecksumSha256         pgtype.Text        `json:"checksum_sha256"`
}

func (q *Queries) GetUploadIntentWithAsset(ctx context.Context, id uuid.UUID) (GetUploadIntentWithAssetRow, error) {
	row := q.db.QueryRow(ctx, getUploadIntentWithAsset, id)
	var i GetUploadIntentWithAssetRow
	err := row.Scan(
		&i.ID,
		&i.MediaAssetID,
		&i.OwnerUserID,
		&i.ExpectedSizeBytes,
		&i.ExpectedContentType,
		&i.ExpectedChecksumSha256,
		&i.Status,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.OrganizationID,
		&i.Kind,
		&i.AssetStatus,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
	)
	return i, err
}

const setMediaAssetProcessed = `-- name: SetMediaAssetProcessed :one
UPDATE media_assets SET status='ready',duration_seconds=$2,width=$3,height=$4,metadata=$5,failure_reason=NULL,updated_at=now() WHERE id=$1 RETURNING id, organization_id, owner_user_id, kind, status, storage_key, original_filename, content_type, size_bytes, checksum_sha256, duration_seconds, width, height, metadata, failure_reason, created_at, updated_at
`

type SetMediaAssetProcessedParams struct {
	ID              uuid.UUID   `json:"id"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
	Width           pgtype.Int4 `json:"width"`
	Height          pgtype.Int4 `json:"height"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) SetMediaAssetProcessed(ctx context.Context, arg SetMediaAssetProcessedParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, setMediaAssetProcessed,
		arg.ID,
		arg.DurationSeconds,
		arg.Width,
		arg.Height,
		arg.Metadata,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerUserID,
		&i.Kind,
		&i.Status,
		&i.StorageKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.DurationSeconds,
		&i.Width,
		&i.Height,
		&i.Metadata,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setMediaAssetStatus = `-- name: SetMediaAssetStatus :one
UPDATE media_assets SET status=$2,failure_reason=$3,updated_at=now() WHERE id=$1 RETURNING id, organization_id, owner_user_id, kind, status, storage_key, original_filename, content_type, size_bytes, checksum_sha256, duration_seconds, width, height, metadata, failure_reason, created_at, updated_at
`

type SetMediaAssetStatusParams struct {
	ID            uuid.UUID   `json:"id"`
	Status        string      `json:"status"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) SetMediaAssetStatus(ctx context.Context, arg SetMediaAssetStatusParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, setMediaAssetStatus, arg.ID, arg.Status, arg.FailureReason)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerUserID,
		&i.Kind,
		&i.Status,
		&i.StorageKey,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.DurationSeconds,
		&i.Width,
		&i.Height,
		&i.Metadata,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
