// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package data

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID                 uuid.UUID          `json:"id"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	CourseID           uuid.UUID          `json:"course_id"`
	LessonID           uuid.NullUUID      `json:"lesson_id"`
	Title              string             `json:"title"`
	Instructions       string             `json:"instructions"`
	DueAt              pgtype.Timestamptz `json:"due_at"`
	MaximumScore       pgtype.Numeric     `json:"maximum_score"`
	PassingScore       pgtype.Numeric     `json:"passing_score"`
	AllowedFileTypes   []string           `json:"allowed_file_types"`
	MaximumSubmissions int32              `json:"maximum_submissions"`
	IsRequired         bool               `json:"is_required"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AssignmentAsset struct {
	AssignmentID uuid.UUID `json:"assignment_id"`
	MediaAssetID uuid.UUID `json:"media_asset_id"`
}

type AssignmentSubmission struct {
	ID               uuid.UUID          `json:"id"`
	AssignmentID     uuid.UUID          `json:"assignment_id"`
	EnrollmentID     uuid.UUID          `json:"enrollment_id"`
	StudentID        uuid.UUID          `json:"student_id"`
	SubmissionNumber int32              `json:"submission_number"`
	Status           string             `json:"status"`
	TextContent      string             `json:"text_content"`
	SubmittedAt      pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AssignmentSubmissionAsset struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	MediaAssetID uuid.UUID `json:"media_asset_id"`
}

type AuditLog struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.NullUUID      `json:"organization_id"`
	ActorUserID    uuid.NullUUID      `json:"actor_user_id"`
	Action         string             `json:"action"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     uuid.NullUUID      `json:"resource_id"`
	RequestID      pgtype.Text        `json:"request_id"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	BeforeData     []byte             `json:"before_data"`
	AfterData      []byte             `json:"after_data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Metadata       []byte             `json:"metadata"`
	UserAgent      string             `json:"user_agent"`
}

type Certificate struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	EnrollmentID      uuid.UUID          `json:"enrollment_id"`
	StudentID         uuid.UUID          `json:"student_id"`
	CourseID          uuid.UUID          `json:"course_id"`
	TemplateID        uuid.NullUUID      `json:"template_id"`
	CertificateNumber string             `json:"certificate_number"`
	VerificationCode  string             `json:"verification_code"`
	MediaAssetID      uuid.NullUUID      `json:"media_asset_id"`
	Status            string             `json:"status"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CertificateTemplate struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Name              string             `json:"name"`
	BackgroundAssetID uuid.NullUUID      `json:"background_asset_id"`
	Config            []byte             `json:"config"`
	IsDefault         bool               `json:"is_default"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Course struct {
	ID                       uuid.UUID          `json:"id"`
	OrganizationID           uuid.UUID          `json:"organization_id"`
	CategoryID               uuid.NullUUID      `json:"category_id"`
	ThumbnailAssetID         uuid.NullUUID      `json:"thumbnail_asset_id"`
	Title                    string             `json:"title"`
	Slug                     string             `json:"slug"`
	Description              string             `json:"description"`
	Language                 string             `json:"language"`
	Level                    string             `json:"level"`
	Status                   string             `json:"status"`
	IsFree                   bool               `json:"is_free"`
	PriceMinor               int64              `json:"price_minor"`
	Currency                 string             `json:"currency"`
	CompletionVideoThreshold pgtype.Numeric     `json:"completion_video_threshold"`
	Version                  int64              `json:"version"`
	PublishedAt              pgtype.Timestamptz `json:"published_at"`
	CreatedBy                uuid.UUID          `json:"created_by"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	SearchVector             interface{}        `json:"search_vector"`
	PassingPercentage        pgtype.Numeric     `json:"passing_percentage"`
}

type CourseCategory struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CourseCompletionSnapshot struct {
	ID                  uuid.UUID          `json:"id"`
	EnrollmentID        uuid.UUID          `json:"enrollment_id"`
	RequiredLessons     int32              `json:"required_lessons"`
	CompletedLessons    int32              `json:"completed_lessons"`
	RequiredQuizzes     int32              `json:"required_quizzes"`
	PassedQuizzes       int32              `json:"passed_quizzes"`
	RequiredAssignments int32              `json:"required_assignments"`
	PassedAssignments   int32              `json:"passed_assignments"`
	Percentage          pgtype.Numeric     `json:"percentage"`
	IsComplete          bool               `json:"is_complete"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type CourseInstructor struct {
	CourseID     uuid.UUID          `json:"course_id"`
	InstructorID uuid.UUID          `json:"instructor_id"`
	AssignedBy   uuid.UUID          `json:"assigned_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CourseModule struct {
	ID          uuid.UUID          `json:"id"`
	CourseID    uuid.UUID          `json:"course_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Position    int32              `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CourseResult struct {
	ID                   uuid.UUID          `json:"id"`
	EnrollmentID         uuid.UUID          `json:"enrollment_id"`
	StudentID            uuid.UUID          `json:"student_id"`
	CourseID             uuid.UUID          `json:"course_id"`
	QuizPercentage       pgtype.Numeric     `json:"quiz_percentage"`
	AssignmentPercentage pgtype.Numeric     `json:"assignment_percentage"`
	CompletionPercentage pgtype.Numeric     `json:"completion_percentage"`
	FinalPercentage      pgtype.Numeric     `json:"final_percentage"`
	PassingPercentage    pgtype.Numeric     `json:"passing_percentage"`
	Passed               bool               `json:"passed"`
	Components           []byte             `json:"components"`
	CalculatedAt         pgtype.Timestamptz `json:"calculated_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type DeviceToken struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	TokenHash      string             `json:"token_hash"`
	EncryptedToken string             `json:"encrypted_token"`
	Platform       string             `json:"platform"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type EmailVerificationToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Enrollment struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	CourseID             uuid.UUID          `json:"course_id"`
	StudentID            uuid.UUID          `json:"student_id"`
	Status               string             `json:"status"`
	Source               string             `json:"source"`
	PriceMinorSnapshot   int64              `json:"price_minor_snapshot"`
	CurrencySnapshot     string             `json:"currency_snapshot"`
	CompletionPercentage pgtype.Numeric     `json:"completion_percentage"`
	EnrolledAt           pgtype.Timestamptz `json:"enrolled_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Grade struct {
	ID                     uuid.UUID          `json:"id"`
	AssignmentSubmissionID uuid.NullUUID      `json:"assignment_submission_id"`
	QuizAttemptID          uuid.NullUUID      `json:"quiz_attempt_id"`
	StudentID              uuid.UUID          `json:"student_id"`
	GradedBy               uuid.UUID          `json:"graded_by"`
	Points                 pgtype.Numeric     `json:"points"`
	Percentage             pgtype.Numeric     `json:"percentage"`
	Feedback               string             `json:"feedback"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type IdempotencyRecord struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Scope          string             `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	ResourceID     uuid.NullUUID      `json:"resource_id"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Lesson struct {
	ID              uuid.UUID          `json:"id"`
	ModuleID        uuid.UUID          `json:"module_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	LessonType      string             `json:"lesson_type"`
	MediaAssetID    uuid.NullUUID      `json:"media_asset_id"`
	Body            string             `json:"body"`
	Position        int32              `json:"position"`
	IsPreview       bool               `json:"is_preview"`
	IsRequired      bool               `json:"is_required"`
	IsPublished     bool               `json:"is_published"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type LessonProgress struct {
	ID                  uuid.UUID          `json:"id"`
	EnrollmentID        uuid.UUID          `json:"enrollment_id"`
	LessonID            uuid.UUID          `json:"lesson_id"`
	State               string             `json:"state"`
	LastPositionSeconds int32              `json:"last_position_seconds"`
	TotalWatchedSeconds int32              `json:"total_watched_seconds"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type LiveAttendanceSession struct {
	ID                  uuid.UUID          `json:"id"`
	LiveSessionID       uuid.UUID          `json:"live_session_id"`
	UserID              uuid.UUID          `json:"user_id"`
	ParticipantIdentity string             `json:"participant_identity"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
	LeftAt              pgtype.Timestamptz `json:"left_at"`
	DurationSeconds     int32              `json:"duration_seconds"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type LiveSession struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	CourseID         uuid.UUID          `json:"course_id"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	RoomName         string             `json:"room_name"`
	Status           string             `json:"status"`
	ScheduledStartAt pgtype.Timestamptz `json:"scheduled_start_at"`
	ScheduledEndAt   pgtype.Timestamptz `json:"scheduled_end_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type LiveWebhookEvent struct {
	ID              uuid.UUID          `json:"id"`
	ProviderEventID string             `json:"provider_event_id"`
	EventType       string             `json:"event_type"`
	Payload         []byte             `json:"payload"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type MediaAsset struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	OwnerUserID      uuid.UUID          `json:"owner_user_id"`
	Kind             string             `json:"kind"`
	Status           string             `json:"status"`
	StorageKey       string             `json:"storage_key"`
	OriginalFilename string             `json:"original_filename"`
	ContentType      string             `json:"content_type"`
	SizeBytes        int64              `json:"size_bytes"`
	ChecksumSha256   pgtype.Text        `json:"checksum_sha256"`
	DurationSeconds  pgtype.Int4        `json:"duration_seconds"`
	Width            pgtype.Int4        `json:"width"`
	Height           pgtype.Int4        `json:"height"`
	Metadata         []byte             `json:"metadata"`
	FailureReason    pgtype.Text        `json:"failure_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MembershipRole struct {
	MembershipID uuid.UUID          `json:"membership_id"`
	RoleID       uuid.UUID          `json:"role_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	OrganizationID   uuid.NullUUID      `json:"organization_id"`
	Type             string             `json:"type"`
	Title            string             `json:"title"`
	Body             string             `json:"body"`
	Data             []byte             `json:"data"`
	DeduplicationKey pgtype.Text        `json:"deduplication_key"`
	ReadAt           pgtype.Timestamptz `json:"read_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type NotificationDelivery struct {
	ID                uuid.UUID          `json:"id"`
	NotificationID    uuid.UUID          `json:"notification_id"`
	DeviceTokenID     uuid.NullUUID      `json:"device_token_id"`
	Status            string             `json:"status"`
	Attempts          int32              `json:"attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	LastError         pgtype.Text        `json:"last_error"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID                      uuid.UUID          `json:"id"`
	OrganizationID          uuid.UUID          `json:"organization_id"`
	UserID                  uuid.UUID          `json:"user_id"`
	Status                  string             `json:"status"`
	AmountMinor             int64              `json:"amount_minor"`
	Currency                string             `json:"currency"`
	IdempotencyKey          string             `json:"idempotency_key"`
	ProviderPaymentIntentID pgtype.Text        `json:"provider_payment_intent_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
}

type OrderItem struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	CourseID    uuid.UUID `json:"course_id"`
	CourseTitle string    `json:"course_title"`
	AmountMinor int64     `json:"amount_minor"`
	Currency    string    `json:"currency"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMembership struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Status         string             `json:"status"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID               uuid.UUID          `json:"id"`
	AggregateType    string             `json:"aggregate_type"`
	AggregateID      uuid.UUID          `json:"aggregate_id"`
	EventType        string             `json:"event_type"`
	Payload          []byte             `json:"payload"`
	DeduplicationKey string             `json:"deduplication_key"`
	Status           string             `json:"status"`
	Attempts         int32              `json:"attempts"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	LastError        pgtype.Text        `json:"last_error"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DeadLetteredAt   pgtype.Timestamptz `json:"dead_lettered_at"`
	ClaimedAt        pgtype.Timestamptz `json:"claimed_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PaymentTransaction struct {
	ID                    uuid.UUID          `json:"id"`
	OrderID               uuid.UUID          `json:"order_id"`
	Provider              string             `json:"provider"`
	ProviderTransactionID string             `json:"provider_transaction_id"`
	Kind                  string             `json:"kind"`
	Status                string             `json:"status"`
	AmountMinor           int64              `json:"amount_minor"`
	Currency              string             `json:"currency"`
	FailureCode           pgtype.Text        `json:"failure_code"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type PaymentWebhookEvent struct {
	ID              uuid.UUID          `json:"id"`
	Provider        string             `json:"provider"`
	ProviderEventID string             `json:"provider_event_id"`
	EventType       string             `json:"event_type"`
	Payload         []byte             `json:"payload"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Quiz struct {
	ID                 uuid.UUID          `json:"id"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	CourseID           uuid.UUID          `json:"course_id"`
	LessonID           uuid.NullUUID      `json:"lesson_id"`
	Title              string             `json:"title"`
	Instructions       string             `json:"instructions"`
	Status             string             `json:"status"`
	TimeLimitSeconds   pgtype.Int4        `json:"time_limit_seconds"`
	AttemptLimit       int32              `json:"attempt_limit"`
	PassPercentage     pgtype.Numeric     `json:"pass_percentage"`
	RandomizeQuestions bool               `json:"randomize_questions"`
	RandomizeOptions   bool               `json:"randomize_options"`
	AvailableFrom      pgtype.Timestamptz `json:"available_from"`
	AvailableUntil     pgtype.Timestamptz `json:"available_until"`
	ResultsVisibility  string             `json:"results_visibility"`
	IsRequired         bool               `json:"is_required"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type QuizAnswer struct {
	ID                uuid.UUID          `json:"id"`
	AttemptID         uuid.UUID          `json:"attempt_id"`
	QuestionID        uuid.UUID          `json:"question_id"`
	SelectedOptionIds []uuid.UUID        `json:"selected_option_ids"`
	TextAnswer        pgtype.Text        `json:"text_answer"`
	AwardedPoints     pgtype.Numeric     `json:"awarded_points"`
	IsCorrect         pgtype.Bool        `json:"is_correct"`
	GraderFeedback    pgtype.Text        `json:"grader_feedback"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type QuizAttempt struct {
	ID               uuid.UUID          `json:"id"`
	QuizID           uuid.UUID          `json:"quiz_id"`
	EnrollmentID     uuid.UUID          `json:"enrollment_id"`
	StudentID        uuid.UUID          `json:"student_id"`
	AttemptNumber    int32              `json:"attempt_number"`
	Status           string             `json:"status"`
	QuestionSnapshot []byte             `json:"question_snapshot"`
	QuestionOrder    []uuid.UUID        `json:"question_order"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	SubmittedAt      pgtype.Timestamptz `json:"submitted_at"`
	GradedAt         pgtype.Timestamptz `json:"graded_at"`
	ScorePoints      pgtype.Numeric     `json:"score_points"`
	MaxPoints        pgtype.Numeric     `json:"max_points"`
	Percentage       pgtype.Numeric     `json:"percentage"`
	Passed           pgtype.Bool        `json:"passed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type QuizQuestion struct {
	ID           uuid.UUID          `json:"id"`
	QuizID       uuid.UUID          `json:"quiz_id"`
	QuestionType string             `json:"question_type"`
	Prompt       string             `json:"prompt"`
	Points       pgtype.Numeric     `json:"points"`
	Position     int32              `json:"position"`
	Explanation  string             `json:"explanation"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type QuizQuestionOption struct {
	ID         uuid.UUID          `json:"id"`
	QuestionID uuid.UUID          `json:"question_id"`
	Text       string             `json:"text"`
	IsCorrect  bool               `json:"is_correct"`
	Position   int32              `json:"position"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RefreshSession struct {
	ID              uuid.UUID          `json:"id"`
	FamilyID        uuid.UUID          `json:"family_id"`
	ParentID        uuid.NullUUID      `json:"parent_id"`
	UserID          uuid.UUID          `json:"user_id"`
	TokenHash       []byte             `json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	RotatedAt       pgtype.Timestamptz `json:"rotated_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	ReuseDetectedAt pgtype.Timestamptz `json:"reuse_detected_at"`
	IpAddress       *netip.Addr        `json:"ip_address"`
	UserAgent       string             `json:"user_agent"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Refund struct {
	ID                   uuid.UUID          `json:"id"`
	OrderID              uuid.UUID          `json:"order_id"`
	PaymentTransactionID uuid.UUID          `json:"payment_transaction_id"`
	ProviderRefundID     string             `json:"provider_refund_id"`
	AmountMinor          int64              `json:"amount_minor"`
	Currency             string             `json:"currency"`
	Status               string             `json:"status"`
	Reason               pgtype.Text        `json:"reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type StudentProfile struct {
	UserID    uuid.UUID          `json:"user_id"`
	Headline  string             `json:"headline"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TeacherProfile struct {
	UserID    uuid.UUID          `json:"user_id"`
	Biography string             `json:"biography"`
	Expertise []string           `json:"expertise"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UploadIntent struct {
	ID                     uuid.UUID          `json:"id"`
	MediaAssetID           uuid.UUID          `json:"media_asset_id"`
	OwnerUserID            uuid.UUID          `json:"owner_user_id"`
	ExpectedSizeBytes      int64              `json:"expected_size_bytes"`
	ExpectedContentType    string             `json:"expected_content_type"`
	ExpectedChecksumSha256 pgtype.Text        `json:"expected_checksum_sha256"`
	Status                 string             `json:"status"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	FirebaseUid      string             `json:"firebase_uid"`
	Email            string             `json:"email"`
	DisplayName      string             `json:"display_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
	PasswordHash     string             `json:"password_hash"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	FailedLoginCount int32              `json:"failed_login_count"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
}

type UserInvitation struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Email          string             `json:"email"`
	RoleID         uuid.UUID          `json:"role_id"`
	TokenHash      string             `json:"token_hash"`
	Status         string             `json:"status"`
	InvitedBy      uuid.UUID          `json:"invited_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UserProfile struct {
	UserID    uuid.UUID          `json:"user_id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Phone     pgtype.Text        `json:"phone"`
	Timezone  string             `json:"timezone"`
	Locale    string             `json:"locale"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID     uuid.UUID          `json:"user_id"`
	RoleID     uuid.UUID          `json:"role_id"`
	AssignedBy uuid.NullUUID      `json:"assigned_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
