// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH claimed AS (
 SELECT id FROM outbox_events WHERE status IN ('pending','failed') AND next_attempt_at<=now()
 ORDER BY next_attempt_at,id FOR UPDATE SKIP LOCKED LIMIT $1
)
UPDATE outbox_events o SET status='processing',attempts=attempts+1
FROM claimed WHERE o.id=claimed.id RETURNING o.id, o.aggregate_type, o.aggregate_id, o.event_type, o.payload, o.deduplication_key, o.status, o.attempts, o.next_attempt_at, o.published_at, o.last_error, o.created_at
`

func (q *Queries) ClaimOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.DeduplicationKey,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.PublishedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id,user_id,organization_id,type,title,body,data,deduplication_key)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT(user_id,deduplication_key) WHERE deduplication_key IS NOT NULL DO UPDATE SET title=EXCLUDED.title RETURNING id, user_id, organization_id, type, title, body, data, deduplication_key, read_at, created_at
`

type CreateNotificationParams struct {
	ID               uuid.UUID     `json:"id"`
	UserID           uuid.UUID     `json:"user_id"`
	OrganizationID   uuid.NullUUID `json:"organization_id"`
	Type             string        `json:"type"`
	Title            string        `json:"title"`
	Body             string        `json:"body"`
	Data             []byte        `json:"data"`
	DeduplicationKey pgtype.Text   `json:"deduplication_key"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.OrganizationID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.DeduplicationKey,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.DeduplicationKey,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one
INSERT INTO notification_deliveries (id,notification_id,device_token_id,status,next_attempt_at)
VALUES ($1,$2,$3,'pending',now()) ON CONFLICT(notification_id,device_token_id) DO UPDATE SET updated_at=now() RETURNING id, notification_id, device_token_id, status, attempts, next_attempt_at, provider_message_id, last_error, sent_at, created_at, updated_at
`

type CreateNotificationDeliveryParams struct {
	ID             uuid.UUID     `json:"id"`
	NotificationID uuid.UUID     `json:"notification_id"`
	DeviceTokenID  uuid.NullUUID `json:"device_token_id"`
}

func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, createNotificationDelivery, arg.ID, arg.NotificationID, arg.DeviceTokenID)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.DeviceTokenID,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.ProviderMessageID,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceTokenByID = `-- name: DeleteDeviceTokenByID :execrows
DELETE FROM device_tokens WHERE id=$1
`

func (q *Queries) DeleteDeviceTokenByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceTokenByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id,aggregate_type,aggregate_id,event_type,payload,deduplication_key)
VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT(deduplication_key) DO NOTHING
`

type InsertOutboxEventParams struct {
	ID               uuid.UUID `json:"id"`
	AggregateType    string    `json:"aggregate_type"`
	AggregateID      uuid.UUID `json:"aggregate_id"`
	EventType        string    `json:"event_type"`
	Payload          []byte    `json:"payload"`
	DeduplicationKey string    `json:"deduplication_key"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.DeduplicationKey,
	)
	return err
}

const listDueAssignmentReminders = `-- name: ListDueAssignmentReminders :many
SELECT a.id AS assignment_id,a.organization_id,e.student_id AS user_id,a.title,a.due_at
FROM assignments a JOIN enrollments e ON e.course_id=a.course_id AND e.status='active'
WHERE a.status='published' AND a.due_at>now() AND a.due_at<=now()+interval '24 hours'
ORDER BY a.due_at,a.id,e.student_id LIMIT $1
`

type ListDueAssignmentRemindersRow struct {
	AssignmentID   uuid.UUID          `json:"assignment_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Title          string             `json:"title"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) ListDueAssignmentReminders(ctx context.Context, limit int32) ([]ListDueAssignmentRemindersRow, error) {
	rows, err := q.db.Query(ctx, listDueAssignmentReminders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueAssignmentRemindersRow{}
	for rows.Next() {
		var i ListDueAssignmentRemindersRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.OrganizationID,
			&i.UserID,
			&i.Title,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueLiveReminders = `-- name: ListDueLiveReminders :many
SELECT l.id AS live_session_id,l.organization_id,e.student_id AS user_id,l.title,l.scheduled_start_at
FROM live_sessions l JOIN enrollments e ON e.course_id=l.course_id AND e.status='active'
WHERE l.status='scheduled' AND l.scheduled_start_at>now() AND l.scheduled_start_at<=now()+interval '15 minutes'
ORDER BY l.scheduled_start_at,l.id,e.student_id LIMIT $1
`

type ListDueLiveRemindersRow struct {
	LiveSessionID    uuid.UUID          `json:"live_session_id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	UserID           uuid.UUID          `json:"user_id"`
	Title            string             `json:"title"`
	ScheduledStartAt pgtype.Timestamptz `json:"scheduled_start_at"`
}

func (q *Queries) ListDueLiveReminders(ctx context.Context, limit int32) ([]ListDueLiveRemindersRow, error) {
	rows, err := q.db.Query(ctx, listDueLiveReminders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueLiveRemindersRow{}
	for rows.Next() {
		var i ListDueLiveRemindersRow
		if err := rows.Scan(
			&i.LiveSessionID,
			&i.OrganizationID,
			&i.UserID,
			&i.Title,
			&i.ScheduledStartAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, organization_id, type, title, body, data, deduplication_key, read_at, created_at FROM notifications WHERE user_id=$1
 AND ($2::timestamptz IS NULL OR (created_at,id)<($2,$3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $4
`

type ListNotificationsParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.DeduplicationKey,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationStudentIDs = `-- name: ListOrganizationStudentIDs :many
SELECT DISTINCT m.user_id FROM organization_memberships m JOIN membership_roles mr ON mr.membership_id=m.id JOIN roles r ON r.id=mr.role_id
WHERE m.organization_id=$1 AND m.status='active' AND r.code='student' ORDER BY m.user_id
`

func (q *Queries) ListOrganizationStudentIDs(ctx context.Context, organizationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOrganizationStudentIDs, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDeviceTokens = `-- name: ListUserDeviceTokens :many
SELECT id, user_id, token_hash, encrypted_token, platform, last_seen_at, created_at FROM device_tokens WHERE user_id=$1 ORDER BY last_seen_at DESC,id
`

func (q *Queries) ListUserDeviceTokens(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listUserDeviceTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.EncryptedToken,
			&i.Platform,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read_at=now() WHERE user_id=$1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND user_id=$2 RETURNING id, user_id, organization_id, type, title, body, data, deduplication_key, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.DeduplicationKey,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const notificationUnreadCount = `-- name: NotificationUnreadCount :one
SELECT count(*) FROM notifications WHERE user_id=$1 AND read_at IS NULL
`

func (q *Queries) NotificationUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, notificationUnreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const registerDeviceToken = `-- name: RegisterDeviceToken :one
INSERT INTO device_tokens (id,user_id,token_hash,encrypted_token,platform,last_seen_at)
VALUES ($1,$2,$3,$4,$5,now()) ON CONFLICT(token_hash) DO UPDATE SET user_id=EXCLUDED.user_id,encrypted_token=EXCLUDED.encrypted_token,platform=EXCLUDED.platform,last_seen_at=now() RETURNING id, user_id, token_hash, encrypted_token, platform, last_seen_at, created_at
`

type RegisterDeviceTokenParams struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	TokenHash      string    `json:"token_hash"`
	EncryptedToken string    `json:"encrypted_token"`
	Platform       string    `json:"platform"`
}

func (q *Queries) RegisterDeviceToken(ctx context.Context, arg RegisterDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, registerDeviceToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.EncryptedToken,
		arg.Platform,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.EncryptedToken,
		&i.Platform,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const removeDeviceToken = `-- name: RemoveDeviceToken :execrows
DELETE FROM device_tokens WHERE id=$1 AND user_id=$2
`

type RemoveDeviceTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveDeviceToken(ctx context.Context, arg RemoveDeviceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeDeviceToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNotificationDeliveryResult = `-- name: SetNotificationDeliveryResult :one
UPDATE notification_deliveries SET status=$2,attempts=attempts+1,next_attempt_at=$3,provider_message_id=$4,last_error=$5,sent_at=CASE WHEN $2='sent' THEN now() ELSE sent_at END,updated_at=now() WHERE id=$1 RETURNING id, notification_id, device_token_id, status, attempts, next_attempt_at, provider_message_id, last_error, sent_at, created_at, updated_at
`

type SetNotificationDeliveryResultParams struct {
	ID                uuid.UUID          `json:"id"`
	Status            string             `json:"status"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	LastError         pgtype.Text        `json:"last_error"`
}

func (q *Queries) SetNotificationDeliveryResult(ctx context.Context, arg SetNotificationDeliveryResultParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, setNotificationDeliveryResult,
		arg.ID,
		arg.Status,
		arg.NextAttemptAt,
		arg.ProviderMessageID,
		arg.LastError,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.DeviceTokenID,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.ProviderMessageID,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOutboxFailed = `-- name: SetOutboxFailed :one
UPDATE outbox_events SET status='failed',next_attempt_at=$2,last_error=$3 WHERE id=$1 RETURNING id, aggregate_type, aggregate_id, event_type, payload, deduplication_key, status, attempts, next_attempt_at, published_at, last_error, created_at
`

type SetOutboxFailedParams struct {
	ID            uuid.UUID          `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
}

func (q *Queries) SetOutboxFailed(ctx context.Context, arg SetOutboxFailedParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, setOutboxFailed, arg.ID, arg.NextAttemptAt, arg.LastError)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.DeduplicationKey,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.PublishedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const setOutboxPublished = `-- name: SetOutboxPublished :one
UPDATE outbox_events SET status='published',published_at=now(),last_error=NULL WHERE id=$1 RETURNING id, aggregate_type, aggregate_id, event_type, payload, deduplication_key, status, attempts, next_attempt_at, published_at, last_error, created_at
`

func (q *Queries) SetOutboxPublished(ctx context.Context, id uuid.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, setOutboxPublished, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.DeduplicationKey,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.PublishedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}
