// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE user_invitations SET status = 'accepted', accepted_at = now()
WHERE id = $1 AND status = 'pending' RETURNING id, organization_id, email, role_id, token_hash, status, invited_by, expires_at, accepted_at, created_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, id)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.TokenHash,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const assignMembershipRole = `-- name: AssignMembershipRole :exec
INSERT INTO membership_roles (membership_id, role_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AssignMembershipRoleParams struct {
	MembershipID uuid.UUID `json:"membership_id"`
	RoleID       uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignMembershipRole(ctx context.Context, arg AssignMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, assignMembershipRole, arg.MembershipID, arg.RoleID)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO user_invitations (id, organization_id, email, role_id, token_hash, invited_by, expires_at)
VALUES ($1, $2, lower($3), $4, $5, $6, $7) RETURNING id, organization_id, email, role_id, token_hash, status, invited_by, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Email          string             `json:"email"`
	RoleID         uuid.UUID          `json:"role_id"`
	TokenHash      string             `json:"token_hash"`
	InvitedBy      uuid.UUID          `json:"invited_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.RoleID,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.TokenHash,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO organization_memberships (id, organization_id, user_id, status, joined_at)
VALUES ($1, $2, $3, $4, CASE WHEN $4 = 'active' THEN now() ELSE NULL END)
ON CONFLICT (organization_id, user_id) DO UPDATE SET status = EXCLUDED.status, updated_at = now()
RETURNING id, organization_id, user_id, status, joined_at, created_at, updated_at
`

type CreateMembershipParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Status         string    `json:"status"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Status,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug) VALUES ($1, $2, $3) RETURNING id, name, slug, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembershipRoles = `-- name: DeleteMembershipRoles :exec
DELETE FROM membership_roles WHERE membership_id=$1
`

func (q *Queries) DeleteMembershipRoles(ctx context.Context, membershipID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembershipRoles, membershipID)
	return err
}

const getInvitationByTokenHashForUpdate = `-- name: GetInvitationByTokenHashForUpdate :one
SELECT id, organization_id, email, role_id, token_hash, status, invited_by, expires_at, accepted_at, created_at FROM user_invitations WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetInvitationByTokenHashForUpdate(ctx context.Context, tokenHash string) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHashForUpdate, tokenHash)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.RoleID,
		&i.TokenHash,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipForUpdate = `-- name: GetMembershipForUpdate :one
SELECT id, organization_id, user_id, status, joined_at, created_at, updated_at FROM organization_memberships WHERE id=$1 AND organization_id=$2 FOR UPDATE
`

type GetMembershipForUpdateParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetMembershipForUpdate(ctx context.Context, arg GetMembershipForUpdateParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipForUpdate, arg.ID, arg.OrganizationID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, status, created_at, updated_at FROM organizations WHERE id = $1 AND status <> 'deleted'
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name, created_at FROM roles WHERE code = $1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipRoleCodes = `-- name: ListMembershipRoleCodes :many
SELECT r.code FROM membership_roles mr JOIN roles r ON r.id=mr.role_id WHERE mr.membership_id=$1 ORDER BY r.code
`

func (q *Queries) ListMembershipRoleCodes(ctx context.Context, membershipID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listMembershipRoleCodes, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT u.id, u.email, u.display_name, u.status AS user_status, m.id AS membership_id, m.status AS membership_status,
       COALESCE(array_agg(r.code ORDER BY r.code) FILTER (WHERE r.code IS NOT NULL), '{}')::text[] AS roles,
       m.created_at
FROM organization_memberships m
JOIN users u ON u.id = m.user_id
LEFT JOIN membership_roles mr ON mr.membership_id = m.id
LEFT JOIN roles r ON r.id = mr.role_id
WHERE m.organization_id = $1
  AND ($2::timestamptz IS NULL OR (m.created_at, m.id) < ($2, $3::uuid))
GROUP BY u.id, m.id ORDER BY m.created_at DESC, m.id DESC LIMIT $4
`

type ListOrganizationMembersParams struct {
	OrganizationID  uuid.UUID          `json:"organization_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListOrganizationMembersRow struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	DisplayName      string             `json:"display_name"`
	UserStatus       string             `json:"user_status"`
	MembershipID     uuid.UUID          `json:"membership_id"`
	MembershipStatus string             `json:"membership_status"`
	Roles            []string           `json:"roles"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, arg ListOrganizationMembersParams) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.UserStatus,
			&i.MembershipID,
			&i.MembershipStatus,
			&i.Roles,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, status, created_at, updated_at FROM organizations
WHERE status <> 'deleted'
  AND ($1::timestamptz IS NULL OR (created_at, id) < ($1, $2::uuid))
ORDER BY created_at DESC, id DESC LIMIT $3
`

type ListOrganizationsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.CursorCreatedAt, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMembershipStatus = `-- name: SetMembershipStatus :one
UPDATE organization_memberships SET status=$1,joined_at=CASE WHEN $1::text='active' THEN COALESCE(joined_at,now()) ELSE joined_at END,updated_at=now()
WHERE id=$2 AND organization_id=$3 RETURNING id, organization_id, user_id, status, joined_at, created_at, updated_at
`

type SetMembershipStatusParams struct {
	Status         string    `json:"status"`
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) SetMembershipStatus(ctx context.Context, arg SetMembershipStatusParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, setMembershipStatus, arg.Status, arg.ID, arg.OrganizationID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations SET name = $2, slug = $3, updated_at = now()
WHERE id = $1 AND status <> 'deleted' RETURNING id, name, slug, status, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
