// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id,organization_id,user_id,status,amount_minor,currency,idempotency_key)
VALUES ($1,$2,$3,'pending',$4,$5,$6) ON CONFLICT(user_id,idempotency_key) DO NOTHING RETURNING id, organization_id, user_id, status, amount_minor, currency, idempotency_key, provider_payment_intent_id, created_at, updated_at, paid_at
`

type CreateOrderParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	AmountMinor    int64     `json:"amount_minor"`
	Currency       string    `json:"currency"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.AmountMinor,
		arg.Currency,
		arg.IdempotencyKey,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderPaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id,order_id,course_id,course_title,amount_minor,currency) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, order_id, course_id, course_title, amount_minor, currency
`

type CreateOrderItemParams struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	CourseID    uuid.UUID `json:"course_id"`
	CourseTitle string    `json:"course_title"`
	AmountMinor int64     `json:"amount_minor"`
	Currency    string    `json:"currency"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.CourseID,
		arg.CourseTitle,
		arg.AmountMinor,
		arg.Currency,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CourseID,
		&i.CourseTitle,
		&i.AmountMinor,
		&i.Currency,
	)
	return i, err
}

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (id,order_id,provider,provider_transaction_id,kind,status,amount_minor,currency,failure_code)
VALUES ($1,$2,'dummy',$3,$4,$5,$6,$7,$8)
ON CONFLICT(provider_transaction_id) DO UPDATE SET updated_at=now() RETURNING id, order_id, provider, provider_transaction_id, kind, status, amount_minor, currency, failure_code, created_at, updated_at
`

type CreatePaymentTransactionParams struct {
	ID                    uuid.UUID   `json:"id"`
	OrderID               uuid.UUID   `json:"order_id"`
	ProviderTransactionID string      `json:"provider_transaction_id"`
	Kind                  string      `json:"kind"`
	Status                string      `json:"status"`
	AmountMinor           int64       `json:"amount_minor"`
	Currency              string      `json:"currency"`
	FailureCode           pgtype.Text `json:"failure_code"`
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, createPaymentTransaction,
		arg.ID,
		arg.OrderID,
		arg.ProviderTransactionID,
		arg.Kind,
		arg.Status,
		arg.AmountMinor,
		arg.Currency,
		arg.FailureCode,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.Kind,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentWebhookEvent = `-- name: CreatePaymentWebhookEvent :execrows
INSERT INTO payment_webhook_events (id,provider,provider_event_id,event_type,payload,processed_at) VALUES ($1,'dummy',$2,$3,$4,now()) ON CONFLICT(provider,provider_event_id) DO NOTHING
`

type CreatePaymentWebhookEventParams struct {
	ID              uuid.UUID `json:"id"`
	ProviderEventID string    `json:"provider_event_id"`
	EventType       string    `json:"event_type"`
	Payload         []byte    `json:"payload"`
}

func (q *Queries) CreatePaymentWebhookEvent(ctx context.Context, arg CreatePaymentWebhookEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPaymentWebhookEvent,
		arg.ID,
		arg.ProviderEventID,
		arg.EventType,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO refunds (id,order_id,payment_transaction_id,provider_refund_id,amount_minor,currency,status,reason)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(provider_refund_id) DO UPDATE SET updated_at=now() RETURNING id, order_id, payment_transaction_id, provider_refund_id, amount_minor, currency, status, reason, created_at, updated_at
`

type CreateRefundParams struct {
	ID                   uuid.UUID   `json:"id"`
	OrderID              uuid.UUID   `json:"order_id"`
	PaymentTransactionID uuid.UUID   `json:"payment_transaction_id"`
	ProviderRefundID     string      `json:"provider_refund_id"`
	AmountMinor          int64       `json:"amount_minor"`
	Currency             string      `json:"currency"`
	Status               string      `json:"status"`
	Reason               pgtype.Text `json:"reason"`
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.ID,
		arg.OrderID,
		arg.PaymentTransactionID,
		arg.ProviderRefundID,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.Reason,
	)
	var i Refund
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentTransactionID,
		&i.ProviderRefundID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, organization_id, user_id, status, amount_minor, currency, idempotency_key, provider_payment_intent_id, created_at, updated_at, paid_at FROM orders WHERE id=$1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderPaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getOrderByPaymentIntentForUpdate = `-- name: GetOrderByPaymentIntentForUpdate :one
SELECT id, organization_id, user_id, status, amount_minor, currency, idempotency_key, provider_payment_intent_id, created_at, updated_at, paid_at FROM orders WHERE provider_payment_intent_id=$1 FOR UPDATE
`

func (q *Queries) GetOrderByPaymentIntentForUpdate(ctx context.Context, providerPaymentIntentID pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByPaymentIntentForUpdate, providerPaymentIntentID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderPaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getOrderByUserIdempotency = `-- name: GetOrderByUserIdempotency :one
SELECT o.id, o.organization_id, o.user_id, o.status, o.amount_minor, o.currency, o.idempotency_key, o.provider_payment_intent_id, o.created_at, o.updated_at, o.paid_at,oi.course_id FROM orders o JOIN order_items oi ON oi.order_id=o.id WHERE o.user_id=$1 AND o.idempotency_key=$2
`

type GetOrderByUserIdempotencyParams struct {
	UserID         uuid.UUID `json:"user_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

type GetOrderByUserIdempotencyRow struct {
	ID                      uuid.UUID          `json:"id"`
	OrganizationID          uuid.UUID          `json:"organization_id"`
	UserID                  uuid.UUID          `json:"user_id"`
	Status                  string             `json:"status"`
	AmountMinor             int64              `json:"amount_minor"`
	Currency                string             `json:"currency"`
	IdempotencyKey          string             `json:"idempotency_key"`
	ProviderPaymentIntentID pgtype.Text        `json:"provider_payment_intent_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
	CourseID                uuid.UUID          `json:"course_id"`
}

func (q *Queries) GetOrderByUserIdempotency(ctx context.Context, arg GetOrderByUserIdempotencyParams) (GetOrderByUserIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getOrderByUserIdempotency, arg.UserID, arg.IdempotencyKey)
	var i GetOrderByUserIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderPaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
		&i.CourseID,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, organization_id, user_id, status, amount_minor, currency, idempotency_key, provider_payment_intent_id, created_at, updated_at, paid_at FROM orders WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderPaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getSuccessfulPaymentForOrder = `-- name: GetSuccessfulPaymentForOrder :one
SELECT id, order_id, provider, provider_transaction_id, kind, status, amount_minor, currency, failure_code, created_at, updated_at FROM payment_transactions WHERE order_id=$1 AND kind='payment' AND status='succeeded' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetSuccessfulPaymentForOrder(ctx context.Context, orderID uuid.UUID) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getSuccessfulPaymentForOrder, orderID)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.Kind,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminPaymentOrders = `-- name: ListAdminPaymentOrders :many
SELECT o.id, o.organization_id, o.user_id, o.status, o.amount_minor, o.currency, o.idempotency_key, o.provider_payment_intent_id, o.created_at, o.updated_at, o.paid_at, u.email, u.display_name
FROM orders o JOIN users u ON u.id=o.user_id
WHERE o.organization_id=$1
  AND ($2::text IS NULL OR o.status=$2)
  AND ($3::timestamptz IS NULL OR o.created_at>=$3)
  AND ($4::timestamptz IS NULL OR o.created_at<$4)
  AND ($5::timestamptz IS NULL OR (o.created_at,o.id)<($5,$6::uuid))
ORDER BY o.created_at DESC,o.id DESC LIMIT $7
`

type ListAdminPaymentOrdersParams struct {
	OrganizationID  uuid.UUID          `json:"organization_id"`
	Status          pgtype.Text        `json:"status"`
	FromTime        pgtype.Timestamptz `json:"from_time"`
	ToTime          pgtype.Timestamptz `json:"to_time"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListAdminPaymentOrdersRow struct {
	ID                      uuid.UUID          `json:"id"`
	OrganizationID          uuid.UUID          `json:"organization_id"`
	UserID                  uuid.UUID          `json:"user_id"`
	Status                  string             `json:"status"`
	AmountMinor             int64              `json:"amount_minor"`
	Currency                string             `json:"currency"`
	IdempotencyKey          string             `json:"idempotency_key"`
	ProviderPaymentIntentID pgtype.Text        `json:"provider_payment_intent_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
	Email                   string             `json:"email"`
	DisplayName             string             `json:"display_name"`
}

func (q *Queries) ListAdminPaymentOrders(ctx context.Context, arg ListAdminPaymentOrdersParams) ([]ListAdminPaymentOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAdminPaymentOrders,
		arg.OrganizationID,
		arg.Status,
		arg.FromTime,
		arg.ToTime,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminPaymentOrdersRow{}
	for rows.Next() {
		var i ListAdminPaymentOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.IdempotencyKey,
			&i.ProviderPaymentIntentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT id, organization_id, user_id, status, amount_minor, currency, idempotency_key, provider_payment_intent_id, created_at, updated_at, paid_at FROM orders WHERE user_id=$1
 AND ($2::timestamptz IS NULL OR (created_at,id)<($2,$3::uuid))
ORDER BY created_at DESC,id DESC LIMIT $4
`

type ListUserOrdersParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listUserOrders,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.IdempotencyKey,
			&i.ProviderPaymentIntentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPayments = `-- name: ListUserPayments :many
SELECT p.id, p.order_id, p.provider, p.provider_transaction_id, p.kind, p.status, p.amount_minor, p.currency, p.failure_code, p.created_at, p.updated_at FROM payment_transactions p JOIN orders o ON o.id=p.order_id WHERE o.user_id=$1
 AND ($2::timestamptz IS NULL OR (p.created_at,p.id)<($2,$3::uuid))
ORDER BY p.created_at DESC,p.id DESC LIMIT $4
`

type ListUserPaymentsParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListUserPayments(ctx context.Context, arg ListUserPaymentsParams) ([]PaymentTransaction, error) {
	rows, err := q.db.Query(ctx, listUserPayments,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentTransaction{}
	for rows.Next() {
		var i PaymentTransaction
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Provider,
			&i.ProviderTransactionID,
			&i.Kind,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.FailureCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderPaymentIntent = `-- name: SetOrderPaymentIntent :one
UPDATE orders SET provider_payment_intent_id=$2,status='processing',updated_at=now() WHERE id=$1 AND status IN ('pending','processing') RETURNING id, organization_id, user_id, status, amount_minor, currency, idempotency_key, provider_payment_intent_id, created_at, updated_at, paid_at
`

type SetOrderPaymentIntentParams struct {
	ID                      uuid.UUID   `json:"id"`
	ProviderPaymentIntentID pgtype.Text `json:"provider_payment_intent_id"`
}

func (q *Queries) SetOrderPaymentIntent(ctx context.Context, arg SetOrderPaymentIntentParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderPaymentIntent, arg.ID, arg.ProviderPaymentIntentID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderPaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const setOrderStatus = `-- name: SetOrderStatus :one
UPDATE orders SET status=$2,paid_at=CASE WHEN $2='paid' THEN COALESCE(paid_at,now()) ELSE paid_at END,updated_at=now() WHERE id=$1 RETURNING id, organization_id, user_id, status, amount_minor, currency, idempotency_key, provider_payment_intent_id, created_at, updated_at, paid_at
`

type SetOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.ProviderPaymentIntentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const sumSucceededRefunds = `-- name: SumSucceededRefunds :one
SELECT COALESCE(sum(amount_minor),0)::bigint FROM refunds WHERE order_id=$1 AND status='succeeded'
`

func (q *Queries) SumSucceededRefunds(ctx context.Context, orderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumSucceededRefunds, orderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
