// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (id,organization_id,course_id,lesson_id,title,instructions,time_limit_seconds,attempt_limit,pass_percentage,randomize_questions,randomize_options,available_from,available_until,results_visibility,is_required)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id, organization_id, course_id, lesson_id, title, instructions, status, time_limit_seconds, attempt_limit, pass_percentage, randomize_questions, randomize_options, available_from, available_until, results_visibility, is_required, created_at, updated_at
`

type CreateQuizParams struct {
	ID                 uuid.UUID          `json:"id"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	CourseID           uuid.UUID          `json:"course_id"`
	LessonID           uuid.NullUUID      `json:"lesson_id"`
	Title              string             `json:"title"`
	Instructions       string             `json:"instructions"`
	TimeLimitSeconds   pgtype.Int4        `json:"time_limit_seconds"`
	AttemptLimit       int32              `json:"attempt_limit"`
	PassPercentage     pgtype.Numeric     `json:"pass_percentage"`
	RandomizeQuestions bool               `json:"randomize_questions"`
	RandomizeOptions   bool               `json:"randomize_options"`
	AvailableFrom      pgtype.Timestamptz `json:"available_from"`
	AvailableUntil     pgtype.Timestamptz `json:"available_until"`
	ResultsVisibility  string             `json:"results_visibility"`
	IsRequired         bool               `json:"is_required"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.ID,
		arg.OrganizationID,
		arg.CourseID,
		arg.LessonID,
		arg.Title,
		arg.Instructions,
		arg.TimeLimitSeconds,
		arg.AttemptLimit,
		arg.PassPercentage,
		arg.RandomizeQuestions,
		arg.RandomizeOptions,
		arg.AvailableFrom,
		arg.AvailableUntil,
		arg.ResultsVisibility,
		arg.IsRequired,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Status,
		&i.TimeLimitSeconds,
		&i.AttemptLimit,
		&i.PassPercentage,
		&i.RandomizeQuestions,
		&i.RandomizeOptions,
		&i.AvailableFrom,
		&i.AvailableUntil,
		&i.ResultsVisibility,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuizAttempt = `-- name: CreateQuizAttempt :one
INSERT INTO quiz_attempts (id,quiz_id,enrollment_id,student_id,attempt_number,question_snapshot,question_order,started_at,expires_at,max_points)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, quiz_id, enrollment_id, student_id, attempt_number, status, question_snapshot, question_order, started_at, expires_at, submitted_at, graded_at, score_points, max_points, percentage, passed, created_at, updated_at
`

type CreateQuizAttemptParams struct {
	ID               uuid.UUID          `json:"id"`
	QuizID           uuid.UUID          `json:"quiz_id"`
	EnrollmentID     uuid.UUID          `json:"enrollment_id"`
	StudentID        uuid.UUID          `json:"student_id"`
	AttemptNumber    int32              `json:"attempt_number"`
	QuestionSnapshot []byte             `json:"question_snapshot"`
	QuestionOrder    []uuid.UUID        `json:"question_order"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	MaxPoints        pgtype.Numeric     `json:"max_points"`
}

func (q *Queries) CreateQuizAttempt(ctx context.Context, arg CreateQuizAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, createQuizAttempt,
		arg.ID,
		arg.QuizID,
		arg.EnrollmentID,
		arg.StudentID,
		arg.AttemptNumber,
		arg.QuestionSnapshot,
		arg.QuestionOrder,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.MaxPoints,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.Status,
		&i.QuestionSnapshot,
		&i.QuestionOrder,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.ScorePoints,
		&i.MaxPoints,
		&i.Percentage,
		&i.Passed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuizOption = `-- name: CreateQuizOption :one
INSERT INTO quiz_question_options (id,question_id,text,is_correct,position) VALUES ($1,$2,$3,$4,$5) RETURNING id, question_id, text, is_correct, position, created_at
`

type CreateQuizOptionParams struct {
	ID         uuid.UUID `json:"id"`
	QuestionID uuid.UUID `json:"question_id"`
	Text       string    `json:"text"`
	IsCorrect  bool      `json:"is_correct"`
	Position   int32     `json:"position"`
}

func (q *Queries) CreateQuizOption(ctx context.Context, arg CreateQuizOptionParams) (QuizQuestionOption, error) {
	row := q.db.QueryRow(ctx, createQuizOption,
		arg.ID,
		arg.QuestionID,
		arg.Text,
		arg.IsCorrect,
		arg.Position,
	)
	var i QuizQuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createQuizQuestion = `-- name: CreateQuizQuestion :one
INSERT INTO quiz_questions (id,quiz_id,question_type,prompt,points,position) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, quiz_id, question_type, prompt, points, position, explanation, created_at, updated_at
`

type CreateQuizQuestionParams struct {
	ID           uuid.UUID      `json:"id"`
	QuizID       uuid.UUID      `json:"quiz_id"`
	QuestionType string         `json:"question_type"`
	Prompt       string         `json:"prompt"`
	Points       pgtype.Numeric `json:"points"`
	Position     int32          `json:"position"`
}

func (q *Queries) CreateQuizQuestion(ctx context.Context, arg CreateQuizQuestionParams) (QuizQuestion, error) {
	row := q.db.QueryRow(ctx, createQuizQuestion,
		arg.ID,
		arg.QuizID,
		arg.QuestionType,
		arg.Prompt,
		arg.Points,
		arg.Position,
	)
	var i QuizQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.QuestionType,
		&i.Prompt,
		&i.Points,
		&i.Position,
		&i.Explanation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuiz = `-- name: DeleteQuiz :execrows
DELETE FROM quizzes WHERE id=$1 AND status='draft'
`

func (q *Queries) DeleteQuiz(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuiz, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteQuizQuestion = `-- name: DeleteQuizQuestion :execrows
DELETE FROM quiz_questions q USING quizzes z WHERE q.id=$1 AND z.id=q.quiz_id AND z.status='draft'
`

func (q *Queries) DeleteQuizQuestion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuizQuestion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteQuizQuestionOptions = `-- name: DeleteQuizQuestionOptions :exec
DELETE FROM quiz_question_options WHERE question_id=$1
`

func (q *Queries) DeleteQuizQuestionOptions(ctx context.Context, questionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuizQuestionOptions, questionID)
	return err
}

const expireQuizAttempt = `-- name: ExpireQuizAttempt :one
UPDATE quiz_attempts
SET status='expired',updated_at=now()
WHERE id=$1 AND status='in_progress'
RETURNING id, quiz_id, enrollment_id, student_id, attempt_number, status, question_snapshot, question_order, started_at, expires_at, submitted_at, graded_at, score_points, max_points, percentage, passed, created_at, updated_at
`

func (q *Queries) ExpireQuizAttempt(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, expireQuizAttempt, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.Status,
		&i.QuestionSnapshot,
		&i.QuestionOrder,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.ScorePoints,
		&i.MaxPoints,
		&i.Percentage,
		&i.Passed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStudentQuizAttempts = `-- name: ExpireStudentQuizAttempts :execrows
UPDATE quiz_attempts
SET status='expired',updated_at=now()
WHERE quiz_id=$1 AND student_id=$2
  AND status='in_progress' AND expires_at IS NOT NULL
  AND expires_at<=$3
`

type ExpireStudentQuizAttemptsParams struct {
	QuizID    uuid.UUID          `json:"quiz_id"`
	StudentID uuid.UUID          `json:"student_id"`
	ExpiredAt pgtype.Timestamptz `json:"expired_at"`
}

func (q *Queries) ExpireStudentQuizAttempts(ctx context.Context, arg ExpireStudentQuizAttemptsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireStudentQuizAttempts, arg.QuizID, arg.StudentID, arg.ExpiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, organization_id, course_id, lesson_id, title, instructions, status, time_limit_seconds, attempt_limit, pass_percentage, randomize_questions, randomize_options, available_from, available_until, results_visibility, is_required, created_at, updated_at FROM quizzes WHERE id=$1
`

func (q *Queries) GetQuiz(ctx context.Context, id uuid.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Status,
		&i.TimeLimitSeconds,
		&i.AttemptLimit,
		&i.PassPercentage,
		&i.RandomizeQuestions,
		&i.RandomizeOptions,
		&i.AvailableFrom,
		&i.AvailableUntil,
		&i.ResultsVisibility,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizAnswerByQuestion = `-- name: GetQuizAnswerByQuestion :one
SELECT id, attempt_id, question_id, selected_option_ids, text_answer, awarded_points, is_correct, grader_feedback, created_at, updated_at FROM quiz_answers WHERE attempt_id=$1 AND question_id=$2
`

type GetQuizAnswerByQuestionParams struct {
	AttemptID  uuid.UUID `json:"attempt_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) GetQuizAnswerByQuestion(ctx context.Context, arg GetQuizAnswerByQuestionParams) (QuizAnswer, error) {
	row := q.db.QueryRow(ctx, getQuizAnswerByQuestion, arg.AttemptID, arg.QuestionID)
	var i QuizAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.SelectedOptionIds,
		&i.TextAnswer,
		&i.AwardedPoints,
		&i.IsCorrect,
		&i.GraderFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizAttempt = `-- name: GetQuizAttempt :one
SELECT id, quiz_id, enrollment_id, student_id, attempt_number, status, question_snapshot, question_order, started_at, expires_at, submitted_at, graded_at, score_points, max_points, percentage, passed, created_at, updated_at FROM quiz_attempts WHERE id=$1
`

func (q *Queries) GetQuizAttempt(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getQuizAttempt, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.Status,
		&i.QuestionSnapshot,
		&i.QuestionOrder,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.ScorePoints,
		&i.MaxPoints,
		&i.Percentage,
		&i.Passed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizAttemptForUpdate = `-- name: GetQuizAttemptForUpdate :one
SELECT id, quiz_id, enrollment_id, student_id, attempt_number, status, question_snapshot, question_order, started_at, expires_at, submitted_at, graded_at, score_points, max_points, percentage, passed, created_at, updated_at FROM quiz_attempts WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetQuizAttemptForUpdate(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getQuizAttemptForUpdate, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.Status,
		&i.QuestionSnapshot,
		&i.QuestionOrder,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.ScorePoints,
		&i.MaxPoints,
		&i.Percentage,
		&i.Passed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizQuestion = `-- name: GetQuizQuestion :one
SELECT id, quiz_id, question_type, prompt, points, position, explanation, created_at, updated_at FROM quiz_questions WHERE id=$1
`

func (q *Queries) GetQuizQuestion(ctx context.Context, id uuid.UUID) (QuizQuestion, error) {
	row := q.db.QueryRow(ctx, getQuizQuestion, id)
	var i QuizQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.QuestionType,
		&i.Prompt,
		&i.Points,
		&i.Position,
		&i.Explanation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const gradeQuizAnswer = `-- name: GradeQuizAnswer :one
UPDATE quiz_answers SET awarded_points=$1,is_correct=$2,grader_feedback=$3,updated_at=now() WHERE id=$4 RETURNING id, attempt_id, question_id, selected_option_ids, text_answer, awarded_points, is_correct, grader_feedback, created_at, updated_at
`

type GradeQuizAnswerParams struct {
	AwardedPoints  pgtype.Numeric `json:"awarded_points"`
	IsCorrect      pgtype.Bool    `json:"is_correct"`
	GraderFeedback pgtype.Text    `json:"grader_feedback"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) GradeQuizAnswer(ctx context.Context, arg GradeQuizAnswerParams) (QuizAnswer, error) {
	row := q.db.QueryRow(ctx, gradeQuizAnswer,
		arg.AwardedPoints,
		arg.IsCorrect,
		arg.GraderFeedback,
		arg.ID,
	)
	var i QuizAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.SelectedOptionIds,
		&i.TextAnswer,
		&i.AwardedPoints,
		&i.IsCorrect,
		&i.GraderFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourseQuizzes = `-- name: ListCourseQuizzes :many
SELECT id, organization_id, course_id, lesson_id, title, instructions, status, time_limit_seconds, attempt_limit, pass_percentage, randomize_questions, randomize_options, available_from, available_until, results_visibility, is_required, created_at, updated_at FROM quizzes WHERE course_id=$1
 AND ($2::boolean OR status='published')
 AND ($3::timestamptz IS NULL OR (created_at,id)<($3,$4::uuid))
ORDER BY created_at DESC,id DESC LIMIT $5
`

type ListCourseQuizzesParams struct {
	CourseID           uuid.UUID          `json:"course_id"`
	IncludeUnpublished bool               `json:"include_unpublished"`
	CursorCreatedAt    pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID           uuid.NullUUID      `json:"cursor_id"`
	PageSize           int32              `json:"page_size"`
}

func (q *Queries) ListCourseQuizzes(ctx context.Context, arg ListCourseQuizzesParams) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, listCourseQuizzes,
		arg.CourseID,
		arg.IncludeUnpublished,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quiz{}
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CourseID,
			&i.LessonID,
			&i.Title,
			&i.Instructions,
			&i.Status,
			&i.TimeLimitSeconds,
			&i.AttemptLimit,
			&i.PassPercentage,
			&i.RandomizeQuestions,
			&i.RandomizeOptions,
			&i.AvailableFrom,
			&i.AvailableUntil,
			&i.ResultsVisibility,
			&i.IsRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAnswers = `-- name: ListQuizAnswers :many
SELECT id, attempt_id, question_id, selected_option_ids, text_answer, awarded_points, is_correct, grader_feedback, created_at, updated_at FROM quiz_answers WHERE attempt_id=$1 ORDER BY created_at,id
`

func (q *Queries) ListQuizAnswers(ctx context.Context, attemptID uuid.UUID) ([]QuizAnswer, error) {
	rows, err := q.db.Query(ctx, listQuizAnswers, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAnswer{}
	for rows.Next() {
		var i QuizAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.SelectedOptionIds,
			&i.TextAnswer,
			&i.AwardedPoints,
			&i.IsCorrect,
			&i.GraderFeedback,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAttempts = `-- name: ListQuizAttempts :many
SELECT id, quiz_id, enrollment_id, student_id, attempt_number, status, question_snapshot, question_order, started_at, expires_at, submitted_at, graded_at, score_points, max_points, percentage, passed, created_at, updated_at FROM quiz_attempts WHERE quiz_id=$1 AND student_id=$2
 AND ($3::timestamptz IS NULL OR (created_at,id)<($3,$4::uuid))
ORDER BY created_at DESC,id DESC LIMIT $5
`

type ListQuizAttemptsParams struct {
	QuizID          uuid.UUID          `json:"quiz_id"`
	StudentID       uuid.UUID          `json:"student_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.NullUUID      `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListQuizAttempts(ctx context.Context, arg ListQuizAttemptsParams) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, listQuizAttempts,
		arg.QuizID,
		arg.StudentID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.EnrollmentID,
			&i.StudentID,
			&i.AttemptNumber,
			&i.Status,
			&i.QuestionSnapshot,
			&i.QuestionOrder,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.SubmittedAt,
			&i.GradedAt,
			&i.ScorePoints,
			&i.MaxPoints,
			&i.Percentage,
			&i.Passed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizQuestionBank = `-- name: ListQuizQuestionBank :many
SELECT q.id,q.question_type,q.prompt,q.points,q.position,q.explanation,
 o.id AS option_id,o.text AS option_text,o.is_correct,o.position AS option_position
FROM quiz_questions q LEFT JOIN quiz_question_options o ON o.question_id=q.id
WHERE q.quiz_id=$1 ORDER BY q.position,q.id,o.position,o.id
`

type ListQuizQuestionBankRow struct {
	ID             uuid.UUID      `json:"id"`
	QuestionType   string         `json:"question_type"`
	Prompt         string         `json:"prompt"`
	Points         pgtype.Numeric `json:"points"`
	Position       int32          `json:"position"`
	Explanation    string         `json:"explanation"`
	OptionID       uuid.NullUUID  `json:"option_id"`
	OptionText     pgtype.Text    `json:"option_text"`
	IsCorrect      pgtype.Bool    `json:"is_correct"`
	OptionPosition pgtype.Int4    `json:"option_position"`
}

func (q *Queries) ListQuizQuestionBank(ctx context.Context, quizID uuid.UUID) ([]ListQuizQuestionBankRow, error) {
	rows, err := q.db.Query(ctx, listQuizQuestionBank, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuizQuestionBankRow{}
	for rows.Next() {
		var i ListQuizQuestionBankRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionType,
			&i.Prompt,
			&i.Points,
			&i.Position,
			&i.Explanation,
			&i.OptionID,
			&i.OptionText,
			&i.IsCorrect,
			&i.OptionPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextQuizAttemptNumber = `-- name: NextQuizAttemptNumber :one
SELECT COALESCE(max(attempt_number),0)::integer+1 FROM quiz_attempts WHERE quiz_id=$1 AND student_id=$2
`

type NextQuizAttemptNumberParams struct {
	QuizID    uuid.UUID `json:"quiz_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) NextQuizAttemptNumber(ctx context.Context, arg NextQuizAttemptNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextQuizAttemptNumber, arg.QuizID, arg.StudentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setQuizStatus = `-- name: SetQuizStatus :one
UPDATE quizzes SET status=$2,updated_at=now() WHERE id=$1 RETURNING id, organization_id, course_id, lesson_id, title, instructions, status, time_limit_seconds, attempt_limit, pass_percentage, randomize_questions, randomize_options, available_from, available_until, results_visibility, is_required, created_at, updated_at
`

type SetQuizStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetQuizStatus(ctx context.Context, arg SetQuizStatusParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, setQuizStatus, arg.ID, arg.Status)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Status,
		&i.TimeLimitSeconds,
		&i.AttemptLimit,
		&i.PassPercentage,
		&i.RandomizeQuestions,
		&i.RandomizeOptions,
		&i.AvailableFrom,
		&i.AvailableUntil,
		&i.ResultsVisibility,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitQuizAttempt = `-- name: SubmitQuizAttempt :one
UPDATE quiz_attempts SET status=$1,submitted_at=COALESCE(submitted_at,now()),graded_at=CASE WHEN $1::text='graded' THEN now() ELSE graded_at END,score_points=$2,percentage=$3,passed=$4,updated_at=now() WHERE id=$5 RETURNING id, quiz_id, enrollment_id, student_id, attempt_number, status, question_snapshot, question_order, started_at, expires_at, submitted_at, graded_at, score_points, max_points, percentage, passed, created_at, updated_at
`

type SubmitQuizAttemptParams struct {
	Status      string         `json:"status"`
	ScorePoints pgtype.Numeric `json:"score_points"`
	Percentage  pgtype.Numeric `json:"percentage"`
	Passed      pgtype.Bool    `json:"passed"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) SubmitQuizAttempt(ctx context.Context, arg SubmitQuizAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, submitQuizAttempt,
		arg.Status,
		arg.ScorePoints,
		arg.Percentage,
		arg.Passed,
		arg.ID,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.EnrollmentID,
		&i.StudentID,
		&i.AttemptNumber,
		&i.Status,
		&i.QuestionSnapshot,
		&i.QuestionOrder,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.SubmittedAt,
		&i.GradedAt,
		&i.ScorePoints,
		&i.MaxPoints,
		&i.Percentage,
		&i.Passed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes SET title=$1,instructions=$2,time_limit_seconds=$3,attempt_limit=$4,pass_percentage=$5,randomize_questions=$6,randomize_options=$7,available_from=$8,available_until=$9,results_visibility=$10,is_required=$11,updated_at=now() WHERE id=$12 RETURNING id, organization_id, course_id, lesson_id, title, instructions, status, time_limit_seconds, attempt_limit, pass_percentage, randomize_questions, randomize_options, available_from, available_until, results_visibility, is_required, created_at, updated_at
`

type UpdateQuizParams struct {
	Title              string             `json:"title"`
	Instructions       string             `json:"instructions"`
	TimeLimitSeconds   pgtype.Int4        `json:"time_limit_seconds"`
	AttemptLimit       int32              `json:"attempt_limit"`
	PassPercentage     pgtype.Numeric     `json:"pass_percentage"`
	RandomizeQuestions bool               `json:"randomize_questions"`
	RandomizeOptions   bool               `json:"randomize_options"`
	AvailableFrom      pgtype.Timestamptz `json:"available_from"`
	AvailableUntil     pgtype.Timestamptz `json:"available_until"`
	ResultsVisibility  string             `json:"results_visibility"`
	IsRequired         bool               `json:"is_required"`
	ID                 uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz,
		arg.Title,
		arg.Instructions,
		arg.TimeLimitSeconds,
		arg.AttemptLimit,
		arg.PassPercentage,
		arg.RandomizeQuestions,
		arg.RandomizeOptions,
		arg.AvailableFrom,
		arg.AvailableUntil,
		arg.ResultsVisibility,
		arg.IsRequired,
		arg.ID,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CourseID,
		&i.LessonID,
		&i.Title,
		&i.Instructions,
		&i.Status,
		&i.TimeLimitSeconds,
		&i.AttemptLimit,
		&i.PassPercentage,
		&i.RandomizeQuestions,
		&i.RandomizeOptions,
		&i.AvailableFrom,
		&i.AvailableUntil,
		&i.ResultsVisibility,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuizQuestion = `-- name: UpdateQuizQuestion :one
UPDATE quiz_questions SET question_type=$1,prompt=$2,points=$3,position=$4,updated_at=now()
WHERE id=$5 RETURNING id, quiz_id, question_type, prompt, points, position, explanation, created_at, updated_at
`

type UpdateQuizQuestionParams struct {
	QuestionType string         `json:"question_type"`
	Prompt       string         `json:"prompt"`
	Points       pgtype.Numeric `json:"points"`
	Position     int32          `json:"position"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateQuizQuestion(ctx context.Context, arg UpdateQuizQuestionParams) (QuizQuestion, error) {
	row := q.db.QueryRow(ctx, updateQuizQuestion,
		arg.QuestionType,
		arg.Prompt,
		arg.Points,
		arg.Position,
		arg.ID,
	)
	var i QuizQuestion
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.QuestionType,
		&i.Prompt,
		&i.Points,
		&i.Position,
		&i.Explanation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertQuizAnswer = `-- name: UpsertQuizAnswer :one
INSERT INTO quiz_answers (id,attempt_id,question_id,selected_option_ids,text_answer)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT(attempt_id,question_id) DO UPDATE SET selected_option_ids=EXCLUDED.selected_option_ids,text_answer=EXCLUDED.text_answer,updated_at=now() RETURNING id, attempt_id, question_id, selected_option_ids, text_answer, awarded_points, is_correct, grader_feedback, created_at, updated_at
`

type UpsertQuizAnswerParams struct {
	ID                uuid.UUID   `json:"id"`
	AttemptID         uuid.UUID   `json:"attempt_id"`
	QuestionID        uuid.UUID   `json:"question_id"`
	SelectedOptionIds []uuid.UUID `json:"selected_option_ids"`
	TextAnswer        pgtype.Text `json:"text_answer"`
}

func (q *Queries) UpsertQuizAnswer(ctx context.Context, arg UpsertQuizAnswerParams) (QuizAnswer, error) {
	row := q.db.QueryRow(ctx, upsertQuizAnswer,
		arg.ID,
		arg.AttemptID,
		arg.QuestionID,
		arg.SelectedOptionIds,
		arg.TextAnswer,
	)
	var i QuizAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.SelectedOptionIds,
		&i.TextAnswer,
		&i.AwardedPoints,
		&i.IsCorrect,
		&i.GraderFeedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
