// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package data

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assessmentReport = `-- name: AssessmentReport :many
SELECT c.id AS course_id,c.title,
 COALESCE((SELECT round(count(*) FILTER(WHERE qa.passed)::numeric/NULLIF(count(*),0)*100,2) FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE q.course_id=c.id AND qa.status='graded' AND qa.submitted_at>=$1 AND qa.submitted_at<$2),0) AS quiz_pass_rate,
 COALESCE((SELECT round(count(DISTINCT s.student_id)::numeric/NULLIF((SELECT count(*) FROM enrollments e WHERE e.course_id=c.id AND e.status IN ('active','completed')),0)*100,2) FROM assignment_submissions s JOIN assignments a ON a.id=s.assignment_id WHERE a.course_id=c.id AND s.submitted_at>=$1 AND s.submitted_at<$2),0) AS assignment_submission_rate
FROM courses c WHERE c.organization_id=$3 ORDER BY c.title,c.id LIMIT $4
`

type AssessmentReportParams struct {
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	PageSize       int32              `json:"page_size"`
}

type AssessmentReportRow struct {
	CourseID                 uuid.UUID   `json:"course_id"`
	Title                    string      `json:"title"`
	QuizPassRate             interface{} `json:"quiz_pass_rate"`
	AssignmentSubmissionRate interface{} `json:"assignment_submission_rate"`
}

func (q *Queries) AssessmentReport(ctx context.Context, arg AssessmentReportParams) ([]AssessmentReportRow, error) {
	rows, err := q.db.Query(ctx, assessmentReport,
		arg.FromTime,
		arg.ToTime,
		arg.OrganizationID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssessmentReportRow{}
	for rows.Next() {
		var i AssessmentReportRow
		if err := rows.Scan(
			&i.CourseID,
			&i.Title,
			&i.QuizPassRate,
			&i.AssignmentSubmissionRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completionByCourse = `-- name: CompletionByCourse :many
SELECT c.id AS course_id,c.title,count(e.id) AS total_enrollments,count(e.id) FILTER(WHERE e.status='completed') AS completed_enrollments,
 CASE WHEN count(e.id)=0 THEN 0 ELSE round(count(e.id) FILTER(WHERE e.status='completed')::numeric/count(e.id)*100,2) END AS completion_rate
FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id AND e.created_at>=$1 AND e.created_at<$2
WHERE c.organization_id=$3 GROUP BY c.id,c.title ORDER BY total_enrollments DESC,c.id LIMIT $4
`

type CompletionByCourseParams struct {
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	PageSize       int32              `json:"page_size"`
}

type CompletionByCourseRow struct {
	CourseID             uuid.UUID   `json:"course_id"`
	Title                string      `json:"title"`
	TotalEnrollments     int64       `json:"total_enrollments"`
	CompletedEnrollments int64       `json:"completed_enrollments"`
	CompletionRate       interface{} `json:"completion_rate"`
}

func (q *Queries) CompletionByCourse(ctx context.Context, arg CompletionByCourseParams) ([]CompletionByCourseRow, error) {
	rows, err := q.db.Query(ctx, completionByCourse,
		arg.FromTime,
		arg.ToTime,
		arg.OrganizationID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompletionByCourseRow{}
	for rows.Next() {
		var i CompletionByCourseRow
		if err := rows.Scan(
			&i.CourseID,
			&i.Title,
			&i.TotalEnrollments,
			&i.CompletedEnrollments,
			&i.CompletionRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enrollmentTrend = `-- name: EnrollmentTrend :many
SELECT date_trunc('day',created_at) AS day,count(*) AS enrollments,count(*) FILTER(WHERE status='completed') AS completions
FROM enrollments WHERE organization_id=$1 AND created_at>=$2 AND created_at<$3
GROUP BY 1 ORDER BY 1 LIMIT 366
`

type EnrollmentTrendParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2    pgtype.Timestamptz `json:"created_at_2"`
}

type EnrollmentTrendRow struct {
	Day         pgtype.Interval `json:"day"`
	Enrollments int64           `json:"enrollments"`
	Completions int64           `json:"completions"`
}

func (q *Queries) EnrollmentTrend(ctx context.Context, arg EnrollmentTrendParams) ([]EnrollmentTrendRow, error) {
	rows, err := q.db.Query(ctx, enrollmentTrend, arg.OrganizationID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentTrendRow{}
	for rows.Next() {
		var i EnrollmentTrendRow
		if err := rows.Scan(&i.Day, &i.Enrollments, &i.Completions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveAttendanceReport = `-- name: LiveAttendanceReport :many
SELECT l.id AS live_session_id,l.course_id,l.title,l.scheduled_start_at,count(DISTINCT a.user_id) AS attendees,COALESCE(sum(a.duration_seconds),0)::bigint AS attendance_seconds
FROM live_sessions l LEFT JOIN live_attendance_sessions a ON a.live_session_id=l.id
WHERE l.organization_id=$1 AND l.scheduled_start_at>=$2 AND l.scheduled_start_at<$3
GROUP BY l.id ORDER BY l.scheduled_start_at DESC,l.id DESC LIMIT $4
`

type LiveAttendanceReportParams struct {
	OrganizationID     uuid.UUID          `json:"organization_id"`
	ScheduledStartAt   pgtype.Timestamptz `json:"scheduled_start_at"`
	ScheduledStartAt_2 pgtype.Timestamptz `json:"scheduled_start_at_2"`
	Limit              int32              `json:"limit"`
}

type LiveAttendanceReportRow struct {
	LiveSessionID     uuid.UUID          `json:"live_session_id"`
	CourseID          uuid.UUID          `json:"course_id"`
	Title             string             `json:"title"`
	ScheduledStartAt  pgtype.Timestamptz `json:"scheduled_start_at"`
	Attendees         int64              `json:"attendees"`
	AttendanceSeconds int64              `json:"attendance_seconds"`
}

func (q *Queries) LiveAttendanceReport(ctx context.Context, arg LiveAttendanceReportParams) ([]LiveAttendanceReportRow, error) {
	rows, err := q.db.Query(ctx, liveAttendanceReport,
		arg.OrganizationID,
		arg.ScheduledStartAt,
		arg.ScheduledStartAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveAttendanceReportRow{}
	for rows.Next() {
		var i LiveAttendanceReportRow
		if err := rows.Scan(
			&i.LiveSessionID,
			&i.CourseID,
			&i.Title,
			&i.ScheduledStartAt,
			&i.Attendees,
			&i.AttendanceSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationOverview = `-- name: OrganizationOverview :one
SELECT
 (SELECT count(DISTINCT m.user_id) FROM organization_memberships m JOIN membership_roles mr ON mr.membership_id=m.id JOIN roles r ON r.id=mr.role_id WHERE m.organization_id=$1 AND m.status='active' AND r.code='student') AS total_students,
 (SELECT count(DISTINCT m.user_id) FROM organization_memberships m JOIN membership_roles mr ON mr.membership_id=m.id JOIN roles r ON r.id=mr.role_id WHERE m.organization_id=$1 AND m.status='active' AND r.code='instructor') AS total_instructors,
 (SELECT count(*) FROM courses c WHERE c.organization_id=$1 AND c.status='published') AS published_courses,
 (SELECT count(*) FROM enrollments e WHERE e.organization_id=$1 AND e.status='active') AS active_enrollments,
 (SELECT count(*) FROM enrollments e WHERE e.organization_id=$1 AND e.status='completed') AS completed_enrollments,
 (SELECT COALESCE(sum(o.amount_minor),0)::bigint FROM orders o WHERE o.organization_id=$1 AND o.status IN ('paid','refunded') AND o.created_at>=$2 AND o.created_at<$3) AS gross_revenue_minor,
 (SELECT COALESCE(sum(r.amount_minor),0)::bigint FROM refunds r JOIN orders o ON o.id=r.order_id WHERE o.organization_id=$1 AND r.status='succeeded' AND r.created_at>=$2 AND r.created_at<$3) AS refund_amount_minor
`

type OrganizationOverviewParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
}

type OrganizationOverviewRow struct {
	TotalStudents        int64 `json:"total_students"`
	TotalInstructors     int64 `json:"total_instructors"`
	PublishedCourses     int64 `json:"published_courses"`
	ActiveEnrollments    int64 `json:"active_enrollments"`
	CompletedEnrollments int64 `json:"completed_enrollments"`
	GrossRevenueMinor    int64 `json:"gross_revenue_minor"`
	RefundAmountMinor    int64 `json:"refund_amount_minor"`
}

func (q *Queries) OrganizationOverview(ctx context.Context, arg OrganizationOverviewParams) (OrganizationOverviewRow, error) {
	row := q.db.QueryRow(ctx, organizationOverview, arg.OrganizationID, arg.FromTime, arg.ToTime)
	var i OrganizationOverviewRow
	err := row.Scan(
		&i.TotalStudents,
		&i.TotalInstructors,
		&i.PublishedCourses,
		&i.ActiveEnrollments,
		&i.CompletedEnrollments,
		&i.GrossRevenueMinor,
		&i.RefundAmountMinor,
	)
	return i, err
}

const revenueByCourse = `-- name: RevenueByCourse :many
SELECT oi.course_id,oi.course_title,count(DISTINCT o.id) AS orders,COALESCE(sum(oi.amount_minor),0)::bigint AS revenue_minor,oi.currency
FROM order_items oi JOIN orders o ON o.id=oi.order_id
WHERE o.organization_id=$1 AND o.status IN ('paid','refunded') AND o.created_at>=$2 AND o.created_at<$3
GROUP BY oi.course_id,oi.course_title,oi.currency ORDER BY revenue_minor DESC,oi.course_id LIMIT $4
`

type RevenueByCourseParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2    pgtype.Timestamptz `json:"created_at_2"`
	Limit          int32              `json:"limit"`
}

type RevenueByCourseRow struct {
	CourseID     uuid.UUID `json:"course_id"`
	CourseTitle  string    `json:"course_title"`
	Orders       int64     `json:"orders"`
	RevenueMinor int64     `json:"revenue_minor"`
	Currency     string    `json:"currency"`
}

func (q *Queries) RevenueByCourse(ctx context.Context, arg RevenueByCourseParams) ([]RevenueByCourseRow, error) {
	rows, err := q.db.Query(ctx, revenueByCourse,
		arg.OrganizationID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueByCourseRow{}
	for rows.Next() {
		var i RevenueByCourseRow
		if err := rows.Scan(
			&i.CourseID,
			&i.CourseTitle,
			&i.Orders,
			&i.RevenueMinor,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueTrend = `-- name: RevenueTrend :many
SELECT day,currency,sum(gross_minor)::bigint AS gross_minor,sum(refund_minor)::bigint AS refund_minor
FROM (
 SELECT date_trunc('day',o.created_at)::timestamptz AS day,o.currency,o.amount_minor AS gross_minor,0::bigint AS refund_minor
 FROM orders o
 WHERE o.organization_id=$1 AND o.status IN ('paid','refunded') AND o.created_at>=$2 AND o.created_at<$3
 UNION ALL
 SELECT date_trunc('day',r.created_at)::timestamptz AS day,r.currency,0::bigint AS gross_minor,r.amount_minor AS refund_minor
 FROM refunds r JOIN orders o ON o.id=r.order_id
 WHERE o.organization_id=$1 AND r.status='succeeded' AND r.created_at>=$2 AND r.created_at<$3
) ledger
GROUP BY day,currency ORDER BY day,currency LIMIT 1000
`

type RevenueTrendParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
}

type RevenueTrendRow struct {
	Day         pgtype.Timestamptz `json:"day"`
	Currency    string             `json:"currency"`
	GrossMinor  int64              `json:"gross_minor"`
	RefundMinor int64              `json:"refund_minor"`
}

func (q *Queries) RevenueTrend(ctx context.Context, arg RevenueTrendParams) ([]RevenueTrendRow, error) {
	rows, err := q.db.Query(ctx, revenueTrend, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueTrendRow{}
	for rows.Next() {
		var i RevenueTrendRow
		if err := rows.Scan(
			&i.Day,
			&i.Currency,
			&i.GrossMinor,
			&i.RefundMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
