// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthUserRoles.
const (
	AuthUserRolesAdmin   AuthUserRoles = "admin"
	AuthUserRolesStudent AuthUserRoles = "student"
	AuthUserRolesTeacher AuthUserRoles = "teacher"
)

// Valid indicates whether the value is a known member of the AuthUserRoles enum.
func (e AuthUserRoles) Valid() bool {
	switch e {
	case AuthUserRolesAdmin:
		return true
	case AuthUserRolesStudent:
		return true
	case AuthUserRolesTeacher:
		return true
	default:
		return false
	}
}

// Defines values for AuthUserStatus.
const (
	AuthUserStatusActive    AuthUserStatus = "active"
	AuthUserStatusDisabled  AuthUserStatus = "disabled"
	AuthUserStatusPending   AuthUserStatus = "pending"
	AuthUserStatusSuspended AuthUserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the AuthUserStatus enum.
func (e AuthUserStatus) Valid() bool {
	switch e {
	case AuthUserStatusActive:
		return true
	case AuthUserStatusDisabled:
		return true
	case AuthUserStatusPending:
		return true
	case AuthUserStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for CourseLevel.
const (
	CourseLevelAdvanced     CourseLevel = "advanced"
	CourseLevelAll          CourseLevel = "all"
	CourseLevelBeginner     CourseLevel = "beginner"
	CourseLevelIntermediate CourseLevel = "intermediate"
)

// Valid indicates whether the value is a known member of the CourseLevel enum.
func (e CourseLevel) Valid() bool {
	switch e {
	case CourseLevelAdvanced:
		return true
	case CourseLevelAll:
		return true
	case CourseLevelBeginner:
		return true
	case CourseLevelIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for CourseStatus.
const (
	CourseStatusArchived  CourseStatus = "archived"
	CourseStatusDraft     CourseStatus = "draft"
	CourseStatusPublished CourseStatus = "published"
	CourseStatusReview    CourseStatus = "review"
)

// Valid indicates whether the value is a known member of the CourseStatus enum.
func (e CourseStatus) Valid() bool {
	switch e {
	case CourseStatusArchived:
		return true
	case CourseStatusDraft:
		return true
	case CourseStatusPublished:
		return true
	case CourseStatusReview:
		return true
	default:
		return false
	}
}

// Defines values for CourseWriteLevel.
const (
	CourseWriteLevelAdvanced     CourseWriteLevel = "advanced"
	CourseWriteLevelAll          CourseWriteLevel = "all"
	CourseWriteLevelBeginner     CourseWriteLevel = "beginner"
	CourseWriteLevelIntermediate CourseWriteLevel = "intermediate"
)

// Valid indicates whether the value is a known member of the CourseWriteLevel enum.
func (e CourseWriteLevel) Valid() bool {
	switch e {
	case CourseWriteLevelAdvanced:
		return true
	case CourseWriteLevelAll:
		return true
	case CourseWriteLevelBeginner:
		return true
	case CourseWriteLevelIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for DeviceTokenWritePlatform.
const (
	Android DeviceTokenWritePlatform = "android"
	Ios     DeviceTokenWritePlatform = "ios"
	Web     DeviceTokenWritePlatform = "web"
)

// Valid indicates whether the value is a known member of the DeviceTokenWritePlatform enum.
func (e DeviceTokenWritePlatform) Valid() bool {
	switch e {
	case Android:
		return true
	case Ios:
		return true
	case Web:
		return true
	default:
		return false
	}
}

// Defines values for EnrollmentStatus.
const (
	EnrollmentStatusActive         EnrollmentStatus = "active"
	EnrollmentStatusCancelled      EnrollmentStatus = "cancelled"
	EnrollmentStatusCompleted      EnrollmentStatus = "completed"
	EnrollmentStatusExpired        EnrollmentStatus = "expired"
	EnrollmentStatusPendingPayment EnrollmentStatus = "pending_payment"
)

// Valid indicates whether the value is a known member of the EnrollmentStatus enum.
func (e EnrollmentStatus) Valid() bool {
	switch e {
	case EnrollmentStatusActive:
		return true
	case EnrollmentStatusCancelled:
		return true
	case EnrollmentStatusCompleted:
		return true
	case EnrollmentStatusExpired:
		return true
	case EnrollmentStatusPendingPayment:
		return true
	default:
		return false
	}
}

// Defines values for InvitationWriteRole.
const (
	InvitationWriteRoleInstructor        InvitationWriteRole = "instructor"
	InvitationWriteRoleOrganizationAdmin InvitationWriteRole = "organization_admin"
	InvitationWriteRoleStudent           InvitationWriteRole = "student"
)

// Valid indicates whether the value is a known member of the InvitationWriteRole enum.
func (e InvitationWriteRole) Valid() bool {
	switch e {
	case InvitationWriteRoleInstructor:
		return true
	case InvitationWriteRoleOrganizationAdmin:
		return true
	case InvitationWriteRoleStudent:
		return true
	default:
		return false
	}
}

// Defines values for LessonWriteLessonType.
const (
	LessonWriteLessonTypeAssignment LessonWriteLessonType = "assignment"
	LessonWriteLessonTypeLive       LessonWriteLessonType = "live"
	LessonWriteLessonTypePdf        LessonWriteLessonType = "pdf"
	LessonWriteLessonTypeQuiz       LessonWriteLessonType = "quiz"
	LessonWriteLessonTypeText       LessonWriteLessonType = "text"
	LessonWriteLessonTypeVideo      LessonWriteLessonType = "video"
)

// Valid indicates whether the value is a known member of the LessonWriteLessonType enum.
func (e LessonWriteLessonType) Valid() bool {
	switch e {
	case LessonWriteLessonTypeAssignment:
		return true
	case LessonWriteLessonTypeLive:
		return true
	case LessonWriteLessonTypePdf:
		return true
	case LessonWriteLessonTypeQuiz:
		return true
	case LessonWriteLessonTypeText:
		return true
	case LessonWriteLessonTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for MembershipRoles.
const (
	MembershipRolesInstructor        MembershipRoles = "instructor"
	MembershipRolesOrganizationAdmin MembershipRoles = "organization_admin"
	MembershipRolesStudent           MembershipRoles = "student"
	MembershipRolesSuperAdmin        MembershipRoles = "super_admin"
)

// Valid indicates whether the value is a known member of the MembershipRoles enum.
func (e MembershipRoles) Valid() bool {
	switch e {
	case MembershipRolesInstructor:
		return true
	case MembershipRolesOrganizationAdmin:
		return true
	case MembershipRolesStudent:
		return true
	case MembershipRolesSuperAdmin:
		return true
	default:
		return false
	}
}

// Defines values for MembershipUpdateRoles.
const (
	MembershipUpdateRolesInstructor        MembershipUpdateRoles = "instructor"
	MembershipUpdateRolesOrganizationAdmin MembershipUpdateRoles = "organization_admin"
	MembershipUpdateRolesStudent           MembershipUpdateRoles = "student"
)

// Valid indicates whether the value is a known member of the MembershipUpdateRoles enum.
func (e MembershipUpdateRoles) Valid() bool {
	switch e {
	case MembershipUpdateRolesInstructor:
		return true
	case MembershipUpdateRolesOrganizationAdmin:
		return true
	case MembershipUpdateRolesStudent:
		return true
	default:
		return false
	}
}

// Defines values for MembershipUpdateStatus.
const (
	MembershipUpdateStatusActive    MembershipUpdateStatus = "active"
	MembershipUpdateStatusSuspended MembershipUpdateStatus = "suspended"
)

// Valid indicates whether the value is a known member of the MembershipUpdateStatus enum.
func (e MembershipUpdateStatus) Valid() bool {
	switch e {
	case MembershipUpdateStatusActive:
		return true
	case MembershipUpdateStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for ProgressState.
const (
	ProgressStateCompleted  ProgressState = "completed"
	ProgressStateNotStarted ProgressState = "not_started"
	ProgressStateStarted    ProgressState = "started"
)

// Valid indicates whether the value is a known member of the ProgressState enum.
func (e ProgressState) Valid() bool {
	switch e {
	case ProgressStateCompleted:
		return true
	case ProgressStateNotStarted:
		return true
	case ProgressStateStarted:
		return true
	default:
		return false
	}
}

// Defines values for QuestionWriteQuestionType.
const (
	Multiple    QuestionWriteQuestionType = "multiple"
	ShortAnswer QuestionWriteQuestionType = "short_answer"
	Single      QuestionWriteQuestionType = "single"
	TrueFalse   QuestionWriteQuestionType = "true_false"
)

// Valid indicates whether the value is a known member of the QuestionWriteQuestionType enum.
func (e QuestionWriteQuestionType) Valid() bool {
	switch e {
	case Multiple:
		return true
	case ShortAnswer:
		return true
	case Single:
		return true
	case TrueFalse:
		return true
	default:
		return false
	}
}

// Defines values for QuizWriteResultsVisibility.
const (
	AfterClose QuizWriteResultsVisibility = "after_close"
	Immediate  QuizWriteResultsVisibility = "immediate"
	Manual     QuizWriteResultsVisibility = "manual"
)

// Valid indicates whether the value is a known member of the QuizWriteResultsVisibility enum.
func (e QuizWriteResultsVisibility) Valid() bool {
	switch e {
	case AfterClose:
		return true
	case Immediate:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for RoleWriteRoles.
const (
	RoleWriteRolesAdmin   RoleWriteRoles = "admin"
	RoleWriteRolesStudent RoleWriteRoles = "student"
	RoleWriteRolesTeacher RoleWriteRoles = "teacher"
)

// Valid indicates whether the value is a known member of the RoleWriteRoles enum.
func (e RoleWriteRoles) Valid() bool {
	switch e {
	case RoleWriteRolesAdmin:
		return true
	case RoleWriteRolesStudent:
		return true
	case RoleWriteRolesTeacher:
		return true
	default:
		return false
	}
}

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenPairTokenType enum.
func (e TokenPairTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UploadIntentWriteKind.
const (
	UploadIntentWriteKindAssignment UploadIntentWriteKind = "assignment"
	UploadIntentWriteKindImage      UploadIntentWriteKind = "image"
	UploadIntentWriteKindPdf        UploadIntentWriteKind = "pdf"
	UploadIntentWriteKindVideo      UploadIntentWriteKind = "video"
)

// Valid indicates whether the value is a known member of the UploadIntentWriteKind enum.
func (e UploadIntentWriteKind) Valid() bool {
	switch e {
	case UploadIntentWriteKindAssignment:
		return true
	case UploadIntentWriteKindImage:
		return true
	case UploadIntentWriteKindPdf:
		return true
	case UploadIntentWriteKindVideo:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusActive    UserStatus = "active"
	UserStatusDisabled  UserStatus = "disabled"
	UserStatusPending   UserStatus = "pending"
	UserStatusSuspended UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive:
		return true
	case UserStatusDisabled:
		return true
	case UserStatusPending:
		return true
	case UserStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for UserStatusWriteStatus.
const (
	UserStatusWriteStatusActive    UserStatusWriteStatus = "active"
	UserStatusWriteStatusDisabled  UserStatusWriteStatus = "disabled"
	UserStatusWriteStatusPending   UserStatusWriteStatus = "pending"
	UserStatusWriteStatusSuspended UserStatusWriteStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatusWriteStatus enum.
func (e UserStatusWriteStatus) Valid() bool {
	switch e {
	case UserStatusWriteStatusActive:
		return true
	case UserStatusWriteStatusDisabled:
		return true
	case UserStatusWriteStatusPending:
		return true
	case UserStatusWriteStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for AdminListUsersParamsStatus.
const (
	AdminListUsersParamsStatusActive    AdminListUsersParamsStatus = "active"
	AdminListUsersParamsStatusDisabled  AdminListUsersParamsStatus = "disabled"
	AdminListUsersParamsStatusPending   AdminListUsersParamsStatus = "pending"
	AdminListUsersParamsStatusSuspended AdminListUsersParamsStatus = "suspended"
)

// Valid indicates whether the value is a known member of the AdminListUsersParamsStatus enum.
func (e AdminListUsersParamsStatus) Valid() bool {
	switch e {
	case AdminListUsersParamsStatusActive:
		return true
	case AdminListUsersParamsStatusDisabled:
		return true
	case AdminListUsersParamsStatusPending:
		return true
	case AdminListUsersParamsStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for AdminListUsersParamsRole.
const (
	AdminListUsersParamsRoleAdmin   AdminListUsersParamsRole = "admin"
	AdminListUsersParamsRoleStudent AdminListUsersParamsRole = "student"
	AdminListUsersParamsRoleTeacher AdminListUsersParamsRole = "teacher"
)

// Valid indicates whether the value is a known member of the AdminListUsersParamsRole enum.
func (e AdminListUsersParamsRole) Valid() bool {
	switch e {
	case AdminListUsersParamsRoleAdmin:
		return true
	case AdminListUsersParamsRoleStudent:
		return true
	case AdminListUsersParamsRoleTeacher:
		return true
	default:
		return false
	}
}

// Defines values for ListCoursesParamsLevel.
const (
	ListCoursesParamsLevelAdvanced     ListCoursesParamsLevel = "advanced"
	ListCoursesParamsLevelAll          ListCoursesParamsLevel = "all"
	ListCoursesParamsLevelBeginner     ListCoursesParamsLevel = "beginner"
	ListCoursesParamsLevelIntermediate ListCoursesParamsLevel = "intermediate"
)

// Valid indicates whether the value is a known member of the ListCoursesParamsLevel enum.
func (e ListCoursesParamsLevel) Valid() bool {
	switch e {
	case ListCoursesParamsLevelAdvanced:
		return true
	case ListCoursesParamsLevelAll:
		return true
	case ListCoursesParamsLevelBeginner:
		return true
	case ListCoursesParamsLevelIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for TeacherUpdateAssignmentParamsStatus.
const (
	TeacherUpdateAssignmentParamsStatusArchived  TeacherUpdateAssignmentParamsStatus = "archived"
	TeacherUpdateAssignmentParamsStatusDraft     TeacherUpdateAssignmentParamsStatus = "draft"
	TeacherUpdateAssignmentParamsStatusPublished TeacherUpdateAssignmentParamsStatus = "published"
)

// Valid indicates whether the value is a known member of the TeacherUpdateAssignmentParamsStatus enum.
func (e TeacherUpdateAssignmentParamsStatus) Valid() bool {
	switch e {
	case TeacherUpdateAssignmentParamsStatusArchived:
		return true
	case TeacherUpdateAssignmentParamsStatusDraft:
		return true
	case TeacherUpdateAssignmentParamsStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for TeacherUpdateQuizParamsStatus.
const (
	TeacherUpdateQuizParamsStatusArchived  TeacherUpdateQuizParamsStatus = "archived"
	TeacherUpdateQuizParamsStatusDraft     TeacherUpdateQuizParamsStatus = "draft"
	TeacherUpdateQuizParamsStatusPublished TeacherUpdateQuizParamsStatus = "published"
)

// Valid indicates whether the value is a known member of the TeacherUpdateQuizParamsStatus enum.
func (e TeacherUpdateQuizParamsStatus) Valid() bool {
	switch e {
	case TeacherUpdateQuizParamsStatusArchived:
		return true
	case TeacherUpdateQuizParamsStatusDraft:
		return true
	case TeacherUpdateQuizParamsStatusPublished:
		return true
	default:
		return false
	}
}

// AnswerWrite defines model for AnswerWrite.
type AnswerWrite struct {
	QuestionId        UUID    `json:"question_id"`
	SelectedOptionIds *[]UUID `json:"selected_option_ids,omitempty"`
	TextAnswer        *string `json:"text_answer,omitempty"`
}

// AssignmentWrite defines model for AssignmentWrite.
type AssignmentWrite struct {
	AllowedFileTypes   *[]string  `json:"allowed_file_types,omitempty"`
	AttachmentAssetIds *[]UUID    `json:"attachment_asset_ids,omitempty"`
	CourseId           UUID       `json:"course_id"`
	DueAt              *Timestamp `json:"due_at,omitempty"`
	Instructions       *string    `json:"instructions,omitempty"`
	IsRequired         *bool      `json:"is_required,omitempty"`
	LessonId           *UUID      `json:"lesson_id,omitempty"`
	MaximumScore       float32    `json:"maximum_score"`
	MaximumSubmissions int        `json:"maximum_submissions"`
	PassingScore       float32    `json:"passing_score"`
	Title              string     `json:"title"`
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	DisplayName     string              `json:"display_name"`
	Email           openapi_types.Email `json:"email"`
	EmailVerifiedAt *Timestamp          `json:"email_verified_at,omitempty"`
	Id              UUID                `json:"id"`
	Roles           []AuthUserRoles     `json:"roles"`
	Status          AuthUserStatus      `json:"status"`
}

// AuthUserRoles defines model for AuthUser.Roles.
type AuthUserRoles string

// AuthUserStatus defines model for AuthUser.Status.
type AuthUserStatus string

// CategoryWrite defines model for CategoryWrite.
type CategoryWrite struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
}

// CertificateVerification defines model for CertificateVerification.
type CertificateVerification struct {
	CertificateNumber string    `json:"certificate_number"`
	CourseTitle       string    `json:"course_title"`
	IssuedAt          Timestamp `json:"issued_at"`
	OrganizationName  string    `json:"organization_name"`
	StudentName       string    `json:"student_name"`
	Valid             bool      `json:"valid"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword *string `json:"current_password,omitempty"`
	NewPassword     *string `json:"new_password,omitempty"`
}

// Course defines model for Course.
type Course struct {
	Currency         string       `json:"currency"`
	Description      string       `json:"description"`
	Id               UUID         `json:"id"`
	IsFree           bool         `json:"is_free"`
	Language         string       `json:"language"`
	Level            CourseLevel  `json:"level"`
	OrganizationId   UUID         `json:"organization_id"`
	PriceMinor       int64        `json:"price_minor"`
	Slug             string       `json:"slug"`
	Status           CourseStatus `json:"status"`
	ThumbnailAssetId *UUID        `json:"thumbnail_asset_id,omitempty"`
	Title            string       `json:"title"`
	Version          int64        `json:"version"`
}

// CourseLevel defines model for Course.Level.
type CourseLevel string

// CourseStatus defines model for Course.Status.
type CourseStatus string

// CourseWrite defines model for CourseWrite.
type CourseWrite struct {
	CategoryId       *UUID            `json:"category_id,omitempty"`
	Currency         string           `json:"currency"`
	Description      string           `json:"description"`
	IsFree           bool             `json:"is_free"`
	Language         string           `json:"language"`
	Level            CourseWriteLevel `json:"level"`
	PriceMinor       int64            `json:"price_minor"`
	Slug             string           `json:"slug"`
	ThumbnailAssetId *UUID            `json:"thumbnail_asset_id,omitempty"`
	Title            string           `json:"title"`
	Version          int64            `json:"version"`
}

// CourseWriteLevel defines model for CourseWrite.Level.
type CourseWriteLevel string

// DeviceTokenWrite defines model for DeviceTokenWrite.
type DeviceTokenWrite struct {
	Platform DeviceTokenWritePlatform `json:"platform"`

	// Token Sensitive push-provider token; stored encrypted and never logged.
	Token string `json:"token"`
}

// DeviceTokenWritePlatform defines model for DeviceTokenWrite.Platform.
type DeviceTokenWritePlatform string

// Enrollment defines model for Enrollment.
type Enrollment struct {
	CompletionPercentage float32          `json:"completion_percentage"`
	CourseId             UUID             `json:"course_id"`
	Id                   UUID             `json:"id"`
	Status               EnrollmentStatus `json:"status"`
	StudentId            UUID             `json:"student_id"`
}

// EnrollmentStatus defines model for Enrollment.Status.
type EnrollmentStatus string

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// GradeWrite defines model for GradeWrite.
type GradeWrite struct {
	Feedback   *string `json:"feedback,omitempty"`
	Points     float32 `json:"points"`
	QuestionId *UUID   `json:"question_id,omitempty"`
}

// InstructorAssignment defines model for InstructorAssignment.
type InstructorAssignment struct {
	InstructorId UUID `json:"instructor_id"`
}

// InvitationAccept defines model for InvitationAccept.
type InvitationAccept struct {
	Token string `json:"token"`
}

// InvitationWrite defines model for InvitationWrite.
type InvitationWrite struct {
	Email openapi_types.Email `json:"email"`
	Role  InvitationWriteRole `json:"role"`
}

// InvitationWriteRole defines model for InvitationWrite.Role.
type InvitationWriteRole string

// JoinToken defines model for JoinToken.
type JoinToken struct {
	ExpiresAt Timestamp `json:"expires_at"`

	// Token Sensitive short-lived room token; never log it.
	Token string `json:"token"`
	Url   string `json:"url"`
}

// LessonWrite defines model for LessonWrite.
type LessonWrite struct {
	Body            *string               `json:"body,omitempty"`
	Description     *string               `json:"description,omitempty"`
	DurationSeconds *int                  `json:"duration_seconds,omitempty"`
	IsPreview       bool                  `json:"is_preview"`
	IsPublished     bool                  `json:"is_published"`
	IsRequired      bool                  `json:"is_required"`
	LessonType      LessonWriteLessonType `json:"lesson_type"`
	MediaAssetId    *UUID                 `json:"media_asset_id,omitempty"`
	Position        int                   `json:"position"`
	Title           string                `json:"title"`
}

// LessonWriteLessonType defines model for LessonWrite.LessonType.
type LessonWriteLessonType string

// ListResponse defines model for ListResponse.
type ListResponse struct {
	Items      []interface{} `json:"items"`
	NextCursor *string       `json:"next_cursor,omitempty"`
}

// LiveSessionWrite defines model for LiveSessionWrite.
type LiveSessionWrite struct {
	CourseId         UUID      `json:"course_id"`
	Description      *string   `json:"description,omitempty"`
	ScheduledEndAt   Timestamp `json:"scheduled_end_at"`
	ScheduledStartAt Timestamp `json:"scheduled_start_at"`
	Title            string    `json:"title"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password *string             `json:"password,omitempty"`
}

// Membership defines model for Membership.
type Membership struct {
	Id               UUID              `json:"id"`
	OrganizationId   UUID              `json:"organization_id"`
	OrganizationName string            `json:"organization_name"`
	Roles            []MembershipRoles `json:"roles"`
	Status           string            `json:"status"`
}

// MembershipRoles defines model for Membership.Roles.
type MembershipRoles string

// MembershipUpdate defines model for MembershipUpdate.
type MembershipUpdate struct {
	Roles  []MembershipUpdateRoles `json:"roles"`
	Status MembershipUpdateStatus  `json:"status"`
}

// MembershipUpdateRoles defines model for MembershipUpdate.Roles.
type MembershipUpdateRoles string

// MembershipUpdateStatus defines model for MembershipUpdate.Status.
type MembershipUpdateStatus string

// ModuleWrite defines model for ModuleWrite.
type ModuleWrite struct {
	Description *string `json:"description,omitempty"`
	Position    int     `json:"position"`
	Title       string  `json:"title"`
}

// OptionWrite defines model for OptionWrite.
type OptionWrite struct {
	IsCorrect bool   `json:"is_correct"`
	Position  int    `json:"position"`
	Text      string `json:"text"`
}

// Order defines model for Order.
type Order struct {
	AmountMinor int64  `json:"amount_minor"`
	Currency    string `json:"currency"`
	Id          UUID   `json:"id"`

	// Status pending, requires_action, paid, failed, cancelled, or refunded
	Status string `json:"status"`
}

// OrderWrite defines model for OrderWrite.
type OrderWrite struct {
	CourseId UUID `json:"course_id"`
}

// OrganizationWrite defines model for OrganizationWrite.
type OrganizationWrite struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// PaymentIntent defines model for PaymentIntent.
type PaymentIntent struct {
	// ClientSecret Sensitive ephemeral provider value; never log it.
	ClientSecret string `json:"client_secret"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail    *string       `json:"detail,omitempty"`
	Errors    *[]FieldError `json:"errors,omitempty"`
	Instance  *string       `json:"instance,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    int           `json:"status"`
	Title     string        `json:"title"`
	Type      string        `json:"type"`
}

// ProfileWrite defines model for ProfileWrite.
type ProfileWrite struct {
	Biography   *string   `json:"biography,omitempty"`
	DisplayName string    `json:"display_name"`
	Expertise   *[]string `json:"expertise,omitempty"`
	FirstName   *string   `json:"first_name,omitempty"`
	LastName    *string   `json:"last_name,omitempty"`
	Locale      *string   `json:"locale,omitempty"`
	Phone       *string   `json:"phone,omitempty"`
	Timezone    *string   `json:"timezone,omitempty"`
}

// Progress defines model for Progress.
type Progress struct {
	LessonId            UUID          `json:"lesson_id"`
	PositionSeconds     int           `json:"position_seconds"`
	State               ProgressState `json:"state"`
	TotalWatchedSeconds int           `json:"total_watched_seconds"`
}

// ProgressState defines model for Progress.State.
type ProgressState string

// ProgressWrite defines model for ProgressWrite.
type ProgressWrite struct {
	ManualComplete      *bool `json:"manual_complete,omitempty"`
	PositionSeconds     int   `json:"position_seconds"`
	WatchedSecondsDelta int   `json:"watched_seconds_delta"`
}

// QuestionWrite defines model for QuestionWrite.
type QuestionWrite struct {
	Options      []OptionWrite             `json:"options"`
	Points       float32                   `json:"points"`
	Position     int                       `json:"position"`
	Prompt       string                    `json:"prompt"`
	QuestionType QuestionWriteQuestionType `json:"question_type"`
}

// QuestionWriteQuestionType defines model for QuestionWrite.QuestionType.
type QuestionWriteQuestionType string

// QuizAttempt defines model for QuizAttempt.
type QuizAttempt struct {
	AttemptNumber int      `json:"attempt_number"`
	Id            UUID     `json:"id"`
	Passed        *bool    `json:"passed,omitempty"`
	Percentage    *float32 `json:"percentage,omitempty"`

	// Questions Correct-answer flags are never included before submission.
	Questions []map[string]interface{} `json:"questions"`
	QuizId    UUID                     `json:"quiz_id"`
	StartedAt Timestamp                `json:"started_at"`
	Status    string                   `json:"status"`
}

// QuizWrite defines model for QuizWrite.
type QuizWrite struct {
	AttemptLimit       int                         `json:"attempt_limit"`
	AvailableFrom      *Timestamp                  `json:"available_from,omitempty"`
	AvailableUntil     *Timestamp                  `json:"available_until,omitempty"`
	CourseId           UUID                        `json:"course_id"`
	Instructions       *string                     `json:"instructions,omitempty"`
	IsRequired         *bool                       `json:"is_required,omitempty"`
	LessonId           *UUID                       `json:"lesson_id,omitempty"`
	PassPercentage     float32                     `json:"pass_percentage"`
	RandomizeOptions   *bool                       `json:"randomize_options,omitempty"`
	RandomizeQuestions *bool                       `json:"randomize_questions,omitempty"`
	ResultsVisibility  *QuizWriteResultsVisibility `json:"results_visibility,omitempty"`
	TimeLimitSeconds   *int                        `json:"time_limit_seconds,omitempty"`
	Title              string                      `json:"title"`
}

// QuizWriteResultsVisibility defines model for QuizWrite.ResultsVisibility.
type QuizWriteResultsVisibility string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    *string             `json:"password,omitempty"`
}

// RegistrationResponse defines model for RegistrationResponse.
type RegistrationResponse struct {
	Message string   `json:"message"`
	User    AuthUser `json:"user"`

	// VerificationToken Development/test only.
	VerificationToken *string `json:"verification_token,omitempty"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword *string `json:"new_password,omitempty"`
	Token       *string `json:"token,omitempty"`
}

// RoleWrite defines model for RoleWrite.
type RoleWrite struct {
	Roles []RoleWriteRoles `json:"roles"`
}

// RoleWriteRoles defines model for RoleWrite.Roles.
type RoleWriteRoles string

// SubmissionWrite defines model for SubmissionWrite.
type SubmissionWrite struct {
	MediaAssetIds *[]UUID `json:"media_asset_ids,omitempty"`
	TextContent   *string `json:"text_content,omitempty"`
}

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken  *string            `json:"access_token,omitempty"`
	ExpiresAt    Timestamp          `json:"expires_at"`
	RefreshToken *string            `json:"refresh_token,omitempty"`
	TokenType    TokenPairTokenType `json:"token_type"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token *string `json:"token,omitempty"`
}

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// UploadIntent defines model for UploadIntent.
type UploadIntent struct {
	ExpiresAt    Timestamp `json:"expires_at"`
	Id           UUID      `json:"id"`
	MediaAssetId UUID      `json:"media_asset_id"`
	UploadUrl    string    `json:"upload_url"`
}

// UploadIntentWrite defines model for UploadIntentWrite.
type UploadIntentWrite struct {
	ChecksumSha256 *string               `json:"checksum_sha256,omitempty"`
	ContentType    string                `json:"content_type"`
	Filename       string                `json:"filename"`
	Kind           UploadIntentWriteKind `json:"kind"`
	SizeBytes      int64                 `json:"size_bytes"`
}

// UploadIntentWriteKind defines model for UploadIntentWrite.Kind.
type UploadIntentWriteKind string

// User defines model for User.
type User struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          UUID                `json:"id"`
	Memberships []Membership        `json:"memberships"`
	Status      UserStatus          `json:"status"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// UserStatusWrite defines model for UserStatusWrite.
type UserStatusWrite struct {
	Status UserStatusWriteStatus `json:"status"`
}

// UserStatusWriteStatus defines model for UserStatusWrite.Status.
type UserStatusWriteStatus string

// CourseID defines model for CourseID.
type CourseID = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// ID defines model for ID.
type ID = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// ReportFrom defines model for ReportFrom.
type ReportFrom = time.Time

// ReportTo defines model for ReportTo.
type ReportTo = time.Time

// Slug defines model for Slug.
type Slug = string

// List defines model for List.
type List = ListResponse

// OK defines model for OK.
type OK map[string]interface{}

// Tokens defines model for Tokens.
type Tokens = TokenPair

// RefreshToken defines model for RefreshToken.
type RefreshToken struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// AdminListEnrollmentsParams defines parameters for AdminListEnrollments.
type AdminListEnrollmentsParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor    *Cursor             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit     *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Status    *string             `form:"status,omitempty" json:"status,omitempty"`
	CourseId  *openapi_types.UUID `form:"course_id,omitempty" json:"course_id,omitempty"`
	StudentId *openapi_types.UUID `form:"student_id,omitempty" json:"student_id,omitempty"`
}

// AdminPaymentHistoryParams defines parameters for AdminPaymentHistory.
type AdminPaymentHistoryParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Status *string             `form:"status,omitempty" json:"status,omitempty"`
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// AdminOverviewReportParams defines parameters for AdminOverviewReport.
type AdminOverviewReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// AdminRevenueReportParams defines parameters for AdminRevenueReport.
type AdminRevenueReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// AdminListUsersParams defines parameters for AdminListUsers.
type AdminListUsersParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor                     `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit                      `form:"limit,omitempty" json:"limit,omitempty"`
	Q      *string                     `form:"q,omitempty" json:"q,omitempty"`
	Status *AdminListUsersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Role   *AdminListUsersParamsRole   `form:"role,omitempty" json:"role,omitempty"`
}

// AdminListUsersParamsStatus defines parameters for AdminListUsers.
type AdminListUsersParamsStatus string

// AdminListUsersParamsRole defines parameters for AdminListUsers.
type AdminListUsersParamsRole string

// LogoutJSONBody defines parameters for Logout.
type LogoutJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// RefreshJSONBody defines parameters for Refresh.
type RefreshJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// ListCoursesParams defines parameters for ListCourses.
type ListCoursesParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor         *Cursor                 `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit          *Limit                  `form:"limit,omitempty" json:"limit,omitempty"`
	Q              *string                 `form:"q,omitempty" json:"q,omitempty"`
	OrganizationId *openapi_types.UUID     `form:"organization_id,omitempty" json:"organization_id,omitempty"`
	CategoryId     *openapi_types.UUID     `form:"category_id,omitempty" json:"category_id,omitempty"`
	Level          *ListCoursesParamsLevel `form:"level,omitempty" json:"level,omitempty"`
}

// ListCoursesParamsLevel defines parameters for ListCourses.
type ListCoursesParamsLevel string

// ListNotificationsParams defines parameters for ListNotifications.
type ListNotificationsParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePaymentOrderParams defines parameters for CreatePaymentOrder.
type CreatePaymentOrderParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// StudentCertificatesParams defines parameters for StudentCertificates.
type StudentCertificatesParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// StudentListEnrollmentsParams defines parameters for StudentListEnrollments.
type StudentListEnrollmentsParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// StudentPaymentHistoryParams defines parameters for StudentPaymentHistory.
type StudentPaymentHistoryParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// StudentListQuizAttemptsParams defines parameters for StudentListQuizAttempts.
type StudentListQuizAttemptsParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// StudentResultsParams defines parameters for StudentResults.
type StudentResultsParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// TeacherListAssignmentsParams defines parameters for TeacherListAssignments.
type TeacherListAssignmentsParams struct {
	CourseId CourseID `form:"course_id" json:"course_id"`

	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// TeacherUpdateAssignmentParams defines parameters for TeacherUpdateAssignment.
type TeacherUpdateAssignmentParams struct {
	Status *TeacherUpdateAssignmentParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// TeacherUpdateAssignmentParamsStatus defines parameters for TeacherUpdateAssignment.
type TeacherUpdateAssignmentParamsStatus string

// TeacherListCoursesParams defines parameters for TeacherListCourses.
type TeacherListCoursesParams struct {
	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// TeacherListLiveClassesParams defines parameters for TeacherListLiveClasses.
type TeacherListLiveClassesParams struct {
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// TeacherListQuizzesParams defines parameters for TeacherListQuizzes.
type TeacherListQuizzesParams struct {
	CourseId CourseID `form:"course_id" json:"course_id"`

	// Cursor Opaque timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// TeacherUpdateQuizParams defines parameters for TeacherUpdateQuiz.
type TeacherUpdateQuizParams struct {
	Status *TeacherUpdateQuizParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// TeacherUpdateQuizParamsStatus defines parameters for TeacherUpdateQuiz.
type TeacherUpdateQuizParamsStatus string

// TeacherOverviewReportParams defines parameters for TeacherOverviewReport.
type TeacherOverviewReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// TeacherGradeSubmissionParams defines parameters for TeacherGradeSubmission.
type TeacherGradeSubmissionParams struct {
	ReturnForResubmission *bool `form:"return_for_resubmission,omitempty" json:"return_for_resubmission,omitempty"`
}

// AdminReplaceUserRolesJSONRequestBody defines body for AdminReplaceUserRoles for application/json ContentType.
type AdminReplaceUserRolesJSONRequestBody = RoleWrite

// AdminSetUserStatusJSONRequestBody defines body for AdminSetUserStatus for application/json ContentType.
type AdminSetUserStatusJSONRequestBody = UserStatusWrite

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = ForgotPasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody LogoutJSONBody

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody RefreshJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = TokenRequest

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceTokenWrite

// CreateUploadIntentJSONRequestBody defines body for CreateUploadIntent for application/json ContentType.
type CreateUploadIntentJSONRequestBody = UploadIntentWrite

// CreatePaymentOrderJSONRequestBody defines body for CreatePaymentOrder for application/json ContentType.
type CreatePaymentOrderJSONRequestBody = OrderWrite

// StudentCreateSubmissionJSONRequestBody defines body for StudentCreateSubmission for application/json ContentType.
type StudentCreateSubmissionJSONRequestBody = SubmissionWrite

// StudentUpdateProgressJSONRequestBody defines body for StudentUpdateProgress for application/json ContentType.
type StudentUpdateProgressJSONRequestBody = ProgressWrite

// StudentSaveQuizAnswerJSONRequestBody defines body for StudentSaveQuizAnswer for application/json ContentType.
type StudentSaveQuizAnswerJSONRequestBody = AnswerWrite

// TeacherCreateAssignmentJSONRequestBody defines body for TeacherCreateAssignment for application/json ContentType.
type TeacherCreateAssignmentJSONRequestBody = AssignmentWrite

// TeacherUpdateAssignmentJSONRequestBody defines body for TeacherUpdateAssignment for application/json ContentType.
type TeacherUpdateAssignmentJSONRequestBody = AssignmentWrite

// TeacherCreateCourseJSONRequestBody defines body for TeacherCreateCourse for application/json ContentType.
type TeacherCreateCourseJSONRequestBody = CourseWrite

// TeacherUpdateCourseJSONRequestBody defines body for TeacherUpdateCourse for application/json ContentType.
type TeacherUpdateCourseJSONRequestBody = CourseWrite

// TeacherCreateModuleJSONRequestBody defines body for TeacherCreateModule for application/json ContentType.
type TeacherCreateModuleJSONRequestBody = ModuleWrite

// TeacherUpdateLessonJSONRequestBody defines body for TeacherUpdateLesson for application/json ContentType.
type TeacherUpdateLessonJSONRequestBody = LessonWrite

// TeacherCreateLiveClassJSONRequestBody defines body for TeacherCreateLiveClass for application/json ContentType.
type TeacherCreateLiveClassJSONRequestBody = LiveSessionWrite

// TeacherUpdateLiveClassJSONRequestBody defines body for TeacherUpdateLiveClass for application/json ContentType.
type TeacherUpdateLiveClassJSONRequestBody = LiveSessionWrite

// TeacherUpdateModuleJSONRequestBody defines body for TeacherUpdateModule for application/json ContentType.
type TeacherUpdateModuleJSONRequestBody = ModuleWrite

// TeacherCreateLessonJSONRequestBody defines body for TeacherCreateLesson for application/json ContentType.
type TeacherCreateLessonJSONRequestBody = LessonWrite

// TeacherUpdateQuizQuestionJSONRequestBody defines body for TeacherUpdateQuizQuestion for application/json ContentType.
type TeacherUpdateQuizQuestionJSONRequestBody = QuestionWrite

// TeacherCreateQuizJSONRequestBody defines body for TeacherCreateQuiz for application/json ContentType.
type TeacherCreateQuizJSONRequestBody = QuizWrite

// TeacherUpdateQuizJSONRequestBody defines body for TeacherUpdateQuiz for application/json ContentType.
type TeacherUpdateQuizJSONRequestBody = QuizWrite

// TeacherCreateQuizQuestionJSONRequestBody defines body for TeacherCreateQuizQuestion for application/json ContentType.
type TeacherCreateQuizQuestionJSONRequestBody = QuestionWrite

// TeacherGradeSubmissionJSONRequestBody defines body for TeacherGradeSubmission for application/json ContentType.
type TeacherGradeSubmissionJSONRequestBody = GradeWrite

// UpdateCurrentProfileJSONRequestBody defines body for UpdateCurrentProfile for application/json ContentType.
type UpdateCurrentProfileJSONRequestBody = ProfileWrite
