// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CourseLevel.
const (
	CourseLevelAdvanced     CourseLevel = "advanced"
	CourseLevelAll          CourseLevel = "all"
	CourseLevelBeginner     CourseLevel = "beginner"
	CourseLevelIntermediate CourseLevel = "intermediate"
)

// Valid indicates whether the value is a known member of the CourseLevel enum.
func (e CourseLevel) Valid() bool {
	switch e {
	case CourseLevelAdvanced:
		return true
	case CourseLevelAll:
		return true
	case CourseLevelBeginner:
		return true
	case CourseLevelIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for CourseStatus.
const (
	CourseStatusArchived  CourseStatus = "archived"
	CourseStatusDraft     CourseStatus = "draft"
	CourseStatusPublished CourseStatus = "published"
	CourseStatusReview    CourseStatus = "review"
)

// Valid indicates whether the value is a known member of the CourseStatus enum.
func (e CourseStatus) Valid() bool {
	switch e {
	case CourseStatusArchived:
		return true
	case CourseStatusDraft:
		return true
	case CourseStatusPublished:
		return true
	case CourseStatusReview:
		return true
	default:
		return false
	}
}

// Defines values for CourseWriteLevel.
const (
	CourseWriteLevelAdvanced     CourseWriteLevel = "advanced"
	CourseWriteLevelAll          CourseWriteLevel = "all"
	CourseWriteLevelBeginner     CourseWriteLevel = "beginner"
	CourseWriteLevelIntermediate CourseWriteLevel = "intermediate"
)

// Valid indicates whether the value is a known member of the CourseWriteLevel enum.
func (e CourseWriteLevel) Valid() bool {
	switch e {
	case CourseWriteLevelAdvanced:
		return true
	case CourseWriteLevelAll:
		return true
	case CourseWriteLevelBeginner:
		return true
	case CourseWriteLevelIntermediate:
		return true
	default:
		return false
	}
}

// Defines values for DeviceTokenWritePlatform.
const (
	Android DeviceTokenWritePlatform = "android"
	Ios     DeviceTokenWritePlatform = "ios"
	Web     DeviceTokenWritePlatform = "web"
)

// Valid indicates whether the value is a known member of the DeviceTokenWritePlatform enum.
func (e DeviceTokenWritePlatform) Valid() bool {
	switch e {
	case Android:
		return true
	case Ios:
		return true
	case Web:
		return true
	default:
		return false
	}
}

// Defines values for EnrollmentStatus.
const (
	EnrollmentStatusActive         EnrollmentStatus = "active"
	EnrollmentStatusCancelled      EnrollmentStatus = "cancelled"
	EnrollmentStatusCompleted      EnrollmentStatus = "completed"
	EnrollmentStatusExpired        EnrollmentStatus = "expired"
	EnrollmentStatusPendingPayment EnrollmentStatus = "pending_payment"
)

// Valid indicates whether the value is a known member of the EnrollmentStatus enum.
func (e EnrollmentStatus) Valid() bool {
	switch e {
	case EnrollmentStatusActive:
		return true
	case EnrollmentStatusCancelled:
		return true
	case EnrollmentStatusCompleted:
		return true
	case EnrollmentStatusExpired:
		return true
	case EnrollmentStatusPendingPayment:
		return true
	default:
		return false
	}
}

// Defines values for InvitationWriteRole.
const (
	InvitationWriteRoleInstructor        InvitationWriteRole = "instructor"
	InvitationWriteRoleOrganizationAdmin InvitationWriteRole = "organization_admin"
	InvitationWriteRoleStudent           InvitationWriteRole = "student"
)

// Valid indicates whether the value is a known member of the InvitationWriteRole enum.
func (e InvitationWriteRole) Valid() bool {
	switch e {
	case InvitationWriteRoleInstructor:
		return true
	case InvitationWriteRoleOrganizationAdmin:
		return true
	case InvitationWriteRoleStudent:
		return true
	default:
		return false
	}
}

// Defines values for LessonWriteLessonType.
const (
	LessonWriteLessonTypeAssignment LessonWriteLessonType = "assignment"
	LessonWriteLessonTypeLive       LessonWriteLessonType = "live"
	LessonWriteLessonTypePdf        LessonWriteLessonType = "pdf"
	LessonWriteLessonTypeQuiz       LessonWriteLessonType = "quiz"
	LessonWriteLessonTypeText       LessonWriteLessonType = "text"
	LessonWriteLessonTypeVideo      LessonWriteLessonType = "video"
)

// Valid indicates whether the value is a known member of the LessonWriteLessonType enum.
func (e LessonWriteLessonType) Valid() bool {
	switch e {
	case LessonWriteLessonTypeAssignment:
		return true
	case LessonWriteLessonTypeLive:
		return true
	case LessonWriteLessonTypePdf:
		return true
	case LessonWriteLessonTypeQuiz:
		return true
	case LessonWriteLessonTypeText:
		return true
	case LessonWriteLessonTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for MembershipRoles.
const (
	MembershipRolesInstructor        MembershipRoles = "instructor"
	MembershipRolesOrganizationAdmin MembershipRoles = "organization_admin"
	MembershipRolesStudent           MembershipRoles = "student"
	MembershipRolesSuperAdmin        MembershipRoles = "super_admin"
)

// Valid indicates whether the value is a known member of the MembershipRoles enum.
func (e MembershipRoles) Valid() bool {
	switch e {
	case MembershipRolesInstructor:
		return true
	case MembershipRolesOrganizationAdmin:
		return true
	case MembershipRolesStudent:
		return true
	case MembershipRolesSuperAdmin:
		return true
	default:
		return false
	}
}

// Defines values for MembershipUpdateRoles.
const (
	MembershipUpdateRolesInstructor        MembershipUpdateRoles = "instructor"
	MembershipUpdateRolesOrganizationAdmin MembershipUpdateRoles = "organization_admin"
	MembershipUpdateRolesStudent           MembershipUpdateRoles = "student"
)

// Valid indicates whether the value is a known member of the MembershipUpdateRoles enum.
func (e MembershipUpdateRoles) Valid() bool {
	switch e {
	case MembershipUpdateRolesInstructor:
		return true
	case MembershipUpdateRolesOrganizationAdmin:
		return true
	case MembershipUpdateRolesStudent:
		return true
	default:
		return false
	}
}

// Defines values for MembershipUpdateStatus.
const (
	MembershipUpdateStatusActive    MembershipUpdateStatus = "active"
	MembershipUpdateStatusSuspended MembershipUpdateStatus = "suspended"
)

// Valid indicates whether the value is a known member of the MembershipUpdateStatus enum.
func (e MembershipUpdateStatus) Valid() bool {
	switch e {
	case MembershipUpdateStatusActive:
		return true
	case MembershipUpdateStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for ProgressState.
const (
	ProgressStateCompleted  ProgressState = "completed"
	ProgressStateNotStarted ProgressState = "not_started"
	ProgressStateStarted    ProgressState = "started"
)

// Valid indicates whether the value is a known member of the ProgressState enum.
func (e ProgressState) Valid() bool {
	switch e {
	case ProgressStateCompleted:
		return true
	case ProgressStateNotStarted:
		return true
	case ProgressStateStarted:
		return true
	default:
		return false
	}
}

// Defines values for QuestionWriteQuestionType.
const (
	Multiple    QuestionWriteQuestionType = "multiple"
	ShortAnswer QuestionWriteQuestionType = "short_answer"
	Single      QuestionWriteQuestionType = "single"
	TrueFalse   QuestionWriteQuestionType = "true_false"
)

// Valid indicates whether the value is a known member of the QuestionWriteQuestionType enum.
func (e QuestionWriteQuestionType) Valid() bool {
	switch e {
	case Multiple:
		return true
	case ShortAnswer:
		return true
	case Single:
		return true
	case TrueFalse:
		return true
	default:
		return false
	}
}

// Defines values for QuizWriteResultsVisibility.
const (
	AfterClose QuizWriteResultsVisibility = "after_close"
	Immediate  QuizWriteResultsVisibility = "immediate"
	Manual     QuizWriteResultsVisibility = "manual"
)

// Valid indicates whether the value is a known member of the QuizWriteResultsVisibility enum.
func (e QuizWriteResultsVisibility) Valid() bool {
	switch e {
	case AfterClose:
		return true
	case Immediate:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for UploadIntentWriteKind.
const (
	UploadIntentWriteKindAssignment  UploadIntentWriteKind = "assignment"
	UploadIntentWriteKindCertificate UploadIntentWriteKind = "certificate"
	UploadIntentWriteKindImage       UploadIntentWriteKind = "image"
	UploadIntentWriteKindPdf         UploadIntentWriteKind = "pdf"
	UploadIntentWriteKindVideo       UploadIntentWriteKind = "video"
)

// Valid indicates whether the value is a known member of the UploadIntentWriteKind enum.
func (e UploadIntentWriteKind) Valid() bool {
	switch e {
	case UploadIntentWriteKindAssignment:
		return true
	case UploadIntentWriteKindCertificate:
		return true
	case UploadIntentWriteKindImage:
		return true
	case UploadIntentWriteKindPdf:
		return true
	case UploadIntentWriteKindVideo:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusActive    UserStatus = "active"
	UserStatusDeleted   UserStatus = "deleted"
	UserStatusSuspended UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive:
		return true
	case UserStatusDeleted:
		return true
	case UserStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAssignmentParamsStatus.
const (
	UpdateAssignmentParamsStatusArchived  UpdateAssignmentParamsStatus = "archived"
	UpdateAssignmentParamsStatusDraft     UpdateAssignmentParamsStatus = "draft"
	UpdateAssignmentParamsStatusPublished UpdateAssignmentParamsStatus = "published"
)

// Valid indicates whether the value is a known member of the UpdateAssignmentParamsStatus enum.
func (e UpdateAssignmentParamsStatus) Valid() bool {
	switch e {
	case UpdateAssignmentParamsStatusArchived:
		return true
	case UpdateAssignmentParamsStatusDraft:
		return true
	case UpdateAssignmentParamsStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for UpdateQuizParamsStatus.
const (
	UpdateQuizParamsStatusArchived  UpdateQuizParamsStatus = "archived"
	UpdateQuizParamsStatusDraft     UpdateQuizParamsStatus = "draft"
	UpdateQuizParamsStatusPublished UpdateQuizParamsStatus = "published"
)

// Valid indicates whether the value is a known member of the UpdateQuizParamsStatus enum.
func (e UpdateQuizParamsStatus) Valid() bool {
	switch e {
	case UpdateQuizParamsStatusArchived:
		return true
	case UpdateQuizParamsStatusDraft:
		return true
	case UpdateQuizParamsStatusPublished:
		return true
	default:
		return false
	}
}

// AnswerWrite defines model for AnswerWrite.
type AnswerWrite struct {
	QuestionId        UUID    `json:"question_id"`
	SelectedOptionIds *[]UUID `json:"selected_option_ids,omitempty"`
	TextAnswer        *string `json:"text_answer,omitempty"`
}

// AssignmentWrite defines model for AssignmentWrite.
type AssignmentWrite struct {
	AllowedFileTypes   *[]string  `json:"allowed_file_types,omitempty"`
	AttachmentAssetIds *[]UUID    `json:"attachment_asset_ids,omitempty"`
	CourseId           UUID       `json:"course_id"`
	DueAt              *Timestamp `json:"due_at,omitempty"`
	Instructions       *string    `json:"instructions,omitempty"`
	IsRequired         *bool      `json:"is_required,omitempty"`
	LessonId           *UUID      `json:"lesson_id,omitempty"`
	MaximumScore       float32    `json:"maximum_score"`
	MaximumSubmissions int        `json:"maximum_submissions"`
	PassingScore       float32    `json:"passing_score"`
	Title              string     `json:"title"`
}

// Category defines model for Category.
type Category struct {
	Description *string `json:"description,omitempty"`
	Id          UUID    `json:"id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
}

// CategoryWrite defines model for CategoryWrite.
type CategoryWrite struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
}

// CertificateVerification defines model for CertificateVerification.
type CertificateVerification struct {
	CertificateNumber string    `json:"certificate_number"`
	CourseTitle       string    `json:"course_title"`
	IssuedAt          Timestamp `json:"issued_at"`
	OrganizationName  string    `json:"organization_name"`
	StudentName       string    `json:"student_name"`
	Valid             bool      `json:"valid"`
}

// Course defines model for Course.
type Course struct {
	Currency         string       `json:"currency"`
	Description      string       `json:"description"`
	Id               UUID         `json:"id"`
	IsFree           bool         `json:"is_free"`
	Language         string       `json:"language"`
	Level            CourseLevel  `json:"level"`
	OrganizationId   UUID         `json:"organization_id"`
	PriceMinor       int64        `json:"price_minor"`
	Slug             string       `json:"slug"`
	Status           CourseStatus `json:"status"`
	ThumbnailAssetId *UUID        `json:"thumbnail_asset_id,omitempty"`
	Title            string       `json:"title"`
	Version          int64        `json:"version"`
}

// CourseLevel defines model for Course.Level.
type CourseLevel string

// CourseStatus defines model for Course.Status.
type CourseStatus string

// CourseWrite defines model for CourseWrite.
type CourseWrite struct {
	CategoryId       *UUID            `json:"category_id,omitempty"`
	Currency         string           `json:"currency"`
	Description      string           `json:"description"`
	IsFree           bool             `json:"is_free"`
	Language         string           `json:"language"`
	Level            CourseWriteLevel `json:"level"`
	PriceMinor       int64            `json:"price_minor"`
	Slug             string           `json:"slug"`
	ThumbnailAssetId *UUID            `json:"thumbnail_asset_id,omitempty"`
	Title            string           `json:"title"`
	Version          int64            `json:"version"`
}

// CourseWriteLevel defines model for CourseWrite.Level.
type CourseWriteLevel string

// DeviceTokenWrite defines model for DeviceTokenWrite.
type DeviceTokenWrite struct {
	Platform DeviceTokenWritePlatform `json:"platform"`
	Token    string                   `json:"token"`
}

// DeviceTokenWritePlatform defines model for DeviceTokenWrite.Platform.
type DeviceTokenWritePlatform string

// Enrollment defines model for Enrollment.
type Enrollment struct {
	CompletionPercentage float32          `json:"completion_percentage"`
	CourseId             UUID             `json:"course_id"`
	Id                   UUID             `json:"id"`
	Status               EnrollmentStatus `json:"status"`
	StudentId            UUID             `json:"student_id"`
}

// EnrollmentStatus defines model for Enrollment.Status.
type EnrollmentStatus string

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// GradeWrite defines model for GradeWrite.
type GradeWrite struct {
	Feedback   *string `json:"feedback,omitempty"`
	Points     float32 `json:"points"`
	QuestionId *UUID   `json:"question_id,omitempty"`
}

// InstructorAssignment defines model for InstructorAssignment.
type InstructorAssignment struct {
	InstructorId UUID `json:"instructor_id"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	Email     string    `json:"email"`
	ExpiresAt Timestamp `json:"expires_at"`
	Id        UUID      `json:"id"`
	Role      string    `json:"role"`

	// Token Returned only once to the authorized inviter.
	Token *string `json:"token,omitempty"`
}

// InvitationAccept defines model for InvitationAccept.
type InvitationAccept struct {
	Token string `json:"token"`
}

// InvitationWrite defines model for InvitationWrite.
type InvitationWrite struct {
	Email openapi_types.Email `json:"email"`
	Role  InvitationWriteRole `json:"role"`
}

// InvitationWriteRole defines model for InvitationWrite.Role.
type InvitationWriteRole string

// JoinToken defines model for JoinToken.
type JoinToken struct {
	ExpiresAt Timestamp `json:"expires_at"`
	Token     string    `json:"token"`
	Url       string    `json:"url"`
}

// LessonWrite defines model for LessonWrite.
type LessonWrite struct {
	Body            *string               `json:"body,omitempty"`
	Description     *string               `json:"description,omitempty"`
	DurationSeconds *int                  `json:"duration_seconds,omitempty"`
	IsPreview       bool                  `json:"is_preview"`
	IsPublished     bool                  `json:"is_published"`
	IsRequired      bool                  `json:"is_required"`
	LessonType      LessonWriteLessonType `json:"lesson_type"`
	MediaAssetId    *UUID                 `json:"media_asset_id,omitempty"`
	Position        int                   `json:"position"`
	Title           string                `json:"title"`
}

// LessonWriteLessonType defines model for LessonWrite.LessonType.
type LessonWriteLessonType string

// ListResponse defines model for ListResponse.
type ListResponse struct {
	Items      []interface{} `json:"items"`
	NextCursor *string       `json:"next_cursor,omitempty"`
}

// LiveSessionWrite defines model for LiveSessionWrite.
type LiveSessionWrite struct {
	CourseId         UUID      `json:"course_id"`
	Description      *string   `json:"description,omitempty"`
	ScheduledEndAt   Timestamp `json:"scheduled_end_at"`
	ScheduledStartAt Timestamp `json:"scheduled_start_at"`
	Title            string    `json:"title"`
}

// Membership defines model for Membership.
type Membership struct {
	Id               UUID              `json:"id"`
	OrganizationId   UUID              `json:"organization_id"`
	OrganizationName string            `json:"organization_name"`
	Roles            []MembershipRoles `json:"roles"`
	Status           string            `json:"status"`
}

// MembershipRoles defines model for Membership.Roles.
type MembershipRoles string

// MembershipUpdate defines model for MembershipUpdate.
type MembershipUpdate struct {
	Roles  []MembershipUpdateRoles `json:"roles"`
	Status MembershipUpdateStatus  `json:"status"`
}

// MembershipUpdateRoles defines model for MembershipUpdate.Roles.
type MembershipUpdateRoles string

// MembershipUpdateStatus defines model for MembershipUpdate.Status.
type MembershipUpdateStatus string

// ModuleWrite defines model for ModuleWrite.
type ModuleWrite struct {
	Description *string `json:"description,omitempty"`
	Position    int     `json:"position"`
	Title       string  `json:"title"`
}

// OptionWrite defines model for OptionWrite.
type OptionWrite struct {
	IsCorrect bool   `json:"is_correct"`
	Position  int    `json:"position"`
	Text      string `json:"text"`
}

// Order defines model for Order.
type Order struct {
	AmountMinor int64  `json:"amount_minor"`
	Currency    string `json:"currency"`
	Id          UUID   `json:"id"`
	Status      string `json:"status"`
}

// OrderWrite defines model for OrderWrite.
type OrderWrite struct {
	CourseId UUID `json:"course_id"`
}

// Organization defines model for Organization.
type Organization struct {
	CreatedAt Timestamp `json:"created_at"`
	Id        UUID      `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Status    string    `json:"status"`
}

// OrganizationWrite defines model for OrganizationWrite.
type OrganizationWrite struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// PaymentIntent defines model for PaymentIntent.
type PaymentIntent struct {
	// ClientSecret Sensitive ephemeral value; never logged.
	ClientSecret string `json:"client_secret"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail    *string       `json:"detail,omitempty"`
	Errors    *[]FieldError `json:"errors,omitempty"`
	Instance  *string       `json:"instance,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    int           `json:"status"`
	Title     string        `json:"title"`
	Type      string        `json:"type"`
}

// Progress defines model for Progress.
type Progress struct {
	LessonId            UUID          `json:"lesson_id"`
	PositionSeconds     int           `json:"position_seconds"`
	State               ProgressState `json:"state"`
	TotalWatchedSeconds int           `json:"total_watched_seconds"`
}

// ProgressState defines model for Progress.State.
type ProgressState string

// ProgressWrite defines model for ProgressWrite.
type ProgressWrite struct {
	ManualComplete      *bool `json:"manual_complete,omitempty"`
	PositionSeconds     int   `json:"position_seconds"`
	WatchedSecondsDelta int   `json:"watched_seconds_delta"`
}

// QuestionWrite defines model for QuestionWrite.
type QuestionWrite struct {
	Options      []OptionWrite             `json:"options"`
	Points       float32                   `json:"points"`
	Position     int                       `json:"position"`
	Prompt       string                    `json:"prompt"`
	QuestionType QuestionWriteQuestionType `json:"question_type"`
}

// QuestionWriteQuestionType defines model for QuestionWrite.QuestionType.
type QuestionWriteQuestionType string

// QuizAttempt defines model for QuizAttempt.
type QuizAttempt struct {
	AttemptNumber int      `json:"attempt_number"`
	Id            UUID     `json:"id"`
	Passed        *bool    `json:"passed,omitempty"`
	Percentage    *float32 `json:"percentage,omitempty"`

	// Questions Correct-answer flags are never included before submission.
	Questions []map[string]interface{} `json:"questions"`
	QuizId    UUID                     `json:"quiz_id"`
	StartedAt Timestamp                `json:"started_at"`
	Status    string                   `json:"status"`
}

// QuizWrite defines model for QuizWrite.
type QuizWrite struct {
	AttemptLimit       int                         `json:"attempt_limit"`
	AvailableFrom      *Timestamp                  `json:"available_from,omitempty"`
	AvailableUntil     *Timestamp                  `json:"available_until,omitempty"`
	CourseId           UUID                        `json:"course_id"`
	Instructions       *string                     `json:"instructions,omitempty"`
	IsRequired         *bool                       `json:"is_required,omitempty"`
	LessonId           *UUID                       `json:"lesson_id,omitempty"`
	PassPercentage     float32                     `json:"pass_percentage"`
	RandomizeOptions   *bool                       `json:"randomize_options,omitempty"`
	RandomizeQuestions *bool                       `json:"randomize_questions,omitempty"`
	ResultsVisibility  *QuizWriteResultsVisibility `json:"results_visibility,omitempty"`
	TimeLimitSeconds   *int                        `json:"time_limit_seconds,omitempty"`
	Title              string                      `json:"title"`
}

// QuizWriteResultsVisibility defines model for QuizWrite.ResultsVisibility.
type QuizWriteResultsVisibility string

// SubmissionWrite defines model for SubmissionWrite.
type SubmissionWrite struct {
	MediaAssetIds *[]UUID `json:"media_asset_ids,omitempty"`
	TextContent   *string `json:"text_content,omitempty"`
}

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// UploadIntent defines model for UploadIntent.
type UploadIntent struct {
	ExpiresAt    Timestamp `json:"expires_at"`
	Id           UUID      `json:"id"`
	MediaAssetId UUID      `json:"media_asset_id"`
	UploadUrl    string    `json:"upload_url"`
}

// UploadIntentWrite defines model for UploadIntentWrite.
type UploadIntentWrite struct {
	ChecksumSha256 *string               `json:"checksum_sha256,omitempty"`
	ContentType    string                `json:"content_type"`
	Filename       string                `json:"filename"`
	Kind           UploadIntentWriteKind `json:"kind"`
	SizeBytes      int64                 `json:"size_bytes"`
}

// UploadIntentWriteKind defines model for UploadIntentWrite.Kind.
type UploadIntentWriteKind string

// User defines model for User.
type User struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          UUID                `json:"id"`
	Memberships []Membership        `json:"memberships"`
	Status      UserStatus          `json:"status"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// Cursor defines model for Cursor.
type Cursor = string

// ID defines model for ID.
type ID = openapi_types.UUID

// IDQuery defines model for IDQuery.
type IDQuery = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// ReportFrom defines model for ReportFrom.
type ReportFrom = time.Time

// ReportTo defines model for ReportTo.
type ReportTo = time.Time

// List defines model for List.
type List = ListResponse

// OK defines model for OK.
type OK map[string]interface{}

// GradeAssignmentParams defines parameters for GradeAssignment.
type GradeAssignmentParams struct {
	ReturnForResubmission *bool `form:"return_for_resubmission,omitempty" json:"return_for_resubmission,omitempty"`
}

// ListAssignmentsParams defines parameters for ListAssignments.
type ListAssignmentsParams struct {
	CourseId openapi_types.UUID `form:"course_id" json:"course_id"`

	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateAssignmentParams defines parameters for UpdateAssignment.
type UpdateAssignmentParams struct {
	Status *UpdateAssignmentParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateAssignmentParamsStatus defines parameters for UpdateAssignment.
type UpdateAssignmentParamsStatus string

// ListAssignmentSubmissionsParams defines parameters for ListAssignmentSubmissions.
type ListAssignmentSubmissionsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateAssignmentSubmissionParams defines parameters for CreateAssignmentSubmission.
type CreateAssignmentSubmissionParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	OrganizationId openapi_types.UUID `form:"organization_id" json:"organization_id"`

	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListCertificatesParams defines parameters for ListCertificates.
type ListCertificatesParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListCoursesParams defines parameters for ListCourses.
type ListCoursesParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor         *Cursor             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit          *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Q              *string             `form:"q,omitempty" json:"q,omitempty"`
	OrganizationId *openapi_types.UUID `form:"organization_id,omitempty" json:"organization_id,omitempty"`
	CategoryId     *openapi_types.UUID `form:"category_id,omitempty" json:"category_id,omitempty"`
	Level          *string             `form:"level,omitempty" json:"level,omitempty"`
}

// ListManagedCoursesParams defines parameters for ListManagedCourses.
type ListManagedCoursesParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// AdminEnrollCourseParams defines parameters for AdminEnrollCourse.
type AdminEnrollCourseParams struct {
	StudentId openapi_types.UUID `form:"student_id" json:"student_id"`
}

// EnrollCourseParams defines parameters for EnrollCourse.
type EnrollCourseParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RemoveInstructorParams defines parameters for RemoveInstructor.
type RemoveInstructorParams struct {
	InstructorId openapi_types.UUID `form:"instructor_id" json:"instructor_id"`
}

// ListCourseStudentsParams defines parameters for ListCourseStudents.
type ListCourseStudentsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// RemoveDeviceTokenParams defines parameters for RemoveDeviceToken.
type RemoveDeviceTokenParams struct {
	Id IDQuery `form:"id" json:"id"`
}

// ListEnrollmentsParams defines parameters for ListEnrollments.
type ListEnrollmentsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetEnrollmentProgressParams defines parameters for GetEnrollmentProgress.
type GetEnrollmentProgressParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListLiveSessionsParams defines parameters for ListLiveSessions.
type ListLiveSessionsParams struct {
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListNotificationsParams defines parameters for ListNotifications.
type ListNotificationsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListOrganizationMembersParams defines parameters for ListOrganizationMembers.
type ListOrganizationMembersParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPaymentsParams defines parameters for ListPayments.
type ListPaymentsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListQuizzesParams defines parameters for ListQuizzes.
type ListQuizzesParams struct {
	CourseId openapi_types.UUID `form:"course_id" json:"course_id"`

	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateQuizParams defines parameters for UpdateQuiz.
type UpdateQuizParams struct {
	Status *UpdateQuizParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateQuizParamsStatus defines parameters for UpdateQuiz.
type UpdateQuizParamsStatus string

// ListQuizAttemptsParams defines parameters for ListQuizAttempts.
type ListQuizAttemptsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetAssessmentsReportParams defines parameters for GetAssessmentsReport.
type GetAssessmentsReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetCompletionsReportParams defines parameters for GetCompletionsReport.
type GetCompletionsReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetEnrollmentsReportParams defines parameters for GetEnrollmentsReport.
type GetEnrollmentsReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetLiveAttendanceReportParams defines parameters for GetLiveAttendanceReport.
type GetLiveAttendanceReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetOverviewReportParams defines parameters for GetOverviewReport.
type GetOverviewReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetRevenueReportParams defines parameters for GetRevenueReport.
type GetRevenueReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// MyResultsParams defines parameters for MyResults.
type MyResultsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateAssignmentSubmissionJSONRequestBody defines body for UpdateAssignmentSubmission for application/json ContentType.
type UpdateAssignmentSubmissionJSONRequestBody = SubmissionWrite

// GradeAssignmentJSONRequestBody defines body for GradeAssignment for application/json ContentType.
type GradeAssignmentJSONRequestBody = GradeWrite

// CreateAssignmentJSONRequestBody defines body for CreateAssignment for application/json ContentType.
type CreateAssignmentJSONRequestBody = AssignmentWrite

// UpdateAssignmentJSONRequestBody defines body for UpdateAssignment for application/json ContentType.
type UpdateAssignmentJSONRequestBody = AssignmentWrite

// CreateAssignmentSubmissionJSONRequestBody defines body for CreateAssignmentSubmission for application/json ContentType.
type CreateAssignmentSubmissionJSONRequestBody = SubmissionWrite

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryWrite

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = CategoryWrite

// CreateCourseJSONRequestBody defines body for CreateCourse for application/json ContentType.
type CreateCourseJSONRequestBody = CourseWrite

// UpdateCourseJSONRequestBody defines body for UpdateCourse for application/json ContentType.
type UpdateCourseJSONRequestBody = CourseWrite

// AssignInstructorJSONRequestBody defines body for AssignInstructor for application/json ContentType.
type AssignInstructorJSONRequestBody = InstructorAssignment

// CreateModuleJSONRequestBody defines body for CreateModule for application/json ContentType.
type CreateModuleJSONRequestBody = ModuleWrite

// RegisterDeviceTokenJSONRequestBody defines body for RegisterDeviceToken for application/json ContentType.
type RegisterDeviceTokenJSONRequestBody = DeviceTokenWrite

// UpdateLessonProgressJSONRequestBody defines body for UpdateLessonProgress for application/json ContentType.
type UpdateLessonProgressJSONRequestBody = ProgressWrite

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = InvitationAccept

// UpdateLessonJSONRequestBody defines body for UpdateLesson for application/json ContentType.
type UpdateLessonJSONRequestBody = LessonWrite

// CreateLiveSessionJSONRequestBody defines body for CreateLiveSession for application/json ContentType.
type CreateLiveSessionJSONRequestBody = LiveSessionWrite

// UpdateLiveSessionJSONRequestBody defines body for UpdateLiveSession for application/json ContentType.
type UpdateLiveSessionJSONRequestBody = LiveSessionWrite

// CreateUploadIntentJSONRequestBody defines body for CreateUploadIntent for application/json ContentType.
type CreateUploadIntentJSONRequestBody = UploadIntentWrite

// UpdateModuleJSONRequestBody defines body for UpdateModule for application/json ContentType.
type UpdateModuleJSONRequestBody = ModuleWrite

// CreateLessonJSONRequestBody defines body for CreateLesson for application/json ContentType.
type CreateLessonJSONRequestBody = LessonWrite

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = OrderWrite

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = OrganizationWrite

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody = OrganizationWrite

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = InvitationWrite

// UpdateOrganizationMembershipJSONRequestBody defines body for UpdateOrganizationMembership for application/json ContentType.
type UpdateOrganizationMembershipJSONRequestBody = MembershipUpdate

// SaveQuizAnswerJSONRequestBody defines body for SaveQuizAnswer for application/json ContentType.
type SaveQuizAnswerJSONRequestBody = AnswerWrite

// GradeQuizAttemptJSONRequestBody defines body for GradeQuizAttempt for application/json ContentType.
type GradeQuizAttemptJSONRequestBody = GradeWrite

// UpdateQuizQuestionJSONRequestBody defines body for UpdateQuizQuestion for application/json ContentType.
type UpdateQuizQuestionJSONRequestBody = QuestionWrite

// CreateQuizJSONRequestBody defines body for CreateQuiz for application/json ContentType.
type CreateQuizJSONRequestBody = QuizWrite

// UpdateQuizJSONRequestBody defines body for UpdateQuiz for application/json ContentType.
type UpdateQuizJSONRequestBody = QuizWrite

// CreateQuizQuestionJSONRequestBody defines body for CreateQuizQuestion for application/json ContentType.
type CreateQuizQuestionJSONRequestBody = QuestionWrite
