// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package apispec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CourseLevel.
const (
	CourseLevelAdvanced     CourseLevel = "advanced"
	CourseLevelAll          CourseLevel = "all"
	CourseLevelBeginner     CourseLevel = "beginner"
	CourseLevelIntermediate CourseLevel = "intermediate"
)

// Defines values for CourseStatus.
const (
	CourseStatusArchived  CourseStatus = "archived"
	CourseStatusDraft     CourseStatus = "draft"
	CourseStatusPublished CourseStatus = "published"
	CourseStatusReview    CourseStatus = "review"
)

// Defines values for CourseWriteLevel.
const (
	CourseWriteLevelAdvanced     CourseWriteLevel = "advanced"
	CourseWriteLevelAll          CourseWriteLevel = "all"
	CourseWriteLevelBeginner     CourseWriteLevel = "beginner"
	CourseWriteLevelIntermediate CourseWriteLevel = "intermediate"
)

// Defines values for DeviceTokenWritePlatform.
const (
	Android DeviceTokenWritePlatform = "android"
	Ios     DeviceTokenWritePlatform = "ios"
	Web     DeviceTokenWritePlatform = "web"
)

// Defines values for EnrollmentStatus.
const (
	EnrollmentStatusActive         EnrollmentStatus = "active"
	EnrollmentStatusCancelled      EnrollmentStatus = "cancelled"
	EnrollmentStatusCompleted      EnrollmentStatus = "completed"
	EnrollmentStatusExpired        EnrollmentStatus = "expired"
	EnrollmentStatusPendingPayment EnrollmentStatus = "pending_payment"
)

// Defines values for InvitationWriteRole.
const (
	InvitationWriteRoleInstructor        InvitationWriteRole = "instructor"
	InvitationWriteRoleOrganizationAdmin InvitationWriteRole = "organization_admin"
	InvitationWriteRoleStudent           InvitationWriteRole = "student"
)

// Defines values for LessonWriteLessonType.
const (
	LessonWriteLessonTypeAssignment LessonWriteLessonType = "assignment"
	LessonWriteLessonTypeLive       LessonWriteLessonType = "live"
	LessonWriteLessonTypePdf        LessonWriteLessonType = "pdf"
	LessonWriteLessonTypeQuiz       LessonWriteLessonType = "quiz"
	LessonWriteLessonTypeText       LessonWriteLessonType = "text"
	LessonWriteLessonTypeVideo      LessonWriteLessonType = "video"
)

// Defines values for MembershipRoles.
const (
	MembershipRolesInstructor        MembershipRoles = "instructor"
	MembershipRolesOrganizationAdmin MembershipRoles = "organization_admin"
	MembershipRolesStudent           MembershipRoles = "student"
	MembershipRolesSuperAdmin        MembershipRoles = "super_admin"
)

// Defines values for MembershipUpdateRoles.
const (
	MembershipUpdateRolesInstructor        MembershipUpdateRoles = "instructor"
	MembershipUpdateRolesOrganizationAdmin MembershipUpdateRoles = "organization_admin"
	MembershipUpdateRolesStudent           MembershipUpdateRoles = "student"
)

// Defines values for MembershipUpdateStatus.
const (
	MembershipUpdateStatusActive    MembershipUpdateStatus = "active"
	MembershipUpdateStatusSuspended MembershipUpdateStatus = "suspended"
)

// Defines values for ProgressState.
const (
	Completed  ProgressState = "completed"
	NotStarted ProgressState = "not_started"
	Started    ProgressState = "started"
)

// Defines values for QuestionWriteQuestionType.
const (
	Multiple    QuestionWriteQuestionType = "multiple"
	ShortAnswer QuestionWriteQuestionType = "short_answer"
	Single      QuestionWriteQuestionType = "single"
	TrueFalse   QuestionWriteQuestionType = "true_false"
)

// Defines values for QuizWriteResultsVisibility.
const (
	AfterClose QuizWriteResultsVisibility = "after_close"
	Immediate  QuizWriteResultsVisibility = "immediate"
	Manual     QuizWriteResultsVisibility = "manual"
)

// Defines values for UploadIntentWriteKind.
const (
	UploadIntentWriteKindAssignment  UploadIntentWriteKind = "assignment"
	UploadIntentWriteKindCertificate UploadIntentWriteKind = "certificate"
	UploadIntentWriteKindImage       UploadIntentWriteKind = "image"
	UploadIntentWriteKindPdf         UploadIntentWriteKind = "pdf"
	UploadIntentWriteKindVideo       UploadIntentWriteKind = "video"
)

// Defines values for UserStatus.
const (
	UserStatusActive    UserStatus = "active"
	UserStatusDeleted   UserStatus = "deleted"
	UserStatusSuspended UserStatus = "suspended"
)

// Defines values for AdminListUsersParamsStatus.
const (
	AdminListUsersParamsStatusActive    AdminListUsersParamsStatus = "active"
	AdminListUsersParamsStatusDisabled  AdminListUsersParamsStatus = "disabled"
	AdminListUsersParamsStatusPending   AdminListUsersParamsStatus = "pending"
	AdminListUsersParamsStatusSuspended AdminListUsersParamsStatus = "suspended"
)

// Defines values for AdminListUsersParamsRole.
const (
	AdminListUsersParamsRoleAdmin   AdminListUsersParamsRole = "admin"
	AdminListUsersParamsRoleStudent AdminListUsersParamsRole = "student"
	AdminListUsersParamsRoleTeacher AdminListUsersParamsRole = "teacher"
)

// Defines values for AdminReplaceUserRolesJSONBodyRoles.
const (
	Admin   AdminReplaceUserRolesJSONBodyRoles = "admin"
	Student AdminReplaceUserRolesJSONBodyRoles = "student"
	Teacher AdminReplaceUserRolesJSONBodyRoles = "teacher"
)

// Defines values for AdminSetUserStatusJSONBodyStatus.
const (
	Active    AdminSetUserStatusJSONBodyStatus = "active"
	Disabled  AdminSetUserStatusJSONBodyStatus = "disabled"
	Pending   AdminSetUserStatusJSONBodyStatus = "pending"
	Suspended AdminSetUserStatusJSONBodyStatus = "suspended"
)

// Defines values for UpdateAssignmentParamsStatus.
const (
	UpdateAssignmentParamsStatusArchived  UpdateAssignmentParamsStatus = "archived"
	UpdateAssignmentParamsStatusDraft     UpdateAssignmentParamsStatus = "draft"
	UpdateAssignmentParamsStatusPublished UpdateAssignmentParamsStatus = "published"
)

// Defines values for UpdateQuizParamsStatus.
const (
	Archived  UpdateQuizParamsStatus = "archived"
	Draft     UpdateQuizParamsStatus = "draft"
	Published UpdateQuizParamsStatus = "published"
)

// AnswerWrite defines model for AnswerWrite.
type AnswerWrite struct {
	QuestionId        UUID    `json:"question_id"`
	SelectedOptionIds *[]UUID `json:"selected_option_ids,omitempty"`
	TextAnswer        *string `json:"text_answer,omitempty"`
}

// AssignmentWrite defines model for AssignmentWrite.
type AssignmentWrite struct {
	AllowedFileTypes   *[]string  `json:"allowed_file_types,omitempty"`
	AttachmentAssetIds *[]UUID    `json:"attachment_asset_ids,omitempty"`
	CourseId           UUID       `json:"course_id"`
	DueAt              *Timestamp `json:"due_at,omitempty"`
	Instructions       *string    `json:"instructions,omitempty"`
	IsRequired         *bool      `json:"is_required,omitempty"`
	LessonId           *UUID      `json:"lesson_id,omitempty"`
	MaximumScore       float32    `json:"maximum_score"`
	MaximumSubmissions int        `json:"maximum_submissions"`
	PassingScore       float32    `json:"passing_score"`
	Title              string     `json:"title"`
}

// Category defines model for Category.
type Category struct {
	Description *string `json:"description,omitempty"`
	Id          UUID    `json:"id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
}

// CategoryWrite defines model for CategoryWrite.
type CategoryWrite struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
}

// CertificateVerification defines model for CertificateVerification.
type CertificateVerification struct {
	CertificateNumber string    `json:"certificate_number"`
	CourseTitle       string    `json:"course_title"`
	IssuedAt          Timestamp `json:"issued_at"`
	OrganizationName  string    `json:"organization_name"`
	StudentName       string    `json:"student_name"`
	Valid             bool      `json:"valid"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword *string `json:"current_password,omitempty"`
	NewPassword     *string `json:"new_password,omitempty"`
}

// Course defines model for Course.
type Course struct {
	Currency         string       `json:"currency"`
	Description      string       `json:"description"`
	Id               UUID         `json:"id"`
	IsFree           bool         `json:"is_free"`
	Language         string       `json:"language"`
	Level            CourseLevel  `json:"level"`
	OrganizationId   UUID         `json:"organization_id"`
	PriceMinor       int64        `json:"price_minor"`
	Slug             string       `json:"slug"`
	Status           CourseStatus `json:"status"`
	ThumbnailAssetId *UUID        `json:"thumbnail_asset_id,omitempty"`
	Title            string       `json:"title"`
	Version          int64        `json:"version"`
}

// CourseLevel defines model for Course.Level.
type CourseLevel string

// CourseStatus defines model for Course.Status.
type CourseStatus string

// CourseWrite defines model for CourseWrite.
type CourseWrite struct {
	CategoryId       *UUID            `json:"category_id,omitempty"`
	Currency         string           `json:"currency"`
	Description      string           `json:"description"`
	IsFree           bool             `json:"is_free"`
	Language         string           `json:"language"`
	Level            CourseWriteLevel `json:"level"`
	PriceMinor       int64            `json:"price_minor"`
	Slug             string           `json:"slug"`
	ThumbnailAssetId *UUID            `json:"thumbnail_asset_id,omitempty"`
	Title            string           `json:"title"`
	Version          int64            `json:"version"`
}

// CourseWriteLevel defines model for CourseWrite.Level.
type CourseWriteLevel string

// DeviceTokenWrite defines model for DeviceTokenWrite.
type DeviceTokenWrite struct {
	Platform DeviceTokenWritePlatform `json:"platform"`
	Token    string                   `json:"token"`
}

// DeviceTokenWritePlatform defines model for DeviceTokenWrite.Platform.
type DeviceTokenWritePlatform string

// Enrollment defines model for Enrollment.
type Enrollment struct {
	CompletionPercentage float32          `json:"completion_percentage"`
	CourseId             UUID             `json:"course_id"`
	Id                   UUID             `json:"id"`
	Status               EnrollmentStatus `json:"status"`
	StudentId            UUID             `json:"student_id"`
}

// EnrollmentStatus defines model for Enrollment.Status.
type EnrollmentStatus string

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// GradeWrite defines model for GradeWrite.
type GradeWrite struct {
	Feedback   *string `json:"feedback,omitempty"`
	Points     float32 `json:"points"`
	QuestionId *UUID   `json:"question_id,omitempty"`
}

// InstructorAssignment defines model for InstructorAssignment.
type InstructorAssignment struct {
	InstructorId UUID `json:"instructor_id"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	Email     string    `json:"email"`
	ExpiresAt Timestamp `json:"expires_at"`
	Id        UUID      `json:"id"`
	Role      string    `json:"role"`

	// Token Returned only once to the authorized inviter.
	Token *string `json:"token,omitempty"`
}

// InvitationAccept defines model for InvitationAccept.
type InvitationAccept struct {
	Token string `json:"token"`
}

// InvitationWrite defines model for InvitationWrite.
type InvitationWrite struct {
	Email openapi_types.Email `json:"email"`
	Role  InvitationWriteRole `json:"role"`
}

// InvitationWriteRole defines model for InvitationWrite.Role.
type InvitationWriteRole string

// JoinToken defines model for JoinToken.
type JoinToken struct {
	ExpiresAt Timestamp `json:"expires_at"`
	Token     string    `json:"token"`
	Url       string    `json:"url"`
}

// LessonWrite defines model for LessonWrite.
type LessonWrite struct {
	Body            *string               `json:"body,omitempty"`
	Description     *string               `json:"description,omitempty"`
	DurationSeconds *int                  `json:"duration_seconds,omitempty"`
	IsPreview       bool                  `json:"is_preview"`
	IsPublished     bool                  `json:"is_published"`
	IsRequired      bool                  `json:"is_required"`
	LessonType      LessonWriteLessonType `json:"lesson_type"`
	MediaAssetId    *UUID                 `json:"media_asset_id,omitempty"`
	Position        int                   `json:"position"`
	Title           string                `json:"title"`
}

// LessonWriteLessonType defines model for LessonWrite.LessonType.
type LessonWriteLessonType string

// ListResponse defines model for ListResponse.
type ListResponse struct {
	Items      []interface{} `json:"items"`
	NextCursor *string       `json:"next_cursor,omitempty"`
}

// LiveSessionWrite defines model for LiveSessionWrite.
type LiveSessionWrite struct {
	CourseId         UUID      `json:"course_id"`
	Description      *string   `json:"description,omitempty"`
	ScheduledEndAt   Timestamp `json:"scheduled_end_at"`
	ScheduledStartAt Timestamp `json:"scheduled_start_at"`
	Title            string    `json:"title"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password *string             `json:"password,omitempty"`
}

// Membership defines model for Membership.
type Membership struct {
	Id               UUID              `json:"id"`
	OrganizationId   UUID              `json:"organization_id"`
	OrganizationName string            `json:"organization_name"`
	Roles            []MembershipRoles `json:"roles"`
	Status           string            `json:"status"`
}

// MembershipRoles defines model for Membership.Roles.
type MembershipRoles string

// MembershipUpdate defines model for MembershipUpdate.
type MembershipUpdate struct {
	Roles  []MembershipUpdateRoles `json:"roles"`
	Status MembershipUpdateStatus  `json:"status"`
}

// MembershipUpdateRoles defines model for MembershipUpdate.Roles.
type MembershipUpdateRoles string

// MembershipUpdateStatus defines model for MembershipUpdate.Status.
type MembershipUpdateStatus string

// ModuleWrite defines model for ModuleWrite.
type ModuleWrite struct {
	Description *string `json:"description,omitempty"`
	Position    int     `json:"position"`
	Title       string  `json:"title"`
}

// OptionWrite defines model for OptionWrite.
type OptionWrite struct {
	IsCorrect bool   `json:"is_correct"`
	Position  int    `json:"position"`
	Text      string `json:"text"`
}

// Order defines model for Order.
type Order struct {
	AmountMinor int64  `json:"amount_minor"`
	Currency    string `json:"currency"`
	Id          UUID   `json:"id"`
	Status      string `json:"status"`
}

// OrderWrite defines model for OrderWrite.
type OrderWrite struct {
	CourseId UUID `json:"course_id"`
}

// Organization defines model for Organization.
type Organization struct {
	CreatedAt Timestamp `json:"created_at"`
	Id        UUID      `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Status    string    `json:"status"`
}

// OrganizationWrite defines model for OrganizationWrite.
type OrganizationWrite struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// PaymentIntent defines model for PaymentIntent.
type PaymentIntent struct {
	// ClientSecret Sensitive ephemeral value; never logged.
	ClientSecret string `json:"client_secret"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail    *string       `json:"detail,omitempty"`
	Errors    *[]FieldError `json:"errors,omitempty"`
	Instance  *string       `json:"instance,omitempty"`
	RequestId *string       `json:"request_id,omitempty"`
	Status    int           `json:"status"`
	Title     string        `json:"title"`
	Type      string        `json:"type"`
}

// Progress defines model for Progress.
type Progress struct {
	LessonId            UUID          `json:"lesson_id"`
	PositionSeconds     int           `json:"position_seconds"`
	State               ProgressState `json:"state"`
	TotalWatchedSeconds int           `json:"total_watched_seconds"`
}

// ProgressState defines model for Progress.State.
type ProgressState string

// ProgressWrite defines model for ProgressWrite.
type ProgressWrite struct {
	ManualComplete      *bool `json:"manual_complete,omitempty"`
	PositionSeconds     int   `json:"position_seconds"`
	WatchedSecondsDelta int   `json:"watched_seconds_delta"`
}

// QuestionWrite defines model for QuestionWrite.
type QuestionWrite struct {
	Options      []OptionWrite             `json:"options"`
	Points       float32                   `json:"points"`
	Position     int                       `json:"position"`
	Prompt       string                    `json:"prompt"`
	QuestionType QuestionWriteQuestionType `json:"question_type"`
}

// QuestionWriteQuestionType defines model for QuestionWrite.QuestionType.
type QuestionWriteQuestionType string

// QuizAttempt defines model for QuizAttempt.
type QuizAttempt struct {
	AttemptNumber int      `json:"attempt_number"`
	Id            UUID     `json:"id"`
	Passed        *bool    `json:"passed,omitempty"`
	Percentage    *float32 `json:"percentage,omitempty"`

	// Questions Correct-answer flags are never included before submission.
	Questions []map[string]interface{} `json:"questions"`
	QuizId    UUID                     `json:"quiz_id"`
	StartedAt Timestamp                `json:"started_at"`
	Status    string                   `json:"status"`
}

// QuizWrite defines model for QuizWrite.
type QuizWrite struct {
	AttemptLimit       int                         `json:"attempt_limit"`
	AvailableFrom      *Timestamp                  `json:"available_from,omitempty"`
	AvailableUntil     *Timestamp                  `json:"available_until,omitempty"`
	CourseId           UUID                        `json:"course_id"`
	Instructions       *string                     `json:"instructions,omitempty"`
	IsRequired         *bool                       `json:"is_required,omitempty"`
	LessonId           *UUID                       `json:"lesson_id,omitempty"`
	PassPercentage     float32                     `json:"pass_percentage"`
	RandomizeOptions   *bool                       `json:"randomize_options,omitempty"`
	RandomizeQuestions *bool                       `json:"randomize_questions,omitempty"`
	ResultsVisibility  *QuizWriteResultsVisibility `json:"results_visibility,omitempty"`
	TimeLimitSeconds   *int                        `json:"time_limit_seconds,omitempty"`
	Title              string                      `json:"title"`
}

// QuizWriteResultsVisibility defines model for QuizWrite.ResultsVisibility.
type QuizWriteResultsVisibility string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    *string             `json:"password,omitempty"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword *string `json:"new_password,omitempty"`
	Token       *string `json:"token,omitempty"`
}

// SubmissionWrite defines model for SubmissionWrite.
type SubmissionWrite struct {
	MediaAssetIds *[]UUID `json:"media_asset_ids,omitempty"`
	TextContent   *string `json:"text_content,omitempty"`
}

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken  *string   `json:"access_token,omitempty"`
	ExpiresAt    time.Time `json:"expires_at"`
	RefreshToken *string   `json:"refresh_token,omitempty"`
	TokenType    string    `json:"token_type"`
}

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// UploadIntent defines model for UploadIntent.
type UploadIntent struct {
	ExpiresAt    Timestamp `json:"expires_at"`
	Id           UUID      `json:"id"`
	MediaAssetId UUID      `json:"media_asset_id"`
	UploadUrl    string    `json:"upload_url"`
}

// UploadIntentWrite defines model for UploadIntentWrite.
type UploadIntentWrite struct {
	ChecksumSha256 *string               `json:"checksum_sha256,omitempty"`
	ContentType    string                `json:"content_type"`
	Filename       string                `json:"filename"`
	Kind           UploadIntentWriteKind `json:"kind"`
	SizeBytes      int64                 `json:"size_bytes"`
}

// UploadIntentWriteKind defines model for UploadIntentWrite.Kind.
type UploadIntentWriteKind string

// User defines model for User.
type User struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          UUID                `json:"id"`
	Memberships []Membership        `json:"memberships"`
	Status      UserStatus          `json:"status"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// Cursor defines model for Cursor.
type Cursor = string

// ID defines model for ID.
type ID = openapi_types.UUID

// IDQuery defines model for IDQuery.
type IDQuery = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// ReportFrom defines model for ReportFrom.
type ReportFrom = time.Time

// ReportTo defines model for ReportTo.
type ReportTo = time.Time

// List defines model for List.
type List = ListResponse

// OK defines model for OK.
type OK map[string]interface{}

// Tokens defines model for Tokens.
type Tokens = TokenPair

// RefreshToken defines model for RefreshToken.
type RefreshToken struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// AdminListUsersParams defines parameters for AdminListUsers.
type AdminListUsersParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor                     `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit                      `form:"limit,omitempty" json:"limit,omitempty"`
	Q      *string                     `form:"q,omitempty" json:"q,omitempty"`
	Status *AdminListUsersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Role   *AdminListUsersParamsRole   `form:"role,omitempty" json:"role,omitempty"`
}

// AdminListUsersParamsStatus defines parameters for AdminListUsers.
type AdminListUsersParamsStatus string

// AdminListUsersParamsRole defines parameters for AdminListUsers.
type AdminListUsersParamsRole string

// AdminReplaceUserRolesJSONBody defines parameters for AdminReplaceUserRoles.
type AdminReplaceUserRolesJSONBody struct {
	Roles []AdminReplaceUserRolesJSONBodyRoles `json:"roles"`
}

// AdminReplaceUserRolesJSONBodyRoles defines parameters for AdminReplaceUserRoles.
type AdminReplaceUserRolesJSONBodyRoles string

// AdminSetUserStatusJSONBody defines parameters for AdminSetUserStatus.
type AdminSetUserStatusJSONBody struct {
	Status AdminSetUserStatusJSONBodyStatus `json:"status"`
}

// AdminSetUserStatusJSONBodyStatus defines parameters for AdminSetUserStatus.
type AdminSetUserStatusJSONBodyStatus string

// GradeAssignmentParams defines parameters for GradeAssignment.
type GradeAssignmentParams struct {
	ReturnForResubmission *bool `form:"return_for_resubmission,omitempty" json:"return_for_resubmission,omitempty"`
}

// ListAssignmentsParams defines parameters for ListAssignments.
type ListAssignmentsParams struct {
	CourseId openapi_types.UUID `form:"course_id" json:"course_id"`

	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateAssignmentParams defines parameters for UpdateAssignment.
type UpdateAssignmentParams struct {
	Status *UpdateAssignmentParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateAssignmentParamsStatus defines parameters for UpdateAssignment.
type UpdateAssignmentParamsStatus string

// ListAssignmentSubmissionsParams defines parameters for ListAssignmentSubmissions.
type ListAssignmentSubmissionsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateAssignmentSubmissionParams defines parameters for CreateAssignmentSubmission.
type CreateAssignmentSubmissionParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	OrganizationId openapi_types.UUID `form:"organization_id" json:"organization_id"`

	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ForgotPasswordJSONBody defines parameters for ForgotPassword.
type ForgotPasswordJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// LogoutCurrentSessionJSONBody defines parameters for LogoutCurrentSession.
type LogoutCurrentSessionJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// RotateRefreshTokenJSONBody defines parameters for RotateRefreshToken.
type RotateRefreshTokenJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// VerifyEmailJSONBody defines parameters for VerifyEmail.
type VerifyEmailJSONBody struct {
	Token string `json:"token"`
}

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListCertificatesParams defines parameters for ListCertificates.
type ListCertificatesParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListCoursesParams defines parameters for ListCourses.
type ListCoursesParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor         *Cursor             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit          *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Q              *string             `form:"q,omitempty" json:"q,omitempty"`
	OrganizationId *openapi_types.UUID `form:"organization_id,omitempty" json:"organization_id,omitempty"`
	CategoryId     *openapi_types.UUID `form:"category_id,omitempty" json:"category_id,omitempty"`
	Level          *string             `form:"level,omitempty" json:"level,omitempty"`
}

// ListManagedCoursesParams defines parameters for ListManagedCourses.
type ListManagedCoursesParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// AdminEnrollCourseParams defines parameters for AdminEnrollCourse.
type AdminEnrollCourseParams struct {
	StudentId openapi_types.UUID `form:"student_id" json:"student_id"`
}

// EnrollCourseParams defines parameters for EnrollCourse.
type EnrollCourseParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RemoveInstructorParams defines parameters for RemoveInstructor.
type RemoveInstructorParams struct {
	InstructorId openapi_types.UUID `form:"instructor_id" json:"instructor_id"`
}

// ListCourseStudentsParams defines parameters for ListCourseStudents.
type ListCourseStudentsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// RemoveDeviceTokenParams defines parameters for RemoveDeviceToken.
type RemoveDeviceTokenParams struct {
	Id IDQuery `form:"id" json:"id"`
}

// ListEnrollmentsParams defines parameters for ListEnrollments.
type ListEnrollmentsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetEnrollmentProgressParams defines parameters for GetEnrollmentProgress.
type GetEnrollmentProgressParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListLiveSessionsParams defines parameters for ListLiveSessions.
type ListLiveSessionsParams struct {
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListNotificationsParams defines parameters for ListNotifications.
type ListNotificationsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListOrganizationMembersParams defines parameters for ListOrganizationMembers.
type ListOrganizationMembersParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPaymentsParams defines parameters for ListPayments.
type ListPaymentsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePaymentOrderParams defines parameters for CreatePaymentOrder.
type CreatePaymentOrderParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListQuizzesParams defines parameters for ListQuizzes.
type ListQuizzesParams struct {
	CourseId openapi_types.UUID `form:"course_id" json:"course_id"`

	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateQuizParams defines parameters for UpdateQuiz.
type UpdateQuizParams struct {
	Status *UpdateQuizParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateQuizParamsStatus defines parameters for UpdateQuiz.
type UpdateQuizParamsStatus string

// ListQuizAttemptsParams defines parameters for ListQuizAttempts.
type ListQuizAttemptsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetAssessmentsReportParams defines parameters for GetAssessmentsReport.
type GetAssessmentsReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetCompletionsReportParams defines parameters for GetCompletionsReport.
type GetCompletionsReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetEnrollmentsReportParams defines parameters for GetEnrollmentsReport.
type GetEnrollmentsReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetLiveAttendanceReportParams defines parameters for GetLiveAttendanceReport.
type GetLiveAttendanceReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetOverviewReportParams defines parameters for GetOverviewReport.
type GetOverviewReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// GetRevenueReportParams defines parameters for GetRevenueReport.
type GetRevenueReportParams struct {
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *ReportTo   `form:"to,omitempty" json:"to,omitempty"`
}

// MyResultsParams defines parameters for MyResults.
type MyResultsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// StudentListEnrollmentsParams defines parameters for StudentListEnrollments.
type StudentListEnrollmentsParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// TeacherListCoursesParams defines parameters for TeacherListCourses.
type TeacherListCoursesParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Cursor Opaque base64 cursor containing the stable timestamp and UUID tie-breaker.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// AdminReplaceUserRolesJSONRequestBody defines body for AdminReplaceUserRoles for application/json ContentType.
type AdminReplaceUserRolesJSONRequestBody AdminReplaceUserRolesJSONBody

// AdminSetUserStatusJSONRequestBody defines body for AdminSetUserStatus for application/json ContentType.
type AdminSetUserStatusJSONRequestBody AdminSetUserStatusJSONBody

// UpdateAssignmentSubmissionJSONRequestBody defines body for UpdateAssignmentSubmission for application/json ContentType.
type UpdateAssignmentSubmissionJSONRequestBody = SubmissionWrite

// GradeAssignmentJSONRequestBody defines body for GradeAssignment for application/json ContentType.
type GradeAssignmentJSONRequestBody = GradeWrite

// CreateAssignmentJSONRequestBody defines body for CreateAssignment for application/json ContentType.
type CreateAssignmentJSONRequestBody = AssignmentWrite

// UpdateAssignmentJSONRequestBody defines body for UpdateAssignment for application/json ContentType.
type UpdateAssignmentJSONRequestBody = AssignmentWrite

// CreateAssignmentSubmissionJSONRequestBody defines body for CreateAssignmentSubmission for application/json ContentType.
type CreateAssignmentSubmissionJSONRequestBody = SubmissionWrite

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody ForgotPasswordJSONBody

// LoginPasswordUserJSONRequestBody defines body for LoginPasswordUser for application/json ContentType.
type LoginPasswordUserJSONRequestBody = LoginRequest

// LogoutCurrentSessionJSONRequestBody defines body for LogoutCurrentSession for application/json ContentType.
type LogoutCurrentSessionJSONRequestBody LogoutCurrentSessionJSONBody

// RotateRefreshTokenJSONRequestBody defines body for RotateRefreshToken for application/json ContentType.
type RotateRefreshTokenJSONRequestBody RotateRefreshTokenJSONBody

// RegisterPasswordUserJSONRequestBody defines body for RegisterPasswordUser for application/json ContentType.
type RegisterPasswordUserJSONRequestBody = RegisterRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody VerifyEmailJSONBody

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryWrite

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = CategoryWrite

// CreateCourseJSONRequestBody defines body for CreateCourse for application/json ContentType.
type CreateCourseJSONRequestBody = CourseWrite

// UpdateCourseJSONRequestBody defines body for UpdateCourse for application/json ContentType.
type UpdateCourseJSONRequestBody = CourseWrite

// AssignInstructorJSONRequestBody defines body for AssignInstructor for application/json ContentType.
type AssignInstructorJSONRequestBody = InstructorAssignment

// CreateModuleJSONRequestBody defines body for CreateModule for application/json ContentType.
type CreateModuleJSONRequestBody = ModuleWrite

// RegisterDeviceTokenJSONRequestBody defines body for RegisterDeviceToken for application/json ContentType.
type RegisterDeviceTokenJSONRequestBody = DeviceTokenWrite

// UpdateLessonProgressJSONRequestBody defines body for UpdateLessonProgress for application/json ContentType.
type UpdateLessonProgressJSONRequestBody = ProgressWrite

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = InvitationAccept

// UpdateLessonJSONRequestBody defines body for UpdateLesson for application/json ContentType.
type UpdateLessonJSONRequestBody = LessonWrite

// CreateLiveSessionJSONRequestBody defines body for CreateLiveSession for application/json ContentType.
type CreateLiveSessionJSONRequestBody = LiveSessionWrite

// UpdateLiveSessionJSONRequestBody defines body for UpdateLiveSession for application/json ContentType.
type UpdateLiveSessionJSONRequestBody = LiveSessionWrite

// CreateUploadIntentJSONRequestBody defines body for CreateUploadIntent for application/json ContentType.
type CreateUploadIntentJSONRequestBody = UploadIntentWrite

// UpdateModuleJSONRequestBody defines body for UpdateModule for application/json ContentType.
type UpdateModuleJSONRequestBody = ModuleWrite

// CreateLessonJSONRequestBody defines body for CreateLesson for application/json ContentType.
type CreateLessonJSONRequestBody = LessonWrite

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = OrderWrite

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = OrganizationWrite

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody = OrganizationWrite

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = InvitationWrite

// UpdateOrganizationMembershipJSONRequestBody defines body for UpdateOrganizationMembership for application/json ContentType.
type UpdateOrganizationMembershipJSONRequestBody = MembershipUpdate

// SaveQuizAnswerJSONRequestBody defines body for SaveQuizAnswer for application/json ContentType.
type SaveQuizAnswerJSONRequestBody = AnswerWrite

// GradeQuizAttemptJSONRequestBody defines body for GradeQuizAttempt for application/json ContentType.
type GradeQuizAttemptJSONRequestBody = GradeWrite

// UpdateQuizQuestionJSONRequestBody defines body for UpdateQuizQuestion for application/json ContentType.
type UpdateQuizQuestionJSONRequestBody = QuestionWrite

// CreateQuizJSONRequestBody defines body for CreateQuiz for application/json ContentType.
type CreateQuizJSONRequestBody = QuizWrite

// UpdateQuizJSONRequestBody defines body for UpdateQuiz for application/json ContentType.
type UpdateQuizJSONRequestBody = QuizWrite

// CreateQuizQuestionJSONRequestBody defines body for CreateQuizQuestion for application/json ContentType.
type CreateQuizQuestionJSONRequestBody = QuestionWrite

// StudentUpdateProgressJSONRequestBody defines body for StudentUpdateProgress for application/json ContentType.
type StudentUpdateProgressJSONRequestBody = ProgressWrite

// TeacherCreateCourseJSONRequestBody defines body for TeacherCreateCourse for application/json ContentType.
type TeacherCreateCourseJSONRequestBody = CourseWrite

// TeacherUpdateCourseJSONRequestBody defines body for TeacherUpdateCourse for application/json ContentType.
type TeacherUpdateCourseJSONRequestBody = CourseWrite

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9XZPbNpJ/hcXbh7tbydKMx9nN3MPdZBxnvbHXzjjOPqR8KohsSVhTJA2AcsZT89+v",
	"8EESIAF+iZRncnmyRySB7kZ/obvRuPODZJ8mMcSM+pd3fooI2gMDIv66zghNCP9fCDQgOGU4if1L/02K",
	"PmXgrRGFby68QLzlBUnMEI5xvPXYDjzK0DoCj+E9UIb2qYfi0Hv//uVzj2GYrwmgj0Ce+DMf8xE/ZUBu",
	"/Zkfoz34l74c0p/5NNjBHnEI2G3Kn1BGcLz17+9n/svn/HfxeYrYrvwah/7MJ/ApwwRC/5KRDPSRNgnZ",
	"I+Zf+lkm3rSN/JOAJx++At3x44ewTxMGcXD7I5TT7ACFQMp5tNfm/L2mSffot1cQb9nOvzxfLmf+Hsf5",
	"33+1gfAK7zFzIRiJh/rwIWxQFjH/8vzZjM+F99nevzxTM6m/inlwzGALREx0A2lC2AuS7F2zbfgzKwFD",
	"xGDOOchKRTnyz4lrXJb0H/V+JnjpJYO9lIAkiiDgbP8DCHIlKRDE/34ZCkJR9oZsUYy/iB+pPzNE6Nc7",
	"/08ENv6l/2+LUtAW5SsLJWL3s9Y35Yrdf+BcQNMkpiAgPF8u+T+2j4v3Fq8wZYJmDG05WL4J9Af+iPMW",
	"UPZdEmJQuGeEwj8JZsD/5PINsSACStMIB+Ljxb8oVwl3GqFtoMindKGPeZ/PWnL0/cyAbNy56yPbIbiB",
	"DQG6+zn5CHGvyVPCuYMp8hE5zIrl42gi+fS8ynoz/zMH6U0c3SpADNB+rQz3ofg+Wf8LAmZF5b7CKpL4",
	"I6+lnNm0D/kTrmYoG21CPtiNQsg6rZCleYq2OEYMQi8SbD/z3/zYCwYUhpg/QtFbbUWlxrVQ3QTiXRYE",
	"QOkmizxSwGqy9SQcbYPFfD7z35JkHcG+Yf5UvvHnfnDk41pAuHlx7X178ewvnhrZC4EhHFEOjpAwOho1",
	"xHBvESZWOBKGGPdNkFge4Y0okfKESHmp+HLmv6dARoNJDGYBR/2e2ydBhKuYfgZS6Dz4De3TSPxXKGac",
	"xCvMjc7y7K+bi/AC5n9dP/vL/C/rzXKOzp8t50/X62cXm3O0fnqGuOUDbrkgXCWp+lZo/g5fr/0P3A4a",
	"2swAoQXn9y+fc0JaAbjzcW5bu4yhxA0Rgm7F3/AbWyFBKLtTqKtMHea6wpz5V5TibbyHmBVEN5FGUZR8",
	"hnC1wRGs+OcmApXZ69AixlCw4xOsEKXARiFBIJRrj3UIM1gh1io9uaPOP8ExZSQLpHdgwxTTVUnp4vk6",
	"SSJAQtVEQGkvblFO5YoGCQFlLqVfuXyyLF3LONuvgRgfZOs9pjQHtckd5c4ZpTje2maxTMEwkwLYzGfl",
	"iuSfVNGpTmyH3saj14jBNpF7EZM5DYViW6LOpJf+smUIGmXbdvQF3mIM9UUTHg5Ja0MmB1HzoWouVGeA",
	"W2HlcG24wodfgMj/KcBMqIPyxZXiGhvwij9c3MSliWYQ9hXSRLPuK/casizkCsj5wgFF2CrEFarJ9yoD",
	"VpCzAaWjN7ORzLoEOxRv4S2i9HNCwhu5NXH7ZhsUUaiarCAjhAOaqlGMTWDxY7sjPvNj+Nw6irYBP1ue",
	"Xxg78LP+7n4N+AoUVqIV/r2NEMFtJU7w1IDxqUWcxlMxmK42BMBhK1C8zdDWzp4RHCAS/lDM1fSv/hq2",
	"OI5FnIQrdrKHECPG+QyFBxQHwGmFokgjUTmawZ7dwU8JDmC1x7GMhhXrj2P2zYVvMzQOTcTFB7GM6giF",
	"BG2YCO4cMHzmtiJbR5juJCIk2OEDhFZs2C7br2OEo8K96OxUOHXRAQhV692Kps0QVClcmkRBEpOptLXP",
	"V7qgUMk0Jv1nJT+X0LrFwWFwAmWPetBsOjF6IMLRxuUWX6kLx4/ApXp085kZ3bS5AU083IREhZ/7Mu6R",
	"/PocDjgAsYt1MG0aIcYR0lccxSFJhJzhhAvNZ1jbdUUehmr2jeRrs3IqG6TfxySJor3aHVcEK+G7ViH9",
	"KZAAYmYyb+ld997I9Nh61pRsCnHI/e8U3Qq4Zz4KGD5ID0ZALEQDfksFJWZ+wKUlihyaN3eCuoJk05T6",
	"tkEbT1OAdlraVuQFhij8nhApueaKbPgzq2TugVK7aqnAK4coP7CB8ANBoUvbbgDCNQo+WqFIE6yyT42b",
	"sd4RiAoOahob6C/VdjchZUigjgQu3hq87MYIdkgOmDl2G7BHOLJSUHIt7b3L7yxPJHF4C4VWqUTbgGUk",
	"htBL4ujWS+IAPJaItCDK2C4h+AuEHua4yhxghw2mxF6BYqDcTMerIIDUspq2sPz5ctZJPTbP6JCBYvkK",
	"k5SjVKNqTu5ceRk+FQr3OPZnGjOV+sOiqyoIGGS04fH3BMdF6qOCwTA2c1memZ8RkyAZwf6so4Hi37ay",
	"wSsRhXIsyDoJb61gtflrYSZTgCsKQRKHLtWl+UaYrlLl3ludPP68cPpdb3QKuMkHJesccAgJt+fhxpfh",
	"U+6wSMP3KcNfuCEsdZ7N1AkXsrfrliYU5wRsDsl1DLLlzpiOpzaNQWOTXBXyWvlEzyzVFX8ers3/Y4nK",
	"xvAbWwVFvUSLQhPj2AE5wDsQ8UDXxqV3+LeFm/n7YRZBuIK4dwyq/JgyRFhv1TA8wGqZ2YKLlcbJFsfD",
	"QkpuHa5vCC1mZOYfFT/qHT7KwWqMF70G7lvRHU4tPN+ZvwaGVLpFL7mZMmUwV2w0S4EUxvAYC1kX5nL7",
	"0MExqQc8bDHQwqeXGDUvx/s0RDbZd1PjOPz3OFYVL2cVYsz8LMafMlCPVTy0vr0qNlM0o3yrZd02VajX",
	"hSQJl+aBOYPJTFAxsA3kN2mDD4jpKkgI4a9ajXgPkLklb4dY2ntt2jboSQiWLSTaJ1nMegVA9WjZEYHj",
	"XqJYcJQBrwaLE2Vb1l2ztN1y7rWkeU9b7bR6drDNgpLKzAQQ659Smi5n2HMl9RSdHhAp0WqjiUMCi0Si",
	"u16yKbGYIsaA8C3u//6K5l+W828//Pnf//tyXvzxH//5p9YtTFv+8a2MUb0s6k8qaxthiBnffBBZk1gp",
	"QIKYC/gBPEh3sAeCIu+Aogz+y4vhAMSLku0WwvZttzmPFdCynkiTG1nhw02IMAqebpu8fWHkPEw9zUdX",
	"5Yf9SlwUS10snxZK3H+RkDUOQ7FJzG3ZOsnY5TpC8ce6kObg2uIqhCSke8WGFoSzOBXcGqM4cPg5GvZd",
	"ZKeD8cohMPfXcwIb4MoQ2nfacotVONwSBgcfbAlQWufV3mUguXXS99aWXANT/lHuf8QJk/sAUHZA/a+M",
	"7dpj4gxFq8+I8W1D04wVypRY5aBYAHcN30RAmxnaozhD0SrHpNyZ1Cj17GI58yvTrUKIGPIvny5rjF8b",
	"uMkj6R7rcABwp5WNny975WEspLVPYiPtTyps7LAHsjatu4zr7p1FyG2xbHv5UndXLyXJPmVWCS9i4tWw",
	"D8XxVtYhZRHDqfgvd95Xgnk42+4SUlTStbrq5jwFSAW+RiAmJ6l9NfCXK8ZgbwvJIvmgXkqjR9K6axJE",
	"qStY1pKZytGtbzP8a+lHzyXlvE2EttRDBJRtxXEQZSGE3ho2CQGvLO8SR11yDutRYVznsU8Z/rLq5UGT",
	"Aa5gL3ctB2lWXUPNdyuJasDk4hJXSaYaP8rPrzTLDjogHKF1BKuNOoHSmQDlp1nMpIPQ+dv+qc3TF1xy",
	"+aikaB0He2zZOILiMNnjL7DSNGgdqvI1Q6YsLwLNIkZXB0zxGkeY3erqDO+1QoYNA7IKooTKOkpuxOzW",
	"He9B8onVeB0TCbAFJE3OrNPXxug3sMWUARkWjQwxTSN0u7LsaXIT27Sn+VrBzPPjo5kzE3c7aSmw4woI",
	"T1H2N/NHOh+U58VaqwTfFSbJoWLNhM9INfvaaYq6aNVgLJVpx4N76jCJOP1RtxniyMfKkYe0rYmZ6ewG",
	"QO28V8elL3y3IIk5i/rfASLCdDbrIAOr6vTG2K1pUrFy7SdXZ/77NEpQ6ApMTF6GMCwVmQmgV0OSzVgW",
	"vRizGgO2k1ajmCujt4PgI832K7pD58++qYeZNlfzF8v5tx/uvrm4/5NtWZRwFZxUe2GDI3BG7D7iOHSn",
	"jPFeFrlpWWKjitteHsUt/vqWqeofZw3eWeveTwCnIVBB1pjKSn9qi2dXLWcP23hELLuMfXVXqlqOrjFR",
	"1ZCImfkhuGIgTZU2BpE0R15Hw3IOdeZTCDKC2e07joMkuNRpVxk3bnf+Wvz1Iift3//5s187Rsn3p/MI",
	"HyD0Xr1+lx/bE1rtiXejn9yT+y8k6nzykqP1rUcSWY4jjvpFyTbJmAdxKHesT/Kj4cINrSjcHWOpPLSH",
	"401iaX+gBTTnmCaROGzKobx6+/KJdxVFZdsDCdz7n68FGPskBobIrScTFNTLKHiK9T2RrfCyGEvw8njm",
	"2x2i4J3l42tFpJf+2ZPlk6XIpqYQoxT7l/7TJ2dPlr48xi5Iv0ApXhzOFiIruJCeK13c4fB+oYoiqo0f",
	"2k+tc37+IDb9lkPxV3yit3JodSRhyJn18hDxxfl5++vlGdTylLscQp1vN+kARQmrgGgLLkReYcq+114e",
	"5fj9K0Ak5gJogUxVqLaApXIEf8OUJeR2HKje5jNboCKi2QJdJAcgeR2TG7o36i3ZomEQdG9+NGCTIzlI",
	"lgNH4ABxBs2w3ciXTgRaRlUvlWYOey9em7x5xMzeKeNTc6cV+0eFPSi/rBRb60XWhjnCFK0jhz2yT6aq",
	"PutT5WUNfJuBgp1Q47L+wTL4Eb0zZv7F8ukwLWTptWHhEaGRmxnlBxB8Mohn5YFzjsXFOFjMhpiMBtQX",
	"RXHLMFOUueU9jVAAnAA3Ygq91cntMQ0+3LVJPZiyb/VNtS2Io3bG2tlkmKrjTPPt5Ky/KH3ZYQyAWLBz",
	"sMA7KTjvioKjUdbfechkkN6zlUYNW9YLS02AGM8LxKnacLIlLbaIc+1Ye7Ni+wFYeeaiDE2NYZevKAVK",
	"c49mNipbyQo9J+TD2KtpH1iN2o0p4E6adVvbxZagEEbeRIjTRFd6zKEyuNVLEMdOVpuErAhQfUksncxU",
	"yLd26v3DNAuoHY96SGsnfmAjL55gVmas3imwc/vZ3Ie70t7rxE16kueIbn8PtQVcTT1al/JaVNxVlnJ8",
	"6ai24ukkImeTMFFhr2TUrE6S5+L3Ju62WODnKgTXtALtBvKxmcVugtawk8x7I3RsiTCV8h7Ensvp2HNR",
	"aXrUQem9076YRn/05qNpVGM3PfYwHbYxNVoWYjaPkm0Lg/DXXvG3Oolq/bDL78UyThTgydhusU4SRhlB",
	"8piVlT2/K145Lrhz1gODmX9xPnATeJWxHcQsb4xVR1nuNOd69YRDLo1GTxPJor2b1NDNdD5Ovp0WmR0q",
	"D21Sj8Ah+Zjvsfsux/lEy7FJyDZhHZbjhXhxhOUYePbdWvgzLAxyXl+5HyAGgoMyV6h3aO0tDHma07/8",
	"9UOPtYiSLY7dKyBOp+YLUIR7x5cJ4xTsWP6M6uh6ClU0nPqJDBU7yZ9k7Fp2X1MnsesrYAdT65+9MJpI",
	"d4vRycmGK5D73mSYoyhqI8VVFCnIaKeNzlUUjaAM++Cyb0j4ZWz3Gk5oU/vArSq23AsgehaDwUnjc+KE",
	"Uj1cSomqi22gjXrjKE2pH1ozKoL87+UT712RyVEmLM/t/I/69kkgLi8oLauP5lESb+cycyNMbrojSNqY",
	"bqq5WhXcfetQcVRkOoKbuySLmadOT/YP/w9wTQYvPIUufopR3TuRhbRWEB/tNAoMTytLXAfPc53cRFP+",
	"Yi9lf6Pr96cT6ckDELy5nRc+pB160an39vu8vdEobmu30uyuPaIGco5AyRNEwANNaX/OUe0xFR2c0YPr",
	"8rVHcvFJWRLWHCkq+m5PtCM12mF3V/CjTm69Q6N81lJHV7JIx4i5QdIh8XJj7UaPWj+8Fe8fQLYvVFms",
	"3SLN+ouPRJ7tlZQ6ysp+LO60H/8hzrG5qxKkMbmufuDYSFT2cWgDSl1LRvFCxNCg2iu73tZQtsdszdvQ",
	"AisWrqBtLaHioqpIQ4TJ5zhKUOgk5HP1gkbKKhGf2iI1evk3xdsYQu/9zSvXyh9bi6aKopuFQ73zqGo0",
	"6+H6XuF5a1Zca5w9wnBF0283B57W7pcF6z332cbVZkMyO1MVvOcl/3sUoy2EjVz+Wr5zMmb/OgmbRjK1",
	"lauNc6RhaBnuxD7QRNzfkzbfTrSssuh0Ls9+DKt5chbDa/27h6dEm8/UyGMoLv4bb3+gtXe37BD0p0fI",
	"oMNxM1ZLFnqMfTxJjjqCGPdivWOYzolLhSN6jmzeQmvRxV+Lpb6djKXKlpi0acN6A/vkAC/1/pkdiiPM",
	"9u5H6oEuwTcO5NhbZLvMiLoZgx5T7JGtffiHxs3kEE76uDhkL1qOdtkLXCuUx/dPx1s46dTKNqoTLZre",
	"o3WiIqf2VdNOsrpk+n2cjnYmdfqFe7jnZw26l03tRy8fl5O/SMhN3tT9RJZa+XJdVMC7/NWvso05MgIy",
	"Rf2dRtNQXGc0Z8Ulv83GVrv9qL8no+7rH243/5GwIl7XFCTIU7MmtFOo1dptUBPp1irmtRWk7Ul4Cat/",
	"EmgWd4Kj7rtylD8iS7TGWpnGEP3jq116EtTbETziML2GcGsO6Vrcx6XtFEZIlxgK1BXvaZ3yxBukaULg",
	"1aVYyH6CdHEn//OSO1l6m9/BkRNTYvLRjw6b2M5/y6CWvASo6FE8jbo2O/h2T++NOrmNdbRnfcXRWPB2",
	"8TAoPKZkPjjXBhd3fdEFKu8Xs2+dxXPtXrepts6VC88efgeAQsN0qh6QUjxK7YCLlV1THJOHnyJKr8E5",
	"QV24dmXaKasUInyAeRAhWuzDiuqrMY+VA3uFD3DN5ym996EyMXTfhg/gKVQtRNAr9Zw+oHZRGB18yvLR",
	"nFWuUKw52qWRZioZqd7SNtHerCOjdPSdq3Q51kRX18SpVieedwIF+0A5aDkpBy1A9gEdNT8VTrv6zQj9",
	"K8HxfAozoiFV3pc6oYNfTmLx8PlD2QlzOKVEQ/6xw7h8zJMt/x74V9ke5lG+d3DZzxvxXrHFOMYDuBgz",
	"UykaDS9kd+E5FmzTEHyTxs7oyDyNrqq3MD5xvbKBo0UA5HMP5y+UdH7NKdpOZCkD+kU4Y6bg1LC1laqf",
	"Vp10J+akhay1EP1156pJ9vgZSD7TlZjj/c2rr+F0N6M/8dqLySUDjKEFbbjItHXHzbSWEH54hfgPK1s9",
	"0vZWX5888jGJpD2s4MBIuf7YyMU07YvNrM0jyY40ZL0MzBcEUNh8aPs1Ih+vosgY8QZsasci6/xj0RUB",
	"hcPgy2IBoThu6lym9+Ilfcxr8f4IotcZUFW8gMKx+41yEupQ2Gk/KmYJCZt6THNueyNfeSTioPUhb9Z1",
	"8rbiUeoex9eV2r3CJ/aXJVksjrJ6cIQTaW8RLzmwYxgqX7TJNstO9OX8EYReMiYh3JGvr4dq/sAlVEfl",
	"irXlzm8rUDupSTwa8zrkKdOoxkQ2BhI3InvqRuQucqEnv0oFbacJ24k+34vrJIpAXAX4AzBxn2a1H2SK",
	"fzkzE2sGVeIsilo1p3Z7+IDjHvWbtof5fjoYvXd3R1Q2NqQljUVrPQ1UI2RvO18jwdds0N+yNTsF2yyn",
	"ZpuhbKCn/SdRdCcsEvgqfomGn0W56k9PtqTqLqsW57n8TF3HNU7N/xgSO3Gli5tki7vyHrCXUkeOVROm",
	"D3x0XVhXdaZdtDZR5KmYQE4+eoXO+ALTehUVZ+nC9Xl8u0sLqtpuuoNPOuIG9MiwWSesWr2ZClpHRy1G",
	"3HQUqHyG9S5JPtIFF3N536Ur/8if/1O+/stZpwjYW5IEIO6NFyK1HKNfh2NpsnWEA0enkiSEHs1JptwT",
	"adP8ovU0sRnwB9f4JAlhcC3+pwx/masrvdvl5qcMf7mSL9+Ii8ynXBJtMtsyqEdeQjx5qbro/0dEJ0CW",
	"eOUF616aRDi4Pa552/GXCTQSfYFi+jnXx6PdC/YOHUBQUQw+1ZUWYvCvc1+AhZCTXdKjs+Pv7uocCyEn",
	"vDGnSsqvo0CUButOH7HiuHspN5//J/VNvxz0EQHb6a89qaE1viTkw48vDKNRtsIcX1qO0v+k3vnjRqZ+",
	"NzJxuk3GZPjL17mzRDFMDzUy+d1L9kke4q1LCtLfxX1LPVlwOQ0LLnLD36rBrvIXH0kMZBxudFf9Njoy",
	"Z6feCX3GbJdkzJN7Ce8j3A7ghcLJmST0/zB9hxFVe35FO9JeaL4TNn+tuKi9H9HlZy9Isu8iXfLtn5OB",
	"AnZkCNZxg3xOM1Wc2lj7JhoTFq/9QbMuvRSM08t/0EyeC+E2Lw5RHEAT3V7hA1wVb/5BuuQAJO+E5CwV",
	"UO/8QS0CB4izRga7ka/8f6YVzSJGm243en0rQzWPvAuM6rfVesnpqE6qmLLlUtCpfKEc4U6N+XNQzd78",
	"ky/GgF7vdUjz7u8PoCPIBwuOXXwEhdTvqu2SBf/mDJciQpdmSA9oTX8/fYwU/WWc54E2Mpq2Y0YjH7eW",
	"qSj6qUT83zBl1mtoxqsmySE7WUJTzmfJa04VJ2vAcJoEmcKwY55sfCS7BwU1k1GJDT70yJ0kcbcA3rgU",
	"Vt5uG01Lf3dy46g5n6dia63p9ZRczQAFOyCtt978LN876eU3p7rsReH2u73zpbLGze6dIsY4d5uc4Ji4",
	"gvfBXFkyZDH0PvMj6hODr12n/Ec6lG1FS2rJ+SR9wRVyenvwE/QGz9Hs2q5QQTl618LJJGiKtoc2+mkN",
	"/rrYnKJP32gBj25N5AwRKoDwJ23nZqNRV0Yrm7s5ALXwWnESdkBHt9JaNMz5wNq6mfw+Idhd1nSCPmsK",
	"P9Vu7asiN0UnsVzx5w3FTohg1746htZ/oO11DClwwTiy1j9B3xtTYTuM2cg+T1tpo2bHygrHk5UIGhSx",
	"V7Cdjb+f7Fq9Z4jK9EV8pb16DLV8hoxOA7Bl6TqnsRV4tVT20SA6sqA5gLVozJHHGRqJL84bnCgYk9G2",
	"48fv6SNq3dNwmFRg2nqSimM7iODiwzHPwR6bkSrOKXIf6SNuuCKAeyE/YqZOKnbShrLJ/6jHFN2+0LAT",
	"l18Lj0pGZgcoYjuxCA1idoD4yJsrdGD0iQkgGZBytKJFIT5q6pn/rC/H10DdAyM4cKuh1+p5l+vv35Jk",
	"D2wHGfXyYetzmj/c+d8BIkCuMrYTzz/wx+SQC55oSuovhI5Sq3yX5135NxCz4ljqrHhiyrP2IHfstJ9k",
	"Q03thyI3oP2m63D9VV1utN8LPtR+M7u4aQ9K83f/4f7/AgAA//8xszpGle0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
